### ISSUE TITLE
npm install argon2 fails

### ISSUE THREAD

**Issue by mhamill** [ranisalt/node-argon2#1]
Facing an error while trying to execute an `npm install argon2`.

The installation ends with a build error stating `..\argon2\src\core.c(24): fatal error C1083: Cannot open include file: 'inttypes.h': No such file or directory`

Detailed npm-debug.log as well as the error as displayed on the console are attached in [npm-debug.zip](https://github.com/ranisalt/node-argon2/files/72472/npm-debug.zip).

Please help.

**Comment by ranisalt** [comment]
@mhamill do you have GCC installed? As this module is based on the C implementation, it needs to be compiled, and `inttypes.h` is part of a C compiler (clang may do too).
