### ISSUE TITLE
Install from within Vagrant VM fails when /vagrant is a subdirectory of git repo

### ISSUE THREAD

**Issue by drstearns** [ranisalt/node-argon2#10]
This is similar to issue #4, but different enough that I'm guessing the fix will be different, so I'll open a different issue.

I am trying to install argon2 within a Vagrant Linux VM. The `Vagrantfile` is in a sub-directory of my git repo, so when I `vagrant up`,  `vagrant ssh`, and `cd /vagrant`, I'm in a directory that is mirrored to a sub-directory of my git repo. I then execute `npm install argon2` and I get this error:

```
> git submodule update --init

fatal: Not a git repository (or any parent up to mount point /vagrant)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

Git complains because it's looking for the `.git` subdirectory, but it's not accessible from the Linux VM because `/vagrant` is mirrored to a sub-directory of my repo.

I tried to exporting that environment variable, set to 1, but then I just get this error:

```
> git submodule update --init

fatal: Not a git repository (or any of the parent directories): .git
```

Not surprising since the Linux VM can't get to the root of my git repository.

Do you really need to add a git sub-module to the current repo in order to install? The bcrypt module doesn't seem to require that, and it installs perfectly in this configuration.

**Comment by cgmb** [comment]
The actual argon2 implementation is a tiny amount of code, and this is clearly causing problems. I agree with dropping the submodule. If we want to be fancy, we could use `git subtree` [[1]](https://developer.atlassian.com/blog/2015/05/the-power-of-git-subtree/). but I it would be perfectly acceptable to just commit the versions used directly into the repository and note the version or hash they came from.

**Comment by drstearns** [comment]
That sounds like a great solution to me, and I think that's also what the bcrypt module does.

**Comment by ranisalt** [comment]
I have already fixed it in this repository but I have not yet pushed to npm the fixed version. The problem happens because `npm push` was not pushing the .git directory, thus it was not possible to init submodules because... well, there was no repository.

I actually discovered that npm was pushing the submodule already, so there's no need to download it. I'm going to publish it fixed on 0.6 now.

**Comment by drstearns** [comment]
Just verified that your change fixes the install problem in this configuration--thanks!

**Comment by cgmb** [comment]
> I actually discovered that npm was pushing the submodule already, so there's no need to download it.

Ah. That makes sense.
