### ISSUE TITLE
How to link the argon2 library statically?

### ISSUE THREAD

**Issue by jannisch** [ranisalt/node-argon2#108]
Sorry for asking this question here in the issues but I hope it will be useful for other people, especially for "serverless"/FaaS apps.

I've tried modifying the _cflags_ and _ldflags_ in binding.gyp, but it won't compile argon2.node as a statically linked library including libstdc++ and everything.

Is there any way to achieve this?

**Comment by ranisalt** [comment]
What did you try to add to the flags? `-static -static-libgcc -static-libstdc++` might work.

**Comment by jannisch** [comment]
Just `-static` as far as I remember. Unfortunately it fails with this error:

```
> node-gyp rebuild

make: Entering directory '/home/jannis/devel/argon2-static/node_modules/argon2/build'
  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  AR(target) Release/obj.target/argon2.a
  COPY Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
  SOLINK_MODULE(target) Release/obj.target/argon2.node
/usr/bin/ld: /usr/lib/gcc/x86_64-unknown-linux-gnu/7.2.0/crtbeginT.o: relocation R_X86_64_32 against hidden symbol `__TMC_END__' can not be used when making a shared object
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make: *** [argon2.target.mk:145: Release/obj.target/argon2.node] Error 1
make: Leaving directory '/home/jannis/devel/argon2-static/node_modules/argon2/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
```

After finding [this](https://stackoverflow.com/questions/19768267/relocation-r-x86-64-32s-against-linking-error) thread I also added `-fPIC` and `-Wl,-whole-archive` to both flags but it doesn't make a difference.

**Comment by ranisalt** [comment]
Try `-static-libgcc` then, it seems to be inside GCC stuff.

**Comment by jannisch** [comment]
Sorry, I totally forgot to answer after trying `-static-libgcc` and all related parameters.
It seems like node-gyp is super opinionated and prevents static linking everywhere.

However, since all FaaS providers now support Node 8 my question pretty much irrelevant now.
