### ISSUE TITLE
v0.17 bug - stopping getting correct results on a Unix VPS

### ISSUE THREAD

**Issue by ibudisteanu** [ranisalt/node-argon2#110]
Hi Ranieri,

We really love your repository, node-argon2, and at [WebDollar](https://github.com/WebDollar/Node-WebDollar) we use it. The v0.16.2 from October is very stable and it worked on multiple machines, Unix and Windows. As, I have reported before, we had to adapt the v0.16.2 to avoid generating random salts.

The new update, v0.17.0 works like a charm on my Gnome-Ubuntu PC solving my issue with the random salts, but somehow, there is a _problem on my VPS_ ( it uses Debian ). I install it, and it starts generating correct Argon2d hashes, but somehow after a few (random number but relatively small, like after 3-6-7 correct hashes), it starts generating bad argon2 hashes. The particularity of these bad hashes have, is that they have a lot of zeros in the hash. My guess is that maybe my VPS has little RAM and maybe this is the problem. But, again, the v0.16.2 works like a charm also on my VPS (but I have to manually fix that salt problem). Any ideas?

Here is an example of wrong hashes

data
```
001296448d71d672cdcf84e38bf76ed255bb6999943c285b6ba8f4f3fc10ac410000006b0001026ea8794036ab9b22f2c13a4de08ddfc05623750fc3ddc94f6f8d937c4af2e30002e702a59ad71e346e283fe4cf07c5c0b6a6ded95393f8f10d27cc57fe9b4d4dddb768143fe57382dc04ceef328ee87f98630ab727b6071dfb259a19b46484fa659ddc5df6e0e2761359d30a8275058e299fcc0381534545f55cf43e41983f5d4c945675d7682c8b5955557b2ef33654f31512b9b3edd17f74b5bf422ccabbd7537e1a006B
```

```001296448d71d672cdcf84e38bf76ed255bb6999943c285b6ba8f4f3fc10ac41 ``` real output 

```0000000000000000682b438c677f000020000000000000002100000000000000``` argon2d v0.17 wrong output

Params

```
consts.HASH_ARGON2_PARAMS = {salt: 'WebDollar_make_$',time: 2, memPower:10, memBytes: 1024, parallelism: 2, type: 0, hashLen: 32  }
```

Any Ideas? Thanks

I can confirm again that 0.16.2 works on my VPS again. Here  is an output from my VPS, hopefully it can help you out

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.2 (stretch)
Release:	9.2
Codename:	stretch
```

**Comment by ranisalt** [comment]
I will look what could possible regress between 0.16.2 and 0.17.0.

**Comment by ibudisteanu** [comment]
Hi Ranieri,

If you need any kind of data, I would be more than happy to help you out. I didn't encounter any problem using the 0.16.2 on the Debian VPS

**Comment by ibudisteanu** [comment]
@ranisalt I also checked on a Gnome Ubuntu laptop today, and the new version 0.17.0 doesn't work as well, but it behave differently. It just generates different hashes, and if I hash multiple times, I get different answers. Also it contains some zeros at the end. I installed the 0.16.0, and did my change avoiding random salts,  and the 0.16.0 works perfectly on this laptop too.

**Comment by ranisalt** [comment]
I can't reproduce it no more with latest commit, when I updated argon2 version. Can you check?

**Comment by ibudisteanu** [comment]
Hi Ranisalt, you mean your latest commit or your latest release? I am not sure how to verify your repository without using the npmjs `npm install`

**Comment by ranisalt** [comment]
I meant latest commit, but I just published v0.17.1 with a hotfix and it's on latest commit.

**Comment by ibudisteanu** [comment]
Hi Ranieri, I tested the 0.17.1 and it looks working fine on my VPS with Debian. I will test it today more intensively and in case everything works fine, I will close the issue.  Thank you so much for your hard work @ranisalt

**Comment by ibudisteanu** [comment]
Hey Ranieri, you nailed it fixing the bug! Thank you so much!!
