### ISSUE TITLE
Problem with typings

### ISSUE THREAD

**Issue by xibre** [ranisalt/node-argon2#115]
Hello. First of all, thanks for the library.

I am writing an application in TypeScript and I am unable to compile it when using the current version of argon2 (v0.17.1). In particular, the following line fails to compile:

```ts
let hash: string = await argon2.hash('mypassword');
```

The compiler says: `Type 'Buffer' is not assignable to type 'string'.`, but it clearly should resolve with a string in this case.

Downgrading to v0.16.2 helped, so I suspect the problem is somewhere in this patch: https://github.com/ranisalt/node-argon2/commit/dcc402f83195d4c58bd807112f93914a79c70a84.

**Comment by ranisalt** [comment]
Maybe @felipeochoa himself can help.

I am currently refactoring to return a `Hash` object that should ease this issue and verifying.

**Comment by xibre** [comment]
@ranisalt @felipeochoa Thanks a lot!
