### ISSUE TITLE
Incompatible with node 4.x

### ISSUE THREAD

**Issue by simonepri** [ranisalt/node-argon2#124]
The readme says that this package is compatible with node >= 4 but actually is compatible only with node >= 6.
Since it's quite easy to support also node 4, @ranisalt would you consider a PR to add back the support for it?

**Comment by ranisalt** [comment]
The README is outdated. Node 4 is on maintenance support (until 4/30) and people should be pushed to move to 6 or, preferably, 8 as soon as possible.

I do not intend to support deprecated Node versions unless there's a good reason to.

**Comment by simonepri** [comment]
In general I agree with you about not supporting deprecated versions of node.
But this package seems to be the only Argon2 bindings available  and keeping a good support also for older node versions it may be reasonable.

**Comment by ranisalt** [comment]
Sure, I would, but also add to the README that deprecated Node versions are supported on a best effort basis.

**Comment by simonepri** [comment]
Actually I didn't have the time so far. Sorry.

My aim is still to support node 4.
I'm working to unify all the password hashing algorithms to make them adhere to the PHC standard while using the same API interface for every one.

My idea for the `node-argon2` repo is to provide raw only binding to the inner c++ implementation of the kdf function and then having another package that uses the kdf to compute the hash and to encode the hash string using some particular standard (PHC).

Actually I've already done that for some algorithms:
https://github.com/simonepri/phc-argon2
https://github.com/simonepri/phc-scrypt
https://github.com/simonepri/phc-pbkdf2

In particular [this](https://github.com/simonepri/phc-argon2/blob/master/index.js) is the `argon2` one that uses `node-argon2` raw hash methods and then take care of encoding the string.

I don't know if my aim fits well with your idea for this project but I thought was interesting discussing about it.

**Comment by ranisalt** [comment]
Node 4 has officialy EOL'd so don't expect support now if we need boilerplate code to support it.
