### ISSUE TITLE
0.18 Won't build on Windows

### ISSUE THREAD

**Issue by pocesar** [ranisalt/node-argon2#128]
### Steps to reproduce
1. Have Windows 10 with windows-build-tools installed
2. Add argon2 to package.json
3. Fail

Note: 0.17 works

```
..\src\argon2_node.cpp(176): error C2872: 'CONTEXT': ambiguous symbol [g:\www\node_modules\argon2\build\argon2.vcxproj]
  F:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(3680): note: could be '_CONTEXT CONTEXT' (compiling source file ..\src\argon2_node.cpp)
  ..\src\argon2_node.cpp(28): note: or       '`anonymous-namespace'::OBJECTS CONTEXT'
..\src\argon2_node.cpp(176): error C2275: 'CONTEXT': illegal use of this type as an expression [g:\www\node_modules\argon2\build\argon2.vcxproj]
  F:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(3680): note: see declaration of 'CONTEXT'
```

### Expected behaviour
Installs

### Actual behaviour
Craps out with ambiguous symbol error

### Environment
**Operating system**:
Windows 10 x64

**Node version:**
9.11.1

**Compiler version:**
MSBuild 14.0 (vstudio 2015)

**Comment by MaximS** [comment]
Windows 7 x64 SP 1 as well, same error. 0.17 - OK.

**Comment by ranisalt** [comment]
0.19 should fix it

**Comment by TRAHOMOTO** [comment]
argon2 v.0.19 on Windows **10 x64**, node **v8.9.0**, **windows-build-tools** installed, MSBuild 14.0 (vstudio 2015) ---- compiled without issues but there is another issue

`at Promise.then.expected (... bla-bla-bla ...\node_modules\argon2\argon2.js:114:32)` 

```javascript
const verify = (digest, plain) => {
  const {
    id: type, version, params: {
      m: memoryCost, t: timeCost, p: parallelism
    }, salt, hash
  } = phc.deserialize(digest)
  return new Promise((resolve, reject) => {
    const options = {
      type: module.exports[type],
      version: +version,
      hashLength: hash.length,
      memoryCost: +memoryCost,
      timeCost: +timeCost,
      parallelism: +parallelism,
      salt
    }
    bindings.hash(Buffer.from(plain), options, (err, value) => {
      /* istanbul ignore if */
      if (err) {
        return reject(err)
      }
      return resolve(value)
    })
  }).then(expected => expected.equals(hash))
}
```

**Comment by ranisalt** [comment]
Can you try 0.19.1? Windows compilers have been a pain recently...

**Comment by davidspiess** [comment]
Now i get 
```
TypeError: Cannot read property 'hash' of undefined
    at bindings.hash (...\node_modules\argon2\argon2.js:106:28)
```

**Comment by ranisalt** [comment]
What happens when you `require('bindings')('argon2')` at the root of the repo? Specifically, it should be an object like this:

![image](https://user-images.githubusercontent.com/1993083/39960165-55e864a6-560d-11e8-8f51-9404fd1661a1.png)

**Comment by delaneyb** [comment]
@ranisalt 
![32458546_2056374807710156_4949779169589329920_n](https://user-images.githubusercontent.com/18545667/39997151-3e3bef58-57c5-11e8-85a6-f3b497f7fa62.png)
![image](https://user-images.githubusercontent.com/18545667/39997172-4ffedf5c-57c5-11e8-9109-8fba9ee75e0d.png)

**Comment by ranisalt** [comment]
Moving discussion to #134
