### ISSUE TITLE
not usable under archlinux because of bcrypt@1.0.3

### ISSUE THREAD

**Issue by boistordu** [ranisalt/node-argon2#129]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [x] Checkout to the latest version, **including submodules**
- [x] Try to find an *isolated* way to reproduce the behavior
- [x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1.just try to install it you'll see

I just can't see why you would stay @1.03 which clearly is a security problem for a cryptology lib which is sustained by other repos itself. If it would be a standalone then why not but it's not!

### Actual behaviour
Tell us what happens instead
bcrypt@1.0.3 can't be installed it's end of life cycle which is logic since it's bcrypt@2 now

```
make: *** [bcrypt_lib.target.mk:97: Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
make: Leaving directory '/srv/seedbox/flood/node_modules/bcrypt/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Linux 4.16.5-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/srv/seedbox/flood/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/srv/seedbox/flood/node_modules/bcrypt/lib/binding"
gyp ERR! cwd /srv/seedbox/flood/node_modules/bcrypt
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/srv/seedbox/flood/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/srv/seedbox/flood/node_modules/bcrypt/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/srv/seedbox/flood/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:947:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:236:5)
node-pre-gyp ERR! System Linux 4.16.5-1-ARCH
node-pre-gyp ERR! command "/usr/bin/node" "/srv/seedbox/flood/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /srv/seedbox/flood/node_modules/bcrypt
node-pre-gyp ERR! node -v v10.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/srv/seedbox/flood/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/srv/seedbox/flood/node_modules/bcrypt/lib/binding' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@1.0.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@1.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

### Environment
**Operating system**:
archlinux System Linux 4.16.5-1-ARCH
**Node version:**
 node -v v10.0.0
**Compiler version:**
 node-pre-gyp -v v0.6.36
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 7.3.1 20180406 (GCC)

**Comment by boistordu** [comment]
There is way too much problems with bcrypt 1.0.3... Problem of permissions, of location. It doesn't go where you are but always in /usr/lib/node_modules which creates always problems in permission -> several threads about that like this [one](https://github.com/kelektiv/node.bcrypt.js/issues/582)

I really don't understand why you didn't switch immediately to 2.0 since it just make the problems goes away  and it's more secure (simple facts because hashing password are not compatible between 1.0.3 and 2.0)

**Comment by boistordu** [comment]
and I'm suspecting that it is very much the same problem I have under FreeBSD.... All of that just because one bad components.

**Comment by ranisalt** [comment]
This library does not relate to or require bcrypt, but I will check deep in the dependency tree if something does.

**Comment by boistordu** [comment]
I'm going to try to reinstall it today ... wlel right now actually and see what happens

**Comment by boistordu** [comment]
well it seems you were right, so something else was tempering with my install
thanks anyway and sorry to have you disturbed for nothing
