### ISSUE TITLE
TypeError: opts must be an object

### ISSUE THREAD

**Issue by ilouHD** [ranisalt/node-argon2#134]
### Steps to reproduce
1. run test/test.js _or_
2. execute `argon2.hash("password")`

EDIT: using node-argon2 0.19.2 and 0.19.1 the hashing doesn't work, but on 0.19.0 it does, but the verifying doesn't work there.

### Expected behaviour
1) tests are supposed to pass _or_ 2) argon2 is supposed to hash my password

### Actual behaviour
instead of passing tests or even hashing the password argon2 prints out a TypeError:
```
TypeError: opts must be an object
    at Object.serialize (node_modules\@phc\format\index.js:55:11)
    at Promise.then.then.output (node_modules\argon2\argon2.js:70:16)
    at <anonymous>
```
after debugging the code the problem occurrs by calling bindings.hash() at https://github.com/ranisalt/node-argon2/blob/master/argon2.js#L57 because of undefined err and value

### Environment
**Operating system**: Windows 10 Pro 64bit (Version 10.0.17134 Build 17134)

**Node version:** Node.js v8.11.1

**Compiler version:**
windows-build-tools@2.3.0
Microsoft Visual C++ 2017 (v. 14.14.26405.0)
Microsoft Visual C++ Build Tools (v. 14.0.25420.1)

**Comment by ranisalt** [comment]
Can you post the output of `npm ls`?

**Comment by mannatera** [comment]
I have exactly the same problem under Windows with Argon2 0.19.2 (works fine in Ubuntu 14). Here's my output of npm ls under Windows: https://pastebin.com/raw/CM0Qw9nt

**Comment by ranisalt** [comment]
Does the same happen in an isolated environment, i.e. you create a new folder and *only* install argon2?

**Comment by mannatera** [comment]
Yes, the same thing happens. Created new folder, ran yarn init, yarn add argon2, created app.js with content:
`var argon2 = require('argon2');
argon2.hash('password123').then(hash => {
    console.log(hash)
})`

Output after running node app.js : 
(node:12484) UnhandledPromiseRejectionWarning: TypeError: opts must be an object
    at Object.serialize (C:\www\argon\node_modules\@phc\format\index.js:55:11)
    at Promise.then.then.output (C:\www\argon\node_modules\argon2\argon2.js:70:16)
    at <anonymous>
(node:12484) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12484) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by pedrohills** [comment]
Same problem here...

**Comment by ranisalt** [comment]
@mannatera care to make a PR?

**Comment by mannatera** [comment]
Will do

**Comment by mannatera** [comment]
Done #138
