### ISSUE TITLE
Run verify command synchronously

### ISSUE THREAD

**Issue by babbott1000** [ranisalt/node-argon2#136]
It says in the readme that this module is capable of running synchronously.  I apologize if this is a stupid question but I don't see any way to run it except in an asynchronous task.

**Comment by babbott1000** [comment]
My goal is to have a function that tests a hash with 4 different passwords and then returns the password, but I can not do that with a standard function because it rushes to the end and returns undefined.  Would there be any other way to run it async then?

**Comment by ranisalt** [comment]
You can use [`Promise.all`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) to verify them at once, then gather results:

```
Promise.all([
  argon2.verify(...),
  argon2.verify(...),
  argon2.verify(...),
  argon2.verify(...),
]).then(values => {
  return /* if any from `values` is true */
})```

Or you can `await` them, if using Node > 8:

```async function test() {
  await argon2.verify(...)
  await argon2.verify(...)
  await argon2.verify(...)
  await argon2.verify(...)
}```

Either way you do need some form of asynchrony.

**Comment by babbott1000** [comment]
If I run 

```
async function test() {
  const values = [
    await argon2.verify(...),
    await argon2.verify(...),
    await argon2.verify(...),
    await argon2.verify(...),
  ]
  return values.some(v => v)
}

```

 I get `Promise { <pending> }`

**Comment by ranisalt** [comment]
You have to `await test()` (not available on console) as `async function` returns a Promise, or use `then` like this:

```js
test().then(ret => {
  /* here, `ret` contains the value from `return values.some(v => v)` */
})
```

If you are learning JS, please have a look at [MDN on Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises) first.

**Comment by babbott1000** [comment]
I have done js for a while but I have never dont async functions and couldn't find a whole lot of docuumentation on it.  Thanks for your help!

**Comment by ranisalt** [comment]
Sure, feel free to ask :) will close the issue now.

**Comment by babbott1000** [comment]
What I ended up doing is using
```
async function test() {
  const values = [
    await argon2.verify(...),
    await argon2.verify(...),
    await argon2.verify(...),
    await argon2.verify(...),
  ]
  return values.some(v => v)
}
```
but instead of `return values.some(v => v)` I used

```
  for (var i = values.length - 1; i >= 0; i--) {
    if (values[i]) {
      return values[i];
    }
  }
```

**Comment by ranisalt** [comment]
Sure, that's how `some` works internally :P you could also use for...in or for...of
