### ISSUE TITLE
ck

### ISSUE THREAD

**Issue by tasya-TL** [ranisalt/node-argon2#139]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [ ] Checkout to the latest version, **including submodules**
- [ ] Try to find an *isolated* way to reproduce the behavior
- [ ] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
**Operating system**:

**Node version:**

**Compiler version:**

**Comment by ranisalt** [comment]
?
