### ISSUE TITLE
Failed at the argon2@0.19.3 install script 'node-gyp rebuild'

### ISSUE THREAD

**Issue by t0maz** [ranisalt/node-argon2#147]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [x] Checkout to the latest version, **including submodules**
- [x] Try to find an *isolated* way to reproduce the behavior
- [x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. git clone https://github.com/jfurrow/flood.git
2. cd flood
3. npm install --production

### Expected behaviour
no error

### Actual behaviour
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none was installed.
npm WARN flood@1.0.0 No repository field.
npm WARN flood@1.0.0 No license field.
npm ERR! Linux 4.4.0-128-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--production"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! argon2@0.19.3 install: `node-gyp rebuild`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the argon2@0.19.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the argon2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs argon2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls argon2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/data/Pliki/samba_share/Download/rtorrent/flood/npm-debug.log
rtorrent@owczarek /mnt/data/Pliki/samba_share/Download/rtorrent/flood $ npm owner ls argon2
ranisalt <ranisalt@gmail.com>
rtorrent@owczarek /mnt/data/Pliki/samba_share/Download/rtorrent/flood $ ls -lah /mnt/data/Pliki/samba_share/Download/rtorrent/flood/npm-debug.log
ls: cannot access '/mnt/data/Pliki/samba_share/Download/rtorrent/flood/npm-debug.log': No such file or directory
```

### Environment
**Operating system**:
RELEASE=18
CODENAME=sarah
EDITION="Xfce 64-bit"
DESCRIPTION="Linux Mint 18 Sarah"
DESKTOP=Xfce
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_sarah_xfce_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_sarah_xfce.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 18 Xfce 64-bit

**Node version:**
v4.2.6

**Compiler version:**
which one?

**Comment by ranisalt** [comment]
Your version of Node is very outdated. We only support active versions of Node (currently v8 and v10), and try to support maintenance versions (currently v6) on a best effort.

You should either:
- update to v8 or v10 to use the latest version of argon2
- try argon2@0.16.2, the last version to support Node v4 (note it is outdated!)

**Comment by t0maz** [comment]
Many thanks for quick feedback and help.

Yes it was node which is coming by default with Ubuntu 16 / Mint 18
So I've updated it to V10 and here is the current output:

rtorrent@owczarek /mnt/data/Pliki/samba_share/Download/rtorrent/flood $ npm install --production

> argon2@0.19.1 install /mnt/data/Pliki/samba_share/Download/rtorrent/flood/node_modules/argon2
> node-gyp rebuild

make: Entering directory '/mnt/data/Pliki/samba_share/Download/rtorrent/flood/node_modules/argon2/build'
  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  AR(target) Release/obj.target/argon2.a
  COPY Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
make: g++: Command not found
argon2.target.mk:112: recipe for target 'Release/obj.target/argon2/src/argon2_node.o' failed
make: *** [Release/obj.target/argon2/src/argon2_node.o] Error 127
make: Leaving directory '/mnt/data/Pliki/samba_share/Download/rtorrent/flood/node_modules/argon2/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.4.0-128-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /mnt/data/Pliki/samba_share/Download/rtorrent/flood/node_modules/argon2
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN flood@1.0.0 No repository field.
npm WARN flood@1.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.19.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the argon2@0.19.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rtorrent/.npm/_logs/2018-10-13T19_33_52_882Z-debug.log

**Comment by t0maz** [comment]
Oh, I see g++ is missing. I've added it and will let you know how it went.

**Comment by t0maz** [comment]
Yes, it's solved by upgrading node and installing g++
Many thanks for help
