### ISSUE TITLE
Cannot install argon2 on windows 10

### ISSUE THREAD

**Issue by vimutti77** [ranisalt/node-argon2#153]
### Steps to reproduce
1. yarn add argon2

### Expected behaviour
The package is installed correctly,

### Actual behaviour
The build of argon2 v0.20.0 binary fails with following errors:
````$ if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.14.1 | win32 | x64
gyp http GET https://nodejs.org/download/release/v10.14.1/node-v10.14.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.14.1/node-v10.14.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.14.1/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v10.14.1/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v10.14.1/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v10.14.1/win-x86/node.lib
gyp http 200 https://nodejs.org/download/release/v10.14.1/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v10.14.1/SHASUMS256.txt
gyp info spawn C:\Users\xxx\.windows-build-tools\python27\python.EXE
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\Users\\xxx\\node_modules\\argon2\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\xxx\\.node-gyp\\10.14.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\xxx\\.node-gyp\\10.14.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\xxx\\.node-gyp\\10.14.1\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\Users\\xxx\\node_modules\\argon2',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\Users\\xxx\\node_modules\\argon2\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: Dependency 'binding.gyp:require(node-addon-api).gyp#target' not found while trying to load target binding.gyp:argon2#target
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Users\xxx\node_modules\argon2
gyp ERR! node -v v10.14.1
gyp ERR! node-gyp -v v3.8.0
````

### Environment
**Operating system**: windows 10 v1809

**Node version:**: 10.14.1

**Compiler version:**: lastest windows-build-tools. using powershell on vscode v1.29.1

**Comment by ranisalt** [comment]
I see the same issue is happening with AppVeyor builds. Looking to fix it.

**Comment by mfechner** [comment]
Same problem here on a windows 10 machine with node v10.11.0 installed.
Try to install argon `^0.20.0`

**Comment by Captainfive** [comment]
Hi,

Same problem on Windows 10. Version 0.19.3 work well ! 

Best Regards,
Irvin

**Comment by mfechner** [comment]
@Captainfive thanks for this tip, downgraded now to 0.19.3 and it works again.

**Comment by jdforsythe** [comment]
Just added info - it works fine on node v8. Fails on node v10.

**Comment by weagle08** [comment]
I'm pretty sure this is being caused by the submodule [phc-winner-argon2](https://github.com/P-H-C/phc-winner-argon2.git) not loading. If I clone and manually place that submodule in the argon2 directory it builds fine on windows 10.

**Comment by weagle08** [comment]
I also had to modify the binding.gyp line 57:
```
"dependencies": ["<!(node -p 'require(\"node-addon-api\").gyp')", "libargon2"]
```
to
```
"dependencies": ["libargon2"]
```
it builds but does not create the bindings output directory.

so issue with the ('node-addon-api').gyp export not being see as well as the submodule not being pulled.

**Comment by weagle08** [comment]
can anyone help with the submodule issue?

**Comment by ranisalt** [comment]
You need to clone with `git clone --recursive`, but it shouldn't be an issue when installing from npm/yarn as the files are already included.

> not exactly sure what the ('node-addon-api').gyp is doing.

It provides interfacing with Node internals, as this module needs, to provide JS bindings.

**Comment by Zaseth** [comment]
Having the same problem on node v11.8.0. I can't install the latest version of argon2, but I can install version 0.19.3.

**Comment by Zaseth** [comment]
I was able to fix this myself.

- Download this repo
- Download https://github.com/P-H-C/phc-winner-argon2
- Apply https://github.com/ranisalt/node-argon2/issues/153#issuecomment-457438557
- Extract this repo and put /src and /include from PHC Argon2 into this repo's /argon2 folder
- npm install

**Comment by ranisalt** [comment]
v0.20.1 is live.

**Comment by Zaseth** [comment]
Build went successful for me 🎉

**Comment by weagle08** [comment]
thanks guys!

**Comment by gregbown** [comment]
Also would not build if version of python was > 2.7.  I had version 3.7.2 and had to remove the environmental path to it leaving only the path to 2.7

**Comment by ranisalt** [comment]
> Also would not build if version of python was > 2.7. I had version 3.7.2 and had to remove the environmental path to it leaving only the path to 2.7

This is an issue with `node-gyp`, to be more precise, an issue with `gyp` requiring Python 2.7. I intend to move to cmake-js in the near future and kill this issue.

**Comment by DigiGroundJohn** [comment]
I am also getting the same error, it is working perfectly on windows operating system, but when I am trying to move on " Amazon Linux AMI". It's giving the following error.  

python version is 2.7.16
and node v 13.0.1



> argon2@0.19.3 install /node_modules/argon2
> node-gyp rebuild

make: Entering directory `/node_modules/argon2/build'
  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
make: cc: Command not found
make: *** [Release/obj.target/libargon2/argon2/src/opt.o] Error 127
make: Leaving directory `/node_modules/argon2/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/ec2-user/.nvm/versions/node/v13.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.14.138-89.102.amzn1.x86_64
gyp ERR! command "/home/ec2-user/.nvm/versions/node/v13.0.1/bin/node" "/home/ec2-user/.nvm/versions/node/v13.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/argon2
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN burrun-dailai-rest-api@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.19.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.19.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ec2-user/.npm/_logs/2019-11-05T01_03_05_463Z-debug.log

**Comment by Banou26** [comment]
@DigiGroundJohn `sudo apt-get install build-essential` and you're good to go

**Comment by yevheni** [comment]
> @DigiGroundJohn `sudo apt-get install build-essential` and you're good to go

Most helpful reply, thanks
