### ISSUE TITLE
Use GN instead of GYP

### ISSUE THREAD

**Issue by zuohuadong** [ranisalt/node-argon2#155]
### Before creating an issue, please be sure to:
- [x] Checkout to the latest version, **including submodules**
- [x] Try to find an *isolated* way to reproduce the behavior
- [x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
gyp error like: #153 

What is GN?
GN is a meta-build system that generates NinjaBuild files. It's meant to be faster and simpler than GYP. It outputs only Ninja build files.

Why bother with GN?
We believe GN files are more readable and more maintainable than GYP files.
GN is fast:
GN is 20x faster than GYP (as of mid November, building 80% of what GYP builds, in one configuration rather than two, takes 500ms on a z620 running Ubuntu Trusty. GYP takes 20 seconds. We see similar speedups on Mac and Windows).
GN supports automatically re-running itself as needed by Ninja as part of the build. This eliminates the need to remember to re-run GN when you change a build file.
GN gives us better tools for enforcing dependencies (see gn check and the visibility, public_deps, and data_deps options for some examples).
GN gives us tools for querying the build graph; you can ask “what does X depend on” and “who depends on Y”, for example.

### Expected behaviour
please use GN

like：https://v8.dev/docs/build-gn

### Actual behaviour
Tell us what happens instead

### Environment
**Operating system**: linux/windows

**Node version:** 10.11.0

**Compiler version:** xx

**Comment by ranisalt** [comment]
Switching from the native node-gyp to GN would require to write a lot of boilerplate, npm scripts and extra code. Do you have any other module using it we can base on?
