### ISSUE TITLE
support for node 0.10?

### ISSUE THREAD

**Issue by jonathanong** [ranisalt/node-argon2#17]
wanna try putting this into an AWS Lambda when i have time. just wondering if you'd consider supporting node v0.10. totally okay if you don't - i don't support 0.10 in any of my modules. i don't know how much work it requires.

**Comment by ranisalt** [comment]
Hasn't 0.10 already passed it's end of life? I'm going to check if it's possible to build on 0.10.

**Comment by jonathanong** [comment]
yeah... the fact that AWS lambda only supports 0.10 sucks. what to do?

np if u don't want to though. i think wrapping the executable would be easier anyways

**Comment by ranisalt** [comment]
Can't you use [nvm](https://github.com/creationix/nvm)?

It lets you install all versions, and that's what Travis uses to, despite using Ubuntu 14.04 which only has extremely archaic software, support recent versions of Node.

**Comment by jonathanong** [comment]
no, the 0.10 requirement is only for AWS lambda. i'm not sure if they even support using nvm in lambda... will have to look into that. never thought about including the node binaries in the lambda package.

**Comment by ranisalt** [comment]
The problem is major syntax changes are needed to support node < 1 since I heavily use ES6 and C++11 syntax, and those are only available on iojs/node >= 1

**Comment by jonathanong** [comment]
feel free to close this issue if you're not interested!

**Comment by ranisalt** [comment]
Maybe you can use [tj/n](https://github.com/tj/n) to install a newer node version from an older NPM, such as Lambda's. I'd give a try, and if it does not work, I'll open an issue requesting them to upgrade at least to 4.2 (latest LTS).
