### ISSUE TITLE
'make' fails during 'npm install' in project

### ISSUE THREAD

**Issue by janriemer** [ranisalt/node-argon2#18]
Hey, I would like to contribute to your project.
Unfortunately, I get an error when executing `npm install` within the node-argon2 repository.

Being curious, I tried to install your argon2 package into some other project (`npm install argon2`) and that works fine.
It seems that some target in the Makefile can't be resolved correctly (see log beneath).
Do you have any idea to fix this?

Thanks for your effort. :rose: 

Some specs about my system:
- Linux Kubuntu 14.04 LTS
- node@4.3.0
- npm@2.14.18
- node-gyp@3.2.1
- make@3.81

Here is the output produced by `npm install`:
argon2@0.8.0 install /home/jan/Github/node-argon2
\> node-gyp rebuild

make: Entering directory »/home/jan/Github/node-argon2/build«
make: *** No rule to make target »Release/obj.target/libargon2/argon2/src/argon2.o«, 
  needed by »Release/obj.target/argon2.a«.  End.
make: Leaving directory »/home/jan/Github/node-argon2/build«
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/jan/npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-77-generic
gyp ERR! command "/usr/bin/nodejs" "/home/jan/npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/jan/Github/node-argon2
gyp ERR! node -v v4.3.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 

npm ERR! Linux 3.13.0-77-generic
npm ERR! argv "/usr/bin/nodejs" "/home/jan/npm-global/bin/npm" "install"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.18
npm ERR! code ELIFECYCLE
npm ERR! argon2@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1

**Comment by ranisalt** [comment]
That's because you didn't clone the submodule argon2. Try running `git submodule update --init` before building.

It does not happen with npm because the submodule is packed together.

**Comment by ranisalt** [comment]
As a suggestion, if you want something to fix or improve, check [codacy issues](https://www.codacy.com/app/ranisalt/node-argon2/issues). Thanks for trying to help :)

**Comment by janriemer** [comment]
@ranisalt Thanks for the tip with `git submodule`! It works like a charm! :kissing_heart:

**Comment by maurocasas** [comment]
Hey there, I'm getting the same issue on Debian, and I've been doing this all day and cannot get it to work.

My log says MAKE fails at with Exit Code 2

I have
node 4.3
npm 2.14
python 2.7
node-gyp 3.3

**Comment by ranisalt** [comment]
Could you please paste the entire output?
