### ISSUE TITLE
[low] the test 'with hash length' is broken

### ISSUE THREAD

**Issue by leeor** [ranisalt/node-argon2#181]
https://github.com/ranisalt/node-argon2/blob/872fa0cb51bc0af03862a783302049ccbfd67abf/test/test.js#L104-L111

Not a major issue, but the test assumes that the call to `hash` will throw an exception. However, since it's provided with valid options and input and the assertion is never executed.

**Comment by ranisalt** [comment]
You made me notice that every test with a try/catch statement was flawed, not failing on error. Thanks!
