### ISSUE TITLE
node-gyp-build fails on Android Oreo with Termux and clang installed

### ISSUE THREAD

**Issue by earthnoob** [ranisalt/node-argon2#182]
I was trying to install node-argon2 on my Nexus 9 running android Oreo, with Termux as development envrionment. Everything went well until npm triggered node-gyp to build/rebuild the addon.

### Steps to reproduce
1. Install Termux on the Google Play store
2. Run Termux, run `apt update` and install nodejs (this would include npm), python2, make, clang
3. Install node-gyp globally according to instructions: `npm i -g node-gyp`
3. Create a NodeJS project and install node-argon2 as dependency: `CXX=clang++ npm i argon2`

### Expected behaviour
node-gyp finishes building and npm wraps everything up successfully.

### Actual behaviour
node-gyp fails to some degree, on my nexus 9 it would be:
`argon2@0.23.0 install /data/data/com.termux/files/home/repos/node_js_nordiccoder/node_modules/argon2
node-gyp-build

make: Entering directory '/data/data/com.termux/files/home/repos/node_js_nordiccoder/node_modules/argon2/build'
  CC(target) Release/obj.target/libargon2/argon2/src/ref.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  AR(target) Release/obj.target/argon2.a
  COPY Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
  SOLINK_MODULE(target) Release/obj.target/argon2.node
clang-8: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: Release/obj.target/argon2/src/argon2_node.o: relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol '_ZTISt12length_error' which may bind externally can not be used when making a shared object; recompile with -fPIC
Release/obj.target/argon2/src/argon2_node.o: in function 'std::__ndk1::__throw_length_error(char const*)':
argon2_node.cpp:(.text._ZNSt6__ndk120__throw_length_errorEPKc[_ZNSt6__ndk120__throw_length_errorEPKc]+0x2c): dangerous relocation: unsupported relocation
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [argon2.target.mk:141: Release/obj.target/argon2.node] Error 1
make: Leaving directory '/data/data/com.termux/files/home/repos/node_js_nordiccoder/node_modules/argon2/build'
gyp ERR! build error
gyp ERR! stack Error: 'make' failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
gyp ERR! System Linux 3.10.103-ElementalX-N9-7.06
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/home/repos/node_js_nordiccoder/node_modules/argon2
gyp ERR! node -v v12.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN eslint-config-airbnb@17.1.0 requires a peer of eslint-plugin-jsx-a11y@^6.1.1 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@17.1.0 requires a peer of eslint-plugin-react@^7.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN NordicNode@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.23.0 install: 'node-gyp-build'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.23.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2019-05-22T04_17_24_663Z-debug.log`

### Environment
**Operating system**: Android Oreo 8.1.0

**Node version:**: 12.2.0

**Compiler version:**
clang version 8.0.0 (tags/RELEASE_800/final)
Target: aarch64-unknown-linux-android
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin

**NPM version**: v6.9.0
**python2 version**: v2.7.16

**Comment by ranisalt** [comment]
The issue seems to be upstream, on [node-gyp-build](https://github.com/prebuild/node-gyp-build). Please report there and let me know.
