### ISSUE TITLE
Mac build not working.

### ISSUE THREAD

**Issue by allroundexperts** [ranisalt/node-argon2#185]
Mac OSX
Node v12.3
Following is the output of npm install --save argon2:
make: *** No rule to make target `../../../../../../../../../usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi', needed by `Makefile'.  
Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/Cellar/node/12.3.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /dashlane-js/node_modules/argon2
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.23.0 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the argon2@0.23.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/allroundexperts/.npm/_logs/2019-06-08T12_11_15_705Z-debug.log

**Comment by ranisalt** [comment]
Can you try 0.24.0?

**Comment by allroundexperts** [comment]
Doesn't work!

**Comment by wooolfgang** [comment]
@allroundexperts Were you able to resolve the issue? Doesn't work on 
OSX Mojave 10.14.16
Node v12.10.0

```
node-gyp-build

  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  LIBTOOL-STATIC Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
make: g++-6: No such file or directory
make: *** [Release/obj.target/argon2/src/argon2_node.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/liarolfrey/Gitprojects/the-gig-atlas/server/node_modules/argon2
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
```

**Comment by Tino-F** [comment]
@wooolfgang I got mine working by updating my macbook and updating to the latest version of gcc. Also didn't see the section for installation on Mac: https://github.com/ranisalt/node-argon2/blob/master/README.md#osx

**Comment by wooolfgang** [comment]
Just got it working for me as well, I used CXX=g++ instead of CXX=g++-6  🤷‍♂. Thanks!

**Comment by ranisalt** [comment]
> Just got it working for me as well, I used CXX=g++ instead of CXX=g++-6 . Thanks!

If you can reproduce on other OSX machines and that works for all of them, consider making a PR :+1:
