### ISSUE TITLE
Feature Request - Downgrade Safety

### ISSUE THREAD

**Issue by egs2003** [ranisalt/node-argon2#186]
Doorbird uses Argon2i for PAssword Hashing. But they use their algorithm with 8k memory instead of 8192. Your Library does not support such low memory cost. Could you implement it for me?

**Comment by ranisalt** [comment]
Sure, that's it. I can't publish to NPM right now though, you can try using the commit or wait some days if it's not urgent.

**Comment by ranisalt** [comment]
Done, check v0.24.0
