### ISSUE TITLE
Not working on Ubuntu

### ISSUE THREAD

**Issue by allroundexperts** [ranisalt/node-argon2#187]
Error: No native build was found for platform=linux arch=x64 runtime=node abi=64 uv=1 libc=glibc
  
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR!  start:node: `webpack && node dist/dashlane.node.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the start:node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by ranisalt** [comment]
This does not look like an issue from that package. What are you trying to run?

**Comment by TheInfernoX** [comment]
Getting the same error here when installing the package. (Node.js v12.2.0 / npm 6.9.0 / Windows 10 1903)

**Comment by TheInfernoX** [comment]
This particular log line seems interesting:

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable

**Comment by TheInfernoX** [comment]
After doing some more thorough research, it looks like `node-gyp` requires python 2.7 to be installed. Can this dependency on requiring an external installation of python and setting its environment variables be removed in Windows ?

**Comment by TheInfernoX** [comment]
After doing some more thorough research, it looks like node-gyp requires python 2.7 to be installed. Can this dependency on requiring an external installation of python and setting its environment variables be removed in Windows?

**Comment by allroundexperts** [comment]
There's something wrong with this package. Doesn't work on Mac too.

**Comment by ranisalt** [comment]
> After doing some more thorough research, it looks like node-gyp requires python 2.7 to be installed. Can this dependency on requiring an external installation of python and setting its environment variables be removed in Windows?

I don't think so, since the change is on a dependency, and node-gyp depends on the very unmaintained gyp package, and node mandates node-gyp, so it probably will never be fixed.

If you want, you can continue on #155 which proposed moving build system, but nobody stepped over to fix that.

**Comment by fellowseb** [comment]
Hi!
FYI, I had the same issue as OP, and using #202 seems to work better.
Thanks, keep up the good work!
