### ISSUE TITLE
Travis fails to build argon2 in my project

### ISSUE THREAD

**Issue by julien-f** [ranisalt/node-argon2#20]
I get the error `cc1plus: error: unrecognized command line option ‘-Wpedantic’`, I am surely missing something but I could not figure what.

[Here](https://travis-ci.org/julien-f/nodejs-hashy/jobs/107724542) is the build, note that because it is an optional dependency, the error is hidden and you have to expand the `npm install` line.

**Comment by cgmb** [comment]
It seems that `-Wpedantic` was added in GCC 4.8. The version of GCC that comes with Ubuntu 12.04 is older than that, I guess.

**Comment by julien-f** [comment]
Hmm, ok, so I guess I better use the Trusty distro then…

**Comment by ranisalt** [comment]
You need at least GCC 4.8 since C++11 support is needed and is only fully available since that version.
