### ISSUE TITLE
Advertising package

### ISSUE THREAD

**Issue by traverseda** [ranisalt/node-argon2#201]
It looks like this project depends on https://github.com/feross/funding, a project intended to show advertising in a projects build log.

I'm not familiar with your project, I'm just looking through a list of projects that depend on `feross/funding`. It's my understanding that right now there aren't any advertising messages actually showing, but if you're uncomfortable with the possibility of advertisements in build logs that's something you might want to look into.

**Comment by ranisalt** [comment]
That comes from github.com/feross/standard, a dev dep from the same author.

While I appreciate funding (I even added Github Sponsor support a while back), I don't like the predatory way standard is doing it, as open source contribution should not be tied with pesky ads, after all it's contribution and not subscription.

I might replace it with eslint which in turn allows for more customization.

**Comment by traverseda** [comment]
My understanding is that `standard` is just an easy to install jslint config. You can find that (MIT licensed) config file here: https://github.com/standard/eslint-config-standard

**Comment by ranisalt** [comment]
The funding project has been killed and it should not be an issue anymore.
