### ISSUE TITLE
Usage question for user safety

### ISSUE THREAD

**Issue by JMD49591** [ranisalt/node-argon2#207]
Hi, I'm using your package in my project.
As I tried to understand the generated string I asked myself the question if it would be more safe for my users to just save the generated password hash + salt or the full string. Since the full string has the argon2i hashing method and configuration stuff in it, which could give hackers more clues on decrypting the passwords.
Because of this I split the string apart and save the password hash and generated salt separatly. But is this nessarry? Is it more safe?
A short explanation would be nice, because I don't really understand password security in that point.

**Comment by ranisalt** [comment]
No, it is neither necessary nor safer. The parameters are stored on the resulting hash to provide reproducibility - you can generate the same hash using the same parameters - and are only useful for a genuine user, trying to validate the password, and do not provide additional information for an attacker.

If you store the parameters separately from hashes, you must store it somewhere else in your code, so you're just moving it, not removing it.

**Comment by JMD49591** [comment]
Ok, but why is that so? I mean isn't it already a good hint for the attacker that the passwords were hashed with argon2i?

**Comment by ranisalt** [comment]
Even knowing algorithm and parameters, without the plain password the best an attacker can do is close to brute forcing every possible password. It is virtually impossible to obtain the plain text from the hash that way.

A rough analogy: you might know where you want to go and what is the roads you must take, but you still have the job of driving the car; knowing the parameters of the travel does not help driving it.

**Comment by JMD49591** [comment]
hm ok. I guess that means that for verification of the password your programm rehashes the user input with given parameters and compares if they match with the hash. In that case its all up to brute force for the attacker.

But I guess you can still delay the brute force attack by not giving the hacker the alogrithm and parameters, since not even knowing the roads you must take is even harder for reaching the goal.

**Comment by ranisalt** [comment]
> hm ok. I guess that means that for verification of the password your programm rehashes the user input with given parameters and compares if it matches the hash. In that case its all up to brute force for an attacker.

I see where you're trying to get, but you must store these parameters somewhere, and if your attacker can access your database if probably can access the rest of your code, too. That's why we use one-way hash functions for passwords, if absolutely everything breaks, passwords are still 100% safe. Always assume your attacker is smarter, has more power and time than you.

That said, what if in the future you desire to change parameters? How would you handle updating hashes?

> But I guess you can still delay the brute force attack by not giving the hacker the alogrithm and parameters, since not even knowing the roads you must take is even harder for reaching the goal.

You can, but the order of magnitude of brute forcing is much larger. As in, even if having the parameters means an attacker takes half the time to crack the password, what's the point if it's going to take one or two trillion years?

**Comment by JMD49591** [comment]
good points there
> That said, what if in the future you desire to change parameters? How would you handle updating hashes?
Didn't thought about that yet to be honest. I guess some rehashing function I saw somewhere.

All in all it's enough for answering my question, thank you for your time :)

**Comment by ranisalt** [comment]
No problem, feel free to raise up any questions in the future!
