### ISSUE TITLE
[Electron] Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by perry-mitchell** [ranisalt/node-argon2#216]
### Steps to reproduce
1. Clone [Buttercup Desktop](https://github.com/buttercup/buttercup-desktop) on Windows
2. `npm i`
3. `npm start`

### Expected behaviour
The application should build and start without error.

### Actual behaviour
When trying to start with argon2, the following error appears:

```
Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\username\git\project_name\node_modules\argon2\build\Release\argon2.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at load (C:\Users\username\git\project_name\node_modules\node-gyp-build\index.js:20:10)
    at Object.<anonymous> (C:\Users\username\git\project_name\node_modules\argon2\argon2.js:5:81)
```

I'm not sure where else to look, but I can't, for the life of me, figure out why this is crashing. I'm running Gitbash on windows, I've tried msys, and I've tried checking the project out and running that. Installation works fine from this repo itself, though the tests fail with errors like the following:

```
  33) Argon2
       verify
         verify argon2id correct password:
     TypeError: assert is not a function
      at Context.it (test\test.js:235:7)
      at <anonymous>
```

The project I'm trying to use it in is an electron project, but we're trying to use argon2 purely on the Node side. This all happens during import. Could there be some incompatibility with running under electron altogether?

### Environment
**Operating system**: Windows 10 64bit

**Node version:** 8.11

**Compiler version:** -

**Comment by sallar** [comment]
Electron version: 3.1.11
Electron's node version: 10.2

**Comment by ranisalt** [comment]
> we're trying to use argon2 purely on the Node side. This all happens during import

Do you mean it happens when you isolate node-argon2? I didn't understand it clearly, sorry

**Comment by perry-mitchell** [comment]
No worries! So I can run node-argon2's tests locally if I clone the project.. but if I import `argon2` into the project using npm, it always fails as the application starts up. Does argon2 use any DLLs on windows?

**Comment by ranisalt** [comment]
> Does argon2 use any DLLs on windows?

It should not, it only requires standard libraries and the argon2 library that is bundled.

**Comment by perry-mitchell** [comment]
@ranisalt Is there something we can do here to help debug? This is a blocker for us so we'd be more motivated than usual to provide some assistance 😁

**Comment by ranisalt** [comment]
I don't know, I don't use Windows so I can't really be helpful here.

**Comment by carlos-menezes** [comment]
I'm also having this issue.

**Comment by ranisalt** [comment]
If you may, please try again with the latest version and reopen if issue persists.
