### ISSUE TITLE
Cannot install argon2 on Amazon Linux AMI

### ISSUE THREAD

**Issue by DigiGroundJohn** [ranisalt/node-argon2#222]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [x] Checkout to the latest version, **including submodules**
- [x] Try to find an *isolated* way to reproduce the behavior
- [ ] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. npm i argon2
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
**Operating system**:
Amazon Linux AMI

**Node version:**
13.0.1

**python version:**
 2.7.16 
**Compiler version:**

I am also getting the same error, it is working perfectly on windows operating system, but when I am trying to move on " Amazon Linux AMI". It's giving the following error.

python version is 2.7.16
and node v 13.0.1

argon2@0.19.3 install /node_modules/argon2
node-gyp rebuild

make: Entering directory /node_modules/argon2/build' CC(target) Release/obj.target/libargon2/argon2/src/opt.o make: cc: Command not found make: *** [Release/obj.target/libargon2/argon2/src/opt.o] Error 127 make: Leaving directory /node_modules/argon2/build'
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/home/ec2-user/.nvm/versions/node/v13.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack at ChildProcess.emit (events.js:210:5)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.14.138-89.102.amzn1.x86_64
gyp ERR! command "/home/ec2-user/.nvm/versions/node/v13.0.1/bin/node" "/home/ec2-user/.nvm/versions/node/v13.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /node_modules/argon2
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN burrun-dailai-rest-api@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.19.3 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.19.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/ec2-user/.npm/_logs/2019-11-05T01_03_05_463Z-debug.log

**Comment by ranisalt** [comment]
You must install a C and C++ compiler, as per the README.

**Comment by DigiGroundJohn** [comment]
you saved my life :)
