### ISSUE TITLE
Provide alpine linux compatible prebuilt binaries

### ISSUE THREAD

**Issue by defunctzombie** [ranisalt/node-argon2#223]
I am using the argon2 module in alpine linux (in a container to be more specific). When I try to install the latest version (0.25.1) I get the following error when trying to download the prebuilt package.

```
error /app/node_modules/argon2: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /app/node_modules/argon2
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@12.10.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp info check checked for "/app/node_modules/argon2/lib/binding/argon2.node" (not found)
node-pre-gyp http GET https://github.com/ranisalt/node-argon2/releases/download/v0.25.1/argon2-v0.25.1-node-v72-linux-x64-musl.tar.gz
node-pre-gyp http 404 https://github.com/ranisalt/node-argon2/releases/download/v0.25.1/argon2-v0.25.1-node-v72-linux-x64-musl.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/ranisalt/node-argon2/releases/download/v0.25.1/argon2-v0.25.1-node-v72-linux-x64-musl.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for argon2@0.25.1 and node@12.10.0 (node-v72 ABI, musl) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/ranisalt/node-argon2/releases/download/v0.25.1/argon2-v0.25.1-node-v72-linux-x64-musl.tar.gz
```

It would be great if a musl compatible prebuilt binary would be available so I don't need to fallback to compilation.

**Comment by ranisalt** [comment]
I would accept if you can make a PR.

**Comment by defunctzombie** [comment]
How are you handling the prebuild today? Are you just using travis to iterate the `os` field here (https://github.com/ranisalt/node-argon2/blob/master/.travis.yml#L7) and upload what it produces?

**Comment by ranisalt** [comment]
> How are you handling the prebuild today

It should be handled by the `node-pre-gyp package` command. @hoangvvo might know better.

**Comment by hoangvvo** [comment]
@ranisalt I did not even know that my PR was merged :rofl: It has been such a while.

Would you mind remove the tag `v0.25.1` and then readd it via [releases](https://github.com/ranisalt/node-argon2/releases) to test the new build process? No need to publish a new version to npm.

**Comment by hoangvvo** [comment]
@defunctzombie 
The Linux build is using Ubuntu Xenial so it should be compatible. https://docs.travis-ci.com/user/reference/overview/

I would wait for @ranisalt to do the tag thingy to trigger Travis build again. Then, you can try to do a clean install of `node-argon2` to see.

**Comment by hoangvvo** [comment]
@ranisalt Hey I noticed you published a new release through Github. Is this possible to *remove* both the release and tag and try again. (after deleting the release, you will need to do the same thing one more time with the tag)

You tagged [v0.25.1](https://github.com/ranisalt/node-argon2/releases/tag/v0.25.1) before #215. If you simply release (without retaging, it will reuse that old commit, which explains why the ci was using the old config. https://travis-ci.org/ranisalt/node-argon2/builds/610645824/config

**Comment by ranisalt** [comment]
Just did it. Waiting for result

**Comment by AlexGustafsson** [comment]
Any update on this? 25.1 still isn't available as a prebuilt binary for Alpine.

**Comment by johannesschobel** [comment]
i think this is still an issue. i cannot use it in my `node:alpine` docker image!?

**Comment by ranisalt** [comment]
I don't think Github Actions has support for Alpine, but maybe a custom workflow installing musl on Ubuntu and building there might work.

**Comment by defunctzombie** [comment]
What about building the binary in an alpine container? My understanding of Actions is that you can run arbitrary commands?

**Comment by johannesschobel** [comment]
Yeah, you guys were absolute right.. I think I had some missing packages in my Alpine docker container, resulting in a failing `npm install`
