### ISSUE TITLE
.Net version of node-argon2

### ISSUE THREAD

**Issue by lewiscxa** [ranisalt/node-argon2#229]
Hi guys,
Is there a .Net version which is compatible with node-argon2?

**Comment by ranisalt** [comment]
If you mean a .NET version of the Argon2 hashing library, check [upstream](https://github.com/P-H-C/phc-winner-argon2#bindings). There is a C# version.

**Comment by lewiscxa** [comment]
@ranisalt I mean a lib which also supports PHC encoding like node-argon2. I've just checked and it seems that those .Net libs only supports generating the hash only.

**Comment by ranisalt** [comment]
@lewiscxa it seems the .NET libs still don't support it. If you feel like, it's not a big deal, it's just a matter of concatenating the params and base64-encoding salt and hash, see the code for [`@phc/format`](https://github.com/simonepri/phc-format/blob/master/index.js) which we use.
