### ISSUE TITLE
specifying salt does not appear to work

### ISSUE THREAD

**Issue by CalebCarroll** [ranisalt/node-argon2#231]
### Steps to reproduce
1. var hash = await argon2.hash('password','salt');   // this returns different hash each time therefore salt is ignored
2. var hash = await argon2.hash('password',{salt:'salt'});  //this returns Invalid argument error so, although the documentation shows the parameter salt as an option (see Wiki, just after raw option), it is not being treated as an option.
3.

### Expected behaviour
use salt

### Actual behaviour
crash

### Environment
Linux

**Node version:**
12.13.1

**Compiler version:**
7.3.0

**Comment by ranisalt** [comment]
Why are you trying to use your own salts?

That said, salt must be a Buffer, not a string. Try `Buffer.from('salt')`

**Comment by CalebCarroll** [comment]
Thank you.  I Need to be able to specify my own salt in order to support a legacy application (which I didn't write).  I didn't notice salt was meant to be a buffer data type.
