### ISSUE TITLE
Hash to String

### ISSUE THREAD

**Issue by NG235** [ranisalt/node-argon2#232]
There is currently no way to return to hash as a string, making to database work hard. Can this please be fixed or can someone please help me solve this problem.

Thank you.

**Comment by ranisalt** [comment]
What do you mean? By default, `hash` returns a string that can be stored on database and checked with `verify`.

**Comment by NG235** [comment]
I have a function called `hash` that takes an input parameter. See below for code.

https://gist.github.com/NG235/c2675905a995abc5880798b5568c433b

Thank you.

**Comment by ranisalt** [comment]
You are both not awaiting your async function and not returning anything from it.
