### ISSUE TITLE
Install not working in docker node:12-alpine

### ISSUE THREAD

**Issue by kbjr** [ranisalt/node-argon2#236]
I'm trying to get argon2 to install as a dependency of a project in a `node:12-alpine` docker container, but I'm getting an error pretty much immediately once the build starts. I've reduced down the reproducible steps to just this:

1. This is a new container `FROM node:12-alpine`.
2. Install build dependencies:

```bash
$ apk add --no-cache g++ gcc libgcc libstdc++ linux-headers make python
```

Resulting installed versions:

```
(1/23) Installing binutils (2.33.1-r0)
(2/23) Installing gmp (6.1.2-r1)
(3/23) Installing isl (0.18-r0)
(4/23) Installing libgomp (9.2.0-r3)
(5/23) Installing libatomic (9.2.0-r3)
(6/23) Installing mpfr4 (4.0.2-r1)
(7/23) Installing mpc1 (1.1.0-r1)
(8/23) Installing gcc (9.2.0-r3)
(9/23) Installing musl-dev (1.1.24-r0)
(10/23) Installing libc-dev (0.7.2-r0)
(11/23) Installing g++ (9.2.0-r3)
(12/23) Installing linux-headers (4.19.36-r0)
(13/23) Installing make (4.2.1-r2)
(14/23) Installing libbz2 (1.0.8-r1)
(15/23) Installing expat (2.2.9-r1)
(16/23) Installing libffi (3.2.1-r6)
(17/23) Installing gdbm (1.13-r1)
(18/23) Installing ncurses-terminfo-base (6.1_p20191130-r0)
(19/23) Installing ncurses-terminfo (6.1_p20191130-r0)
(20/23) Installing ncurses-libs (6.1_p20191130-r0)
(21/23) Installing readline (8.0.1-r0)
(22/23) Installing sqlite-libs (3.30.1-r1)
(23/23) Installing python2 (2.7.16-r3)
```

3. Then running npm:

```bash
$ npm install node-gyp -g
$ npm install
```

With just this in `package.json`:

```json
{
  "dependencies": {
    "argon2": "^0.25.1"
  }
}
```

And I get the following error:

```
> argon2@0.25.1 install /usr/viva/auth-service/node_modules/argon2
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/ranisalt/node-argon2/releases/download/v0.25.1/argon2-v0.25.1-node-v72-linux-x64-musl.tar.gz
node-pre-gyp WARN Pre-built binaries not found for argon2@0.25.1 and node@12.14.0 (node-v72 ABI, musl) (falling back to source compile with node-gyp)
make: Entering directory '/usr/viva/auth-service/node_modules/argon2/build'
  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
mkdir: can't create directory './Release/': Directory not empty
make: *** [libargon2.target.mk:123: Release/obj.target/libargon2/argon2/src/opt.o] Error 1
make: Leaving directory '/usr/viva/auth-service/node_modules/argon2/build'
```

The only other possibly interesting fact about the environment, besides what can be determined from the container, is that this is Docker running on WSL on Windows 10. But that _should_ have no impact.

**Comment by ranisalt** [comment]
It seems that your container is dirty and contains previous build files. Try a clean, new container instead.

**Comment by kbjr** [comment]
That seemed likely to me as well, so I deleted the container and started from scratch, but I always get the same result.

**Comment by kbjr** [comment]
Just to be extra sure, I just deleted _all_ of my images and containers from docker, did a fresh pull of `node:12-alpine`, and tried to build, but got the same error.

**Comment by kbjr** [comment]
Okay, so, I finally got around to getting the project I'm working on up in CI, and when it runs there, it works and installs fine. At this point, I'm working under the assumption that there is something wrong with it running in WSL, but from what I can tell, there is nothing specifically wrong with installing `argon2` on `node:12-alpine`

**Comment by ranisalt** [comment]
Well, I'll mark it as solved but tag as Windows issue
