### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by maurocasas** [ranisalt/node-argon2#24]
Hello!

I'm currently trying to install Node-Argon2 in a debian7 server and I have been struggling for a few hours now without any luck.

I'm always getting the same error:

`g++: error: unrecognized command line option ‘-Wpedantic’`

I have install
Node 4.3
Npm 2.14
Python 2.7
Make 3.81

**Comment by ranisalt** [comment]
What version of g++?

You can remove the "-Wpedantic", I'm going to push an update that fixes it.

**Comment by maurocasas** [comment]
-
> argon2@0.8.0 install /usr/lib/node_modules/argon2
> node-gyp rebuild

make: Entering directory `/usr/lib/node_modules/argon2/build'
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
../argon2/src/core.c: In function ‘validate_inputs’:
../argon2/src/core.c:357:9: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
../argon2/src/core.c:387:9: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
../argon2/src/core.c:402:9: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
../argon2/src/core.c:416:5: warning: comparison is always false due to limited range of data type [-Wtype-limits]
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  AR(target) Release/obj.target/argon2.a
  COPY Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
g++: error: unrecognized command line option ‘-Wpedantic’
make: *** [Release/obj.target/argon2/src/argon2_node.o] Error 1
make: Leaving directory `/usr/lib/node_modules/argon2/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/argon2
gyp ERR! node -v v4.3.1
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "argon2"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! argon2@0.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.8.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the argon2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls argon2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any

**Comment by maurocasas** [comment]
Instead of using npm intstall argon2 I cloned the repo, run `git submodule update --init` but now I get the classic "module not found argon2"

i forgot to mention I ran `npm install` inside the node-argon2 folder

**Comment by ranisalt** [comment]
Where do you get this "module not found"? After npm install or where you are requiring argon2?

**Comment by maurocasas** [comment]
When requiring.

Thanks for the update, left me without words you're willingness. I'm not sure what to do though, should I try to re-install? Using manual clone or NPM?

Thanks again

**Comment by ranisalt** [comment]
You can now install 0.9.0 from NPM and it will be fixed :smile: please report any issues you might find (I hope none)

To use a package from git clone, you first need to `npm link` after building it, then run `npm link <package>` where you need the package.

**Comment by maurocasas** [comment]
I'm really starting to hate my life right now.


> argon2@0.9.0 install /root/test4/node_modules/argon2
> node-gyp rebuild

make: Entering directory `/root/test4/node_modules/argon2/build'
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
../argon2/src/core.c: In function ‘validate_inputs’:
../argon2/src/core.c:361:9: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
../argon2/src/core.c:391:9: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
../argon2/src/core.c:406:9: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
../argon2/src/core.c:420:5: warning: comparison is always false due to limited range of data type [-Wtype-limi                                                       ts]
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  AR(target) Release/obj.target/argon2.a
  COPY Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
../src/argon2_node.cpp: In function ‘NodeArgon2::size_type NodeArgon2::encodedLength(NodeArgon2::size_type)’:
../src/argon2_node.cpp:34:46: error: ‘UINT32_C’ was not declared in this scope
../src/argon2_node.cpp:34:46: error: ‘UINT64_C’ was not declared in this scope
../src/argon2_node.cpp:34:71: error: unable to deduce ‘const auto’ from ‘<expression error>’
../src/argon2_node.cpp:35:62: error: unable to deduce ‘const auto’ from ‘<expression error>’
../src/argon2_node.cpp:36:66: error: unable to deduce ‘const auto’ from ‘<expression error>’
../src/argon2_node.cpp: In function ‘void init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
../src/argon2_node.cpp:251:34: error: ‘UINT32_C’ was not declared in this scope
../src/argon2_node.cpp:251:34: error: ‘UINT64_C’ was not declared in this scope
../src/argon2_node.cpp: In function ‘NodeArgon2::size_type NodeArgon2::encodedLength(NodeArgon2::size_type)’:
../src/argon2_node.cpp:41:1: warning: control reaches end of non-void function [-Wreturn-type]
make: *** [Release/obj.target/argon2/src/argon2_node.o] Error 1
make: Leaving directory `/root/test4/node_modules/argon2/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v4.3.0/lib/node_modules/npm/node_modules/n                                                       ode-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "/root/.nvm/versions/node/v4.3.0/bin/node" "/root/.nvm/versions/node/v4.3.0/lib/node_modules/                                                       npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/test4/node_modules/argon2
gyp ERR! node -v v4.3.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/root/.nvm/versions/node/v4.3.0/bin/node" "/root/.nvm/versions/node/v4.3.0/bin/npm" "install" "                                                       argon2"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! argon2@0.9.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.9.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the argon2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls argon2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/test4/npm-debug.log

**Comment by ranisalt** [comment]
I can bet it is because your g++ version is too old. g++ 4.8 or higher is required because of heavy use of C++11 syntax, both by this package and its dependencies (nan).

**Comment by maurocasas** [comment]
Indeed it was my friend. I upgraded my Debian 7 Wheezy to G++ 4.9

I had to manually add debianJeesy repos and then run apt-get update and do the usual aptitude installation

I hope some day I catch you and buy you a beer! (Y)
