### ISSUE TITLE
argon2 prebuilt binaries fails on debian stretch

### ISSUE THREAD

**Issue by jnardone** [ranisalt/node-argon2#244]
Debian 9 (aka 'stretch') fails to use the prebuilt binaries though it thinks it can use them.

This is because stretch uses glibc 2.24, but the prebuilt binaries require 2.25:

`Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /root/repo/node_modules/argon2/lib/binding/argon2.node)`

Stretch is supported until 2022; can we build these libraries against an older glibc (so that it supports these platforms) or figure out how to let them downgrade to source builds if not?  (note: i'd much much rather have it support with the prebuilt binaries!)

**Comment by ranisalt** [comment]
While we can pin to `ubuntu-16.04` instead of `ubuntu-latest`, which ships with 2.23 I believe, it would be better to report upstream at `node-pre-gyp` to work around this for all packages.

That said, isn't it a security issue to run a very old glibc version? 2.25 is already 3 years old now and 2.24 is 6 more months older.

**Comment by jnardone** [comment]
I guess you can take that up with Linux maintainers. I know a number of them will patch old libs vs upgrading as part of their maintenance lifecycle. So I expect Stretch for example to stay on some form of 2.24 for its entire existence if history is any guide.

**Comment by jaschaio** [comment]
Any workaround? Not sure why I didn't run into the problem before but now I am seeing this while trying to run this library in a docker container with node `13.8.0-slim` (which apparently uses Debian 9)

**Comment by jaschaio** [comment]
Using Debian 10 aka `buster` (or `node:13.8.0-buster-slim` image from docker hub) works for me as a workaround although that is of course not the resolution for this issue. Just wanted to leave this here in case anybody else runs into the same issue

**Comment by jnardone** [comment]
We had to go back to 0.24.1. Hoping these images get rebuilt with Debian 9 though.

**Comment by BjornLuG** [comment]
I sent a PR #247 explaining how to rebuild the binaries, or to skip prebuilt binaries installation.

To rebuild binaries:
```bash
$ node-gyp rebuild -C ./node_modules/argon2
```

To skip prebuilt binaries installation and compile from source:
```bash
# Force build from source
$ npm install argon2 --build-from-source

# or

# Ignore node-argon2 install script, and build explicitly
$ npm install argon2 --ignore-scripts
$ node-gyp rebuild -C ./node_modules/argon2
```

**Comment by jnardone** [comment]
Thank you, though this doesn’t help as much with automated pipelines that expect to be able to just `npm ci` and expect it to work.

**Comment by BjornLuG** [comment]
True. Well, at least for now `npm ci --build-from-source` also forces rebuilding argon2. Or by setting `npm_config_build_from_source=true` will work too. But IMO the easiest way would be to use `ubuntu-16.04` for the prebuilt binaries. `bcrypt` also uses 16.04 for their prebuilt binaries (default by Travis). I'm not sure if there's any downsides though, but it's @ranisalt 's call to give the green light.

**Comment by digitalkaoz** [comment]
rebuilding this inside node docker fails (`node:13`)

```
 $ npm install -g node-gyp
 /usr/local/bin/node-gyp -> /usr/local/lib/node_modules/node-gyp/bin/node-gyp.js
 + node-gyp@6.1.0
 added 100 packages from 66 contributors in 4.5s
 $ node-gyp rebuild -C ./api/node_modules/argon2
 gyp info it worked if it ends with ok
 gyp info using node-gyp@6.1.0
 gyp info using node@13.8.0 | linux | x64
 gyp info chdir ./api/node_modules/argon2
 gyp info find Python using Python version 3.5.3 found at "/usr/bin/python3"
 gyp http GET https://nodejs.org/download/release/v13.8.0/node-v13.8.0-headers.tar.gz
 gyp http 200 https://nodejs.org/download/release/v13.8.0/node-v13.8.0-headers.tar.gz
 gyp http GET https://nodejs.org/download/release/v13.8.0/SHASUMS256.txt
 gyp http 200 https://nodejs.org/download/release/v13.8.0/SHASUMS256.txt
 gyp info spawn /usr/bin/python3
 gyp info spawn args [
 gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
 gyp info spawn args   'binding.gyp',
 gyp info spawn args   '-f',
 gyp info spawn args   'make',
 gyp info spawn args   '-I',
 gyp info spawn args   '/builds/XXX/api/node_modules/argon2/build/config.gypi',
 gyp info spawn args   '-I',
 gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
 gyp info spawn args   '-I',
 gyp info spawn args   '/root/.cache/node-gyp/13.8.0/include/node/common.gypi',
 gyp info spawn args   '-Dlibrary=shared_library',
 gyp info spawn args   '-Dvisibility=default',
 gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/13.8.0',
 gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/node-gyp',
 gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/13.8.0/<(target_arch)/node.lib',
 gyp info spawn args   '-Dmodule_root_dir=/builds/XXX/api/node_modules/argon2',
 gyp info spawn args   '-Dnode_engine=v8',
 gyp info spawn args   '--depth=.',
 gyp info spawn args   '--no-parallel',
 gyp info spawn args   '--generator-output',
 gyp info spawn args   'build',
 gyp info spawn args   '-Goutput_dir=.'
 gyp info spawn args ]
 gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
 gyp ERR! configure error 
 gyp ERR! stack Error: `gyp` failed with exit code: 1
 gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:351:16)
 gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
 gyp ERR! System Linux 4.19.76-linuxkit
 gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild" "-C" "./api/node_modules/argon2"
 gyp ERR! cwd /builds/XXX/api/node_modules/argon2
 gyp ERR! node -v v13.8.0
 gyp ERR! node-gyp -v v6.1.0
 gyp ERR! not ok 
```

t.b.h. this is a real PITA! downgrading doesnt seem to be an option for me

**Comment by digitalkaoz** [comment]
@ranisalt actually the documentation is wrong, we have to use `node-pre-gyp` now.

so rebuilding works then:

```
$ npm install -g node-pre-gyp
$ node-pre-gyp rebuild -C ./node_modules/argon2
```

this module works correctly in `node:13` then!

@jnardone can you try it?

**Comment by jnardone** [comment]
@digitalkaoz You're missing the point.

*I should not have to do this.*

I should be able to run `npm i` or `npm ci` and have it work correctly on reasonable platforms.  The currently packaged prebuilt binaries fail on platforms it says it supports.  This can be fixed by targeting an older debian (stretch, which is what the node 13 docker image uses btw) or not packaging the binaries (which leads to other fun with node-gyp) but right now I consider this *broken*.

**Comment by digitalkaoz** [comment]
@jnardone sure you are right, i expect it to work Out of the Box too! Just wanted to share a working workaround!

**Comment by jnardone** [comment]
Yes, thank you. :)

**Comment by ranisalt** [comment]
I will accept a PR downgrading Ubuntu version to 16.04. That said, I will upgrade to 18.04 as soon as standard support ends, on April 2021 (plenty of time to update your Debian release until then :smile:)

**Comment by digitalkaoz** [comment]
Tbh, it should be fixed inside node:13 Images, or in the Debian Image.
Downgrading is never a good option! Im not into C and GCC so I dont have a
proper opinion on that, but it should compile everywhere. Or maybe the
solution is just to distribute a working binary for those Distributions.
Should be easy to generate with Docker-Actions i guess

Ranieri Althoff <notifications@github.com> schrieb am Do., 27. Feb. 2020,
19:44:

**Comment by BjornLuG** [comment]
Ah, my bad @digitalkaoz. I actually encountered that same error before but It didn't appeared for some reason the last time I ran it and it slipped my mind when I submitted the PR the other day. I'll be sure to correct it in the next PR.

And at the same time, I'll downgrade to ubuntu 16.04. Everything should work as is again.

**Comment by BjornLuG** [comment]
@jnardone  I didn't know that the keyword "resolve" will auto close this issue, but once this gets merged and released, it'll be great if you can test it out again to see if it works :+1:
