### ISSUE TITLE
Compiler optimizes away zero-scrubbing heap for sensitive data

### ISSUE THREAD

**Issue by daniel-j-h** [ranisalt/node-argon2#246]
Spotted this while skimming the binding code: [here](https://github.com/ranisalt/node-argon2/blob/ff9a0029cc12c414951b55850c2bfe8797b9159b/src/argon2_node.cpp#L81-L99) we
- new[] a chunk of memory
- work on it
- fill it with zeros in order to scrub sensitive data from our heap
- delete[] it

Compiling this C++ code an optimizing compiler is allowed to just remove the zero filling under the [as-if rule](https://en.cppreference.com/w/cpp/language/as_if). Therefore the following line will get removed leaving the heap space containing sensitive data:

https://github.com/ranisalt/node-argon2/blob/ff9a0029cc12c414951b55850c2bfe8797b9159b/src/argon2_node.cpp#L96

If you want to scrub the heap, care has to be taken to make sure the compiler does not just remove it.

**Comment by ranisalt** [comment]
I wouldn't say it is sensitive, it contains the hash and Argon2 by default doesn't clean this from memory anyway. We might get away using [flags](https://github.com/P-H-C/phc-winner-argon2/blob/62358ba2123abd17fccf2a108a301d4b52c01a7c/include/argon2.h#L90-L93) instead.

**Comment by tutankhatum** [comment]
You can use `volatile` to prevent compiler's intervention, right?

**Comment by daniel-j-h** [comment]
Sorta; [here](https://github.com/jedisct1/libsodium/blob/599cb10246cef0fd2d090dd8f805620f119db26c/src/libsodium/sodium/utils.c#L120-L150) is what libsodium does.
