### ISSUE TITLE
Does not work with yarn2

### ISSUE THREAD

**Issue by jeffrson** [ranisalt/node-argon2#249]
# Steps to reproduce
1. yarn init -y
2. yarn set version 2
3.  yarn add argon2

### Expected behaviour
Installs without error

### Actual behaviour
➤ YN0000: ┌ Resolution step
➤ YN0032: │ node-addon-api@npm:2.0.0: Implicit dependencies on node-gyp are discouraged
➤ YN0000: └ Completed in 2.56s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 2.89s
➤ YN0000: ┌ Link step
➤ YN0007: │ argon2@npm:0.26.1 must be built because it never did before or the last one failed
➤ YN0009: │ argon2@npm:0.26.1 couldn't be built successfully (exit code 127, logs can be found here: ...)
➤ YN0000: └ Completed in 8.74s
➤ YN0000: Failed with errors in 14.27s

### Environment
**Operating system**:
Windows 10

**Node version:**
13.9.0

node-gyp *is* installed globally, but yarn2 doesn't use it.

Best solution argon2 could make: list node-gyp in peerDependencies - locally installed node-gyp helps.

**Comment by ranisalt** [comment]
Hey, it seems there was a problem with the deploy for v0.26.1 and that was fixed with v0.26.2. Anyway I added node-gyp to devDependencies should one need to build from sources.
