### ISSUE TITLE
Can we get pre-built binary for node 14.x?

### ISSUE THREAD

**Issue by sekarpdkt** [ranisalt/node-argon2#262]
Hi 

Can we get pre-built binary for node 14.x? 

Thanks

**Comment by ranisalt** [comment]
Yes! Add version [here](https://github.com/ranisalt/node-argon2/blob/master/.github/workflows/ci.yml#L9) and open a pull request :) I'll merge and publish a new release.

**Comment by sekarpdkt** [comment]
Oops !!! it was so simple :-).. Thanks. I raised the PR.

**Comment by MichielDeMey** [comment]
I believe that just enables testing for Node 14.x, but pre-built binaries are determined in `release.yml`, no?
https://github.com/ranisalt/node-argon2/blob/master/.github/workflows/release.yml#L35
https://github.com/ranisalt/node-argon2/blob/master/.github/workflows/release.yml#L71

**Comment by ranisalt** [comment]
@MichielDeMey I don't exactly understand that, I think we build against the oldest still supported LTS and N-API takes care of handling support for newer versions. The binary for Node 10 should still work on Node 12, 13 and 14.

**Comment by MichielDeMey** [comment]
Odd, it's showing it cannot find the pre-built binaries when installing inside my `FROM node:14-alpine` docker image.

```
> argon2@0.26.2 install /usr/src/app/node_modules/argon2
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for argon2@0.26.2 and node@14.4.0 (node-v83 ABI, musl) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Remote end closed socket abruptly.
```

Must be something wrong with my Dockerfile, thanks for the information!

**Comment by sekarpdkt** [comment]
I am updating it for record purpose. Actually I had issue in getting it installed inside a docker of a raspberry pi (for a demo project), with node14.x. As no binary images were available, it was going for compiling from source and failing. As arm64 images were not there it was failing again (for all node versions). As I was trying to install it globally (npm -g ...) and it was not working. If anyone else facing problem, inside docker, try to avoid global installation. If it all it (global) is necessary, there is a switch to disable security check while running npm install (which worked but I opted for non global installation).

**Comment by MichielDeMey** [comment]
Just leaving this here:

It looks like it was something in my lockfile using NPM, I could not exactly pinpoint the issue.
I switched to Yarn instead and it installed successfully with pre-built binaries for all node versions (10, 12, 14).

**Comment by ranisalt** [comment]
@sekarpdkt can you post the logs?

@MichielDeMey if possible, post this issue to the npm repository, they have more knowledge and manpower to investigate it if it is related to npm and not argon2 ;)

**Comment by sekarpdkt** [comment]
Hi @ranisalt, as mentioned above it is not an issue with Argoan2. just recorded it here to ensure if others are facing similar issue, they can get help. Refer to

https://stackoverflow.com/questions/44633419/no-access-permission-error-with-npm-global-install-on-docker-image

There are couple of workarounds are explained there, but, I believe not worth the risk associated.

Following docker config will fail (global install)

```
FROM node:buster

COPY ./package.json .

RUN apt update && apt -y upgrade && apt -y install curl gnupg2  ca-certificates && \
    apt-get autoremove -y && \
    apt-get clean -y && \ 
    npm -g install argon2
```

Following either of the following two will work. (Global install with --unsage-perm flag or local install). 

```
FROM node:buster

COPY ./package.json .

RUN apt update && apt -y upgrade && apt -y install curl gnupg2  ca-certificates && \
    apt-get autoremove -y && \
    apt-get clean -y && \ 
    npm install -g  --unsafe-perm argon2
```

or 

```
FROM node:buster

COPY ./package.json .

RUN apt update && apt -y upgrade && apt -y install curl gnupg2  ca-certificates && \
    apt-get autoremove -y && \
    apt-get clean -y && \ 
    npm install  argon2
```
