### ISSUE TITLE
Doesn't work in Node 14, bindings don't build

### ISSUE THREAD

**Issue by DVLP** [ranisalt/node-argon2#269]
It's won't build in Node 14. It's an issue with packages using C++ bindings. Here's a similar topic of the same happening with another package https://github.com/Project-OSRM/osrm-backend/issues/5720

`npm install argon2` on Node 14 to reproduce

**Comment by DVLP** [comment]
It looks like version 0.27 works fine but it's not released on npm or tagged here. Please release to NPM. In the meantime the workaround is to install straight form the repo in package.json 
`"argon2": "github:ranisalt/node-argon2#master",`

**Comment by ranisalt** [comment]
I just launched v0.27.0 :D

**Comment by DVLP** [comment]
perfect, thanks
