### ISSUE TITLE
node-gyp >= 4.0.0?

### ISSUE THREAD

**Issue by rdegges** [ranisalt/node-argon2#27]
### Steps to reproduce

1. Install latest stable release of node-gyp from npm (3.3.0).
2. This is NOT >= 4.0.0
3. Try to install this library via npm -- it will not work.

### Expected behaviour

Ideally, this should build against 3.3.0 of node-gyp or greater (for future releases), but not depend on unreleased versions of node-gyp.

### Actual behaviour

Things don't work :(

### Environment

**Operating system**: OSX.

**Node version:** 5.5.0

**Compiler version:** <xxx>

**Comment by ranisalt** [comment]
Sorry, that text is misleading, it's supposed to mean it only works with **Node** >= 4.0.0, not node-gyp. I use 3.3.0 locally too :laughing:
