### ISSUE TITLE
Release 0.27.0

### ISSUE THREAD

**Issue by SteinRobert** [ranisalt/node-argon2#270]
`0.26.2` uses a version of `node-addon-api` which is vulnerable to remote memory exposure.
![Bildschirmfoto 2020-08-13 um 10 36 29](https://user-images.githubusercontent.com/1231105/90113213-49e42780-dd51-11ea-8fc8-824e35cb4dee.png)

It seems the version has already been upgraded, only a release is missing.

**Comment by ranisalt** [comment]
I just launched v0.27.0 :D
