### ISSUE TITLE
Getting error when deploying to AWS lambda

### ISSUE THREAD

**Issue by oran1248** [ranisalt/node-argon2#271]
### Steps to reproduce
1. Deploying `next.js` project using `serverless-next.js` to AWS lambda. My project uses `argon2` package.
2. Deployment succeeded, but when lambda is running, getting the following error in log:
![image](https://user-images.githubusercontent.com/26431778/95506067-03f5b980-09b8-11eb-97e1-4090f6a94405.png)

### Expected behaviour
No error should occur.

### Actual behaviour
Got error as I showed above.

### Environment
Amazon AWS Lambda Linux Machine

I read this: https://aws.amazon.com/blogs/compute/nodejs-packages-in-lambda/
But couldn't figure out how to fix it.

**Comment by vespertilian** [comment]
@oran1248 

Are you on windows or mac? I am using SAM, similar to serverless. 

You need to run something like this when packaging your serverless app so the binary used is the correct one 

`npm install bcrypt --save --target=12.2.0 --target_arch=x64 --target_platform=linux --target_libc=glibc`

Or build the bundle on AWS Linux VM. 

https://github.com/serverless/serverless/issues/308
