### ISSUE TITLE
Many warnings and errors in angular project after adding argon2

### ISSUE THREAD

**Issue by y-chen** [ranisalt/node-argon2#273]
I installed `argon2` in angular project to encrypt passwords. Since then I am getting many errors when I try to build it.
The errors look like this:

```
ERROR in /<project>/node_modules/argon2/node_modules/minizlib/constants.js
Module not found: Error: Can't resolve 'zlib' in '/<project>/node_modules/argon2/node_modules/minizlib'
```

The involved modules are `crypto, fs, http, https, os, path, stream` and many others, I tried to install them manually but other errors came up.

### Steps to reproduce
1. Install argon2 
2. Use it to hash a plain text
3. Run `ng build`

### Expected behaviour
Compile without errors

### Actual behaviour
Many warnings and errors:

![image](https://user-images.githubusercontent.com/5136314/99145694-29d64400-2671-11eb-9962-b6aa4f0731df.png)
![image](https://user-images.githubusercontent.com/5136314/99145701-3b1f5080-2671-11eb-8267-7817c679136e.png)

### Environment
**Operating system**:
macOS Catalina 10.15.7 (19H2)

**Node version:**
Node 15.2.0

**Compiler version:**
?

**Comment by ranisalt** [comment]
If you are trying to use argon2 in the browser, this will not work. Try [argon2-browser](https://www.npmjs.com/package/argon2-browser) instead.

But don't hash user passwords before sending to the server, if that's the case.

**Comment by y-chen** [comment]
Actually my project is a NX mono repo with a CryptService in the backend and used by other services, but when I build the frontend Angular app I get all these errors even if it's not used in it.

Is it a best practice to hash passwords in the backend?
I was wondering if it's good to POST plain user password to the Web API.

**Comment by ranisalt** [comment]
The issue seems to be in the [minizlib](https://github.com/isaacs/minizlib) repo, not this one, try opening the same report there and see what you get from them.

> Is it a best practice to hash passwords in the backend?

Yes, it does not make sense to hash in the frontend, and that is simply put unsafe.

>  I was wondering if it's good to POST plain user passwords to the Web API.

It is, just make sure to use HTTPS.

**Comment by ipankajsingh** [comment]
> > I was wondering if it's good to POST plain user passwords to the Web API.
> 
> It is, just make sure to use HTTPS.

How is it safe ?
Anyone can see the request payload via Network tab in Browser, if the password is plain text, it will be readily available.

**Comment by ranisalt** [comment]
>  Anyone can see the request payload via Network tab in Browser, if the password is plain text, it will be readily available.

This assumes that the person has full access to the system. The browser just displays it for debugging, but the entire payload is encrypted (even the path) when you use HTTPS.

**Comment by ipankajsingh** [comment]
True.
But encrypting (not hashing) will still be better than sending a plain text, we can decrypt it in the backend and then hash and store it in DB.
I might be wrong, but somehow it just feels wrong to send a plain text password

**Comment by ranisalt** [comment]
>  But encrypting (not hashing) will still be better than sending a plain text, we can decrypt it in the backend and then hash and store it in DB.

Yes, the idea is right, and that is exactly what HTTPS does. There is no plain text password in the packet that travels between the client and the server.

If you send the password not in plain text in the encrypted payload, the result of the operation you do with the password effectively becomes the password. In other words, if you run Argon2 on the password and send the hash to the server, the hash effectively serves as the password, providing virtually no extra security - or at least not what you expect.

You don't need to worry about this, as HTTPS will provide you key exchange, encryption and even forward secrecy (i.e. leakage of the server private key will not enable an attacker to decrypt a packet).

To be fair, [I had this confusion too a couple of years back](https://stackoverflow.com/questions/14392085/where-do-i-hash-the-password) :laughing:

**Comment by ipankajsingh** [comment]
agree completely, it's just that as a developer it feels wrong on our side to rely on something else (HTTPS in this case) to do all the heavy lifting behind the scene while we can't see anything. Human tendency.
