### ISSUE TITLE
Broken argon2.node on RHEL7

### ISSUE THREAD

**Issue by thias** [ranisalt/node-argon2#276]
### Steps to reproduce
1. Install Directus with `npx create-directus-project foo`
2. Run `npx directus --help` (or any other directus sub-command)
3. No output and exit status 0.

### Expected behaviour

The directus command should work. And the original npx create-directus-project should even have presented a configuration menu.

### Actual behaviour

The directus command doesn't work. No output ever, no useful messages and a confusing exit status of 0.

After stracing the npx execution, I saw that argon2.node was the last file opened by the execution. And after digging some more, I saw that the `node_modules/argon2/lib/binding/napi-v3/argon2.node` file I get is dated August 13, meaning that it's a binary pulled from somewhere. And it's broken on RHEL7:
```
$ ldd /tmp/foo/node_modules/argon2/lib/binding/napi-v3/argon2.node
/tmp/foo/node_modules/argon2/lib/binding/napi-v3/argon2.node: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/foo/node_modules/argon2/lib/binding/napi-v3/argon2.node)
/tmp/foo/node_modules/argon2/lib/binding/napi-v3/argon2.node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/foo/node_modules/argon2/lib/binding/napi-v3/argon2.node)
/tmp/foo/node_modules/argon2/lib/binding/napi-v3/argon2.node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/foo/node_modules/argon2/lib/binding/napi-v3/argon2.node)
    linux-vdso.so.1 =>  (0x00007ffce9b53000)
    libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fc9f3cdc000)
    libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fc9f3ac6000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fc9f38aa000)
    libc.so.6 => /lib64/libc.so.6 (0x00007fc9f34dc000)
    libm.so.6 => /lib64/libm.so.6 (0x00007fc9f31da000)
    /lib64/ld-linux-x86-64.so.2 (0x00007fc9f41f4000)
```

The fix was simple enough:
```
npm rebuild argon2 --build-from-source
```

...and all `npx directus` commands started working.

### Environment

**Operating system**: Red Har Enterprise Linux 7

**Node version:** 10, 12, 13 and 14 tested (before finding the root cause)

**Compiler version:** `gcc-4.8.5-39.el7.x86_64`

**Comment by davidsandoz** [comment]
> The fix was simple enough:
>
> ```
> npm rebuild argon2 --build-from-source
> ```

Unfortunately, this doesn't work for me because this requires to have `cc` installed and my host doesn't make it available.

So I'm stuck until a proper fix is released.

**Comment by ranisalt** [comment]
@davidsandoz you can't have any C compiler installed?

**Comment by davidsandoz** [comment]
@ranisalt It's a [Managed Cloud Server](https://www.infomaniak.com/en/hosting/dedicated-and-cloud-servers/managed-cloud-server) for web hosting, so I don't have admin access on it. It offers the option to install nvm in order to have Node.js, but not a C compiler. I'll try to contact support to see if they could still do it, maybe only temporarily.

Still, even if they accept, others might be in a similar situation than me, but with their host not accepting to have a C compiler installed.

I guess that fixing the root problem by providing a binary that works out of the box would be best. Or isn't that the actual issue here?

**Comment by gianpesto** [comment]
@davidsandoz i had the same problem with the same hoster and could solve it by installing buildEssential over the gui and then run the rebuild script

**Comment by kroawen** [comment]
On centos 7.9, I  run : yum install gcc gcc-c++ kernel-devel  ,then  run: npm rebuild argon2 --build-from-source, it works

**Comment by ranisalt** [comment]
Could you guys try with the latest release (v0.28.1+) and check if this issue still happens? I changed the build process a bit and it might end up solving.

**Comment by davidsandoz** [comment]
@ranisalt I just tried with the latest release and the behaviour is the same: No output and exit status 0

@gianpesto Thanks for the tip! Indeed, installing *BuildEssential* made the rebuild command to work. And after that I'm able to run Directus properly.

Still, using that rebuild command feels like a workaround. Would be best to have a build of argon2 that works out of the box.

**Comment by qaribhaider** [comment]
> > The fix was simple enough:
> > ```
> > npm rebuild argon2 --build-from-source
> > ```
> 
> Unfortunately, this doesn't work for me because this requires to have `cc` installed and my host doesn't make it available.
> 
> So I'm stuck until a proper fix is released.

This worked for;

On a new install, I did following:
> npm install argon2 --build-from-source
> npm rebuild argon2 --build-from-source
> npx directus init
_Within the created project directory_

**Comment by ShahriarKh** [comment]
Well, on a shared hosting, I tried to follow the above steps, but every time I face a new problem (outdated python, outdated gcc, ...).
Is it possible to build directus in a local machine and then copy the whole project files (including `node_modules` if required) to my host? If it's possible, can you say what steps I need to follow?

**Comment by ranisalt** [comment]
@ShahriarKh not really, if you build it locally you will need the same version of the libraries on your hosting to run it. Usually, you can only run compiled code in a system with the same or newer libraries.

With node-argon2, I try to support the most outdated versions of dependencies that still receive support. If you have an even more outdated version, this is a huge red flag that your system has security issues.

**Comment by ponceleon** [comment]
Same erro in 

Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch

:..(

**Comment by cube-dan** [comment]
Found a fix using SCL; info here: https://github.com/directus/directus/issues/6071#issuecomment-1379418550
