### ISSUE TITLE
Installing fails on Windows

### ISSUE THREAD

**Issue by trgwii** [ranisalt/node-argon2#278]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [ ] Checkout to the latest version, **including submodules**
- [x] Try to find an *isolated* way to reproduce the behavior
- [x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. Create a project (`npm init`)
2. Run `npm i argon2@0.27.1`

### Expected behaviour
npm should install argon2

### Actual behaviour
npm fails with the following message:
```
'opencollective-postinstall' is not recognized as an internal or external command,
operable program or batch file.
'true' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.27.1 postinstall: `opencollective-postinstall || true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.27.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Environment
Windows 10.0.19041.685

**Node version:**
v14.15.1

**Comment by ranisalt** [comment]
It appears to be caused by opencollective/opencollective-postinstall and they are not very responsive (opencollective/opencollective-postinstall#41). So I removed it and will publish a new version soon.

(sorry for the extreme delay)
