### ISSUE TITLE
How is memoryCost per thread, if parallelism/thread# doesn't increase memory usage?

### ISSUE THREAD

**Issue by kaansoral** [ranisalt/node-argon2#281]
This might be a very simple question, but in the docs, it says parallelism determines the thread# and memoryCost is per thread https://github.com/ranisalt/node-argon2/wiki/Options

So if you set memoryCost to 400.000 and parallelism to 40 - You'd expect ~16GB memory usage and 40 threads if you continually run the algorithm, let's say on an 8 thread system

But regardless of what you set parallelism to, actual memory usage is always 400MB's, and thread count is ~20

**1)** Am I right in assuming that thread count is determined based on the system and they are not 1:1 with parallelism as it would be unnecessary since they would just bottleneck naturally, instead the project just throttles on it's own?
**2) The actual question:** How does the memoryCost actually work?

**Comment by ranisalt** [comment]
There may have happened a misinterpretation of the documentation, it looks like the memory cost indeed does not scale with the amount of threads, but rather the allocated memory is split between each thread, so it's actually the opposite.

This library does nothing to throttle thread count, however Argon2 can saturate a processor fairly easily, so with only 8 threads available your system may be struggling to run other threads. I'll investigate it better.

**Comment by FewKinG** [comment]
Sorry, I don't think this can be handed off as just a "misinterpretation". My interpretation of the documentation was the same. It says

> The amount of threads to compute the hash on. Each thread has a memory pool with memoryCost size. Note that changing it also changes the resulting hash.

Which to me clearly indicates that *each* thread gets a (separate) memory pool. I was surprised to learn that it seems to not be that way, so I think the wording is at least very unclear and the documentation should be updated - if indeed the memory pool is and should be shared between threads in the first place, that is.
