### ISSUE TITLE
Usage with jest - package.json does not exist 

### ISSUE THREAD

**Issue by rbutera** [ranisalt/node-argon2#282]
I've run into a really weird situation in a project that uses `argon2`, typescript and `ts-jest`/`jest`.

The error I'm facing is:

```
 FAIL  src/tasks/commands/monthly-summary-email.task.command.spec.ts
  ● Test suite failed to run

    package.json does not exist at /Users/rai/dev/lexstep/lexstep-nest/node_modules/argon2/package.json

       5 |  */
       6 |
    >  7 | import * as argon2 from 'argon2'
         | ^
       8 | import { Logger } from '@nestjs/common'
       9 |
      10 | const log = new Logger('LegacyHashedPassword')

      at Object.<anonymous>.exports.find (node_modules/node-pre-gyp/lib/pre-binding.js:18:15)
      at Object.<anonymous> (node_modules/argon2/argon2.js:8:28)
      at Object.<anonymous> (src/common/legacy-hashed-password.ts:7:1)
```

Does anyone know what this error might mean?

## Some other information and weirdness

- The thing is, the test suite in question does not import 'legacy-hashed-password.ts`.
- There are other specs in the repository that test files that import `legacy-hashed-password.ts` but they work fine?

## Related files in the repo 

```typescript
// legacy-hashed-password.ts

/**
 * LegacyHashedPassword
 * thin wrapper around argon2
 * used for compatibility layer with legacy hashed passwords.
 */

import * as argon2 from 'argon2'
import { Logger } from '@nestjs/common'

const log = new Logger('LegacyHashedPassword')

const LegacyHashedPassword = {
  async hash(password: string): Promise<string> {
    try {
      const hash = await argon2.hash(password)
      return hash
    } catch (error) {
      log.error(`failed to hash password: ${JSON.stringify(error)}`)
    }
  },
  async verify(hash: string, password: string): Promise<boolean> {
    try {
      const result = await argon2.verify(hash, password)
      return result
    } catch (error) {
      log.error(`failed to verify hash: ${JSON.stringify(error)}`)
    }
  },
}

export default LegacyHashedPassword
```

**Comment by ranisalt** [comment]
This is an issue with your resolver and unrelated to this repo.

By the way, if Argon2 is your *legacy* password hash, what are you using? Post-quantim something?

**Comment by rbutera** [comment]
> This is an issue with your resolver and unrelated to this repo.
> 
> 
> 
> By the way, if Argon2 is your *legacy* password hash, what are you using? Post-quantum something?

Thanks. Do you have any idea how I could investigate this issue further? I am banging my head against the wall trying to resolve it 

PS: to answer your question we're migrating users to SaaS auth (auth0) hehe

**Comment by jmcdo29** [comment]
I was able to dig into this. There was a mock of the`fs` module that was stubbing the `existsSync` emthod, which `node-pre-gyp` uses to ensure there is a `package.json`. Because of this `stub`, `argon2` was not able to make use of the `node-pre-gyp.find` method which caused the entire test to fail. Definitely not a problem with the argon2 library, just thought I should give an update on what happened.

**Comment by rbutera** [comment]
Turns out that this issue was caused by someone installing `fs`  from the npm registry (which is bad practice as `fs` is part of the node standard library... and the `fs` package is potentially malware/malicious)

```
"fs": "^0.0.1-security",
```

in addition, the `fs` module was hard mocked in the unit test...

```typescript
jest.mock('fs', () => {
  return {
    existsSync: jest.fn(),
    mkdirSync: jest.fn(),
    readFileSync: jest.fn(),
  }
})
```

this meant that argon2 failed to load correctly as 1) `fs` was globally mocked and 2) `fs.existsSync` did not return true/false

It may have been the result of `fs` being treated by jest as any other package (and not as part of the node standard library) because of this npm installation, OR it may be the result of `fs` being mocked globally, in any case....

WHAT FIXED THE PROBLEM:

1) removed `fs` from package.json (do not install packages that have the same name as node standard library)
2) replaced `jest.mock('fs')` with `jest.spyOn` inside tests

**Comment by rbutera** [comment]
Turns out that this issue was caused by someone installing `fs`  from the npm registry (which is bad practice as `fs` is part of the node standard library... and the `fs` package is potentially malware/malicious)

```
"fs": "^0.0.1-security",
```

in addition, the `fs` module was hard mocked in the unit test...

```typescript
jest.mock('fs', () => {
  return {
    existsSync: jest.fn(),
    mkdirSync: jest.fn(),
    readFileSync: jest.fn(),
  }
})
```

this meant that argon2 failed to load correctly as 1) `fs` was globally mocked and 2) `fs.existsSync` did not return true/false

It may have been the result of `fs` being treated by jest as any other package (and not as part of the node standard library) because of this npm installation, OR it may be the result of `fs` being mocked globally, in any case....

WHAT FIXED THE PROBLEM:

1) removed `fs` from package.json (do not install packages that have the same name as node standard library)
2) replaced `jest.mock('fs')` with `jest.spyOn` inside tests
