### ISSUE TITLE
Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found

### ISSUE THREAD

**Issue by polishdude20** [ranisalt/node-argon2#283]
I'm running argon2 on a node server running on CentOS 7 and I'm getting an error as shown below:

``Error: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /var/www/project/backend/node_modules/argon2/lib/binding/napi-v3/argon2.node)``

**Comment by ranisalt** [comment]
You probably need to update your system.
