### ISSUE TITLE
The hash verification is always FALSE

### ISSUE THREAD

**Issue by JefferyHus** [ranisalt/node-argon2#289]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [x] Checkout to the latest version, **including submodules**
- [x] Try to find an *isolated* way to reproduce the behavior
- [x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. Hash a string & save it
2. User `await argon2.verify(hash, string)`
3. Check the value of the boolean returned by the `verify` method

### Expected behavior
It should return `true`

### Actual behavior
It returns `false` all the time

### Environment
**Operating system**: OSX & Linux

**Node version:** v15

**Compiler version:** default

**Comment by ranisalt** [comment]
Can you write down a small reproduction of the issue?

**Comment by tomcon** [comment]
seems same here, first time back on test ubuntu server for a while.
earlier versions of argon2 were fine.
need to investigate further tomorrow before confirming, spent too long on it tonight
