### ISSUE TITLE
Failed to start in react-create-app environment

### ISSUE THREAD

**Issue by dwebfan** [ranisalt/node-argon2#291]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [x] Checkout to the latest version, **including submodules**
- [ ] Try to find an *isolated* way to reproduce the behavior
- [x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. npx create-react-app test-argon2 --template typescript
2. cd test-argon2
3. yarn add argon2
4. yarn add aws-sdk mock-aws-s3 nock
5. apply this diff in src/App.tsx
```
$ diff App.tsx App.tsx.orig
4d3
< import argon2 from 'argon2';
12c11
<           {argon2.hash("password").then ((hash) => {console.log(hash)})}
---
>           Edit <code>src/App.tsx</code> and save to reload.
```
6. yarn start

### Expected behaviour
The react app should start.

### Actual behaviour
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/74809776/114941362-ed616c80-9df7-11eb-94bb-888b577f3a3a.png">

### Environment
**Operating system**:
MAC OS 10.15.6 (Catalina)

**Node version:**
```
$ node -v
v15.11.0
```
**Compiler version:**
```
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by ranisalt** [comment]
You won't be able to run this library in client-side, it is specific to be run in Node. To run in the browser, check [argon2-browser](https://www.npmjs.com/package/argon2-browser)

**Comment by dwebfan** [comment]
Thanks, will close.
