### ISSUE TITLE
Is it possible to use it only for client side javascript?

### ISSUE THREAD

**Issue by rajhlinux** [ranisalt/node-argon2#292]
Can I use this project and implement it on client side only?

I am not using node.js and have no intension of ever use it.
But I am using JavaScript and would like to know if it is possible to use this github for my JavaScript web project
Basically what I am trying to say is, if it is possible to use it for front end JavaScript

I am using a pure c++ web framework and hence why I am asking if it is possible to implement only hashing on it's client side?
Salting and peppering will be done at the server side.

Please let me know.

Thanks.

**Comment by ranisalt** [comment]
What are you using it for? I suspect you are trying to hash passwords and send them in the request already hashed. If that's the case, it is wrong and insecure.

If you are doing something else, there's [argon2-browser](https://www.npmjs.com/package/argon2-browser) for client-side applications, and if you are using C++ on your server, you can use argon2 directly as it is written in C, or through [libsodium](https://github.com/jedisct1/libsodium).

**Comment by rajhlinux** [comment]
Yes I am trying to send them hashed to the server. Why is it wrong and insecure? It's even more unsecure if it's just plain text sent to the server. Yes I will be using secured connection, but having plain text sent to the server is unsecure in my opinion.
The client side will hash the password then it will AES256 encrypt it, then sent to the sever.
The server will then decrypt the AES256 and then hash password with TWO peppers. 
Example: "pepper_1 + hashed password + pepper_2"
It's just doesn't make sense to have everything done on the server side, it's just too risky is it is compromised.
Having things done on the client side is more dynamic and safer.

**Comment by ranisalt** [comment]
This effectively makes the hash be the password. The password is what you send to the server, not what the user has typed in, it is just convenient to make it the same. You are not preventing any type of leak or insecurity by doing this.

>  The server will then decrypt the AES256 and then the hashed password will get TWO peppers.

One, two, or a million peppers add the same extra security as a single one.

> Even Google follows this logic

They don't, and nobody does. Log in to Google with the network inspector open and you will see that it, as is with every other website, sends the plain text password. TLS is good enough for this - in fact, it does exactly what you want, using a cipher like AES to protect the sensitive information during transfer. You are just using two condoms here.

[Do NOT roll your own crypto](https://security.stackexchange.com/questions/18197/why-shouldnt-we-roll-our-own).

**Comment by rajhlinux** [comment]
> This effectively makes the hash be the password. The password is what you send to the server, not what the user has typed in, it is just convenient to make it the same. You are not preventing any type of leak or insecurity by doing this.

This just completely supports my concerns, the top answer on that link states that:
_"In the database: Too low down. The database should never see plaintext passwords; doing this could, in some situations, end up sending plaintext passwords over the network, displaying them in error messages, or writing them to database logs"_
You do realize there is no difference between plaintext and hashed form passwords sent from the client.
Its just better to have them sent as hash to make it more difficult for making it not readable.

> One, two, or a million peppers add the same extra security as a single one. By the way, since you don't hash with the peppers, they add nothing.

You're failing the concept why these two peppers are added. It's much better than the "common standards" of having one visible salt and one unknow pepper. They are not added together but rather prepended and appended, therefore making it extremely difficult to guess what the real password is. This security feature should not be underestimated the way you seem it to think of it. I would also like to point out that user's data will be encrypted using their password and user name too. Their password and username will not be stored in the database at all. If they forget their passwords, they'll need to make a new account and the old account will get deleted due to inactivity. Users will need to use a password manager from now on, this is how the future will be. This will also make it impossible for hackers to make it worth their time to crack 3 layers of AES256 encryption with no salts and password hashes to ever begin with. You need to think like a hacker when deigning a server system. 

>  TLS is good enough

No its not, don't be lazy for being innovative in security and just accept other people's word for secureness, here's proof:
https://www.zdnet.com/article/raccoon-attack-allows-hackers-to-break-tls-encryption-under-certain-conditions/
https://www.acunetix.com/blog/articles/tls-vulnerabilities-attacks-final-part/
https://www.youtube.com/watch?v=udpamSmD_vU

Today smart hackers can do anything easily to intercept "TLS" or any "Secured" connection. 
I do not trust IT employees or companies to not sniff on the servers for user's data either. It's rather smart on the customer's end to send their sensitive info hashed and encrypted while traveling to the server and the server should never ever see cleartext passwords.

> They don't, and nobody does. Log in to Google with the network inspector open and you will see that it, as is with every other website, sends the plain text password. 

This is why it's so easy to hack into their servers. All of the IT people working for those companies have no clue what security truly is, they don't know the difference between a bit and a byte. You love the concept of watching fully butt naked people traveling over a crystal clear transparent tunnel and then later cover them with clothes in a full blown meeting center to take advantage of people not having real privacy. That's just barbaric.

**Comment by ranisalt** [comment]
> This is why it's so easy to hack into their servers

Think about what you just said.

To all people reading this: do NOT hash passwords before sending to the server. Hash them immediately after the server receives it, and always use TLS. Nothing else is needed.
