### ISSUE TITLE
Got this error "libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory" when attempting to run it in aws lambda docker image

### ISSUE THREAD

**Issue by Lilmortal** [ranisalt/node-argon2#293]
### Steps to reproduce
1. This is my Dockerfile:

FROM node:14.10.1-alpine AS BUILD_IMAGE

WORKDIR /src/app

COPY package.json /src/app/package.json
COPY lerna.json /src/app/lerna.json
COPY ./packages/@foodbudget/backend/api/ /src/app/packages/@foodbudget/backend/api/
COPY ./packages/@foodbudget/backend/jobs/ /src/app/packages/@foodbudget/backend/jobs/
COPY ./packages/@foodbudget/backend/errors/ /src/app/packages/@foodbudget/backend/errors/
COPY ./packages/@foodbudget/backend/logger/ /src/app/packages/@foodbudget/backend/logger/

RUN yarn

COPY tsconfig.json /src/app/tsconfig.json
COPY .env /src/app/.env

RUN yarn setup:server:prod

FROM node:14.10.1-alpine AS BUILD_API_IMAGE

WORKDIR /src/app

COPY --from=BUILD_IMAGE /src/app/packages/@foodbudget/backend/jobs/ /src/app/
COPY --from=BUILD_IMAGE /src/app/.env /src/app/.env
RUN yarn --production

COPY --from=BUILD_IMAGE /src/app/node_modules/.prisma/client/ /src/app/node_modules/.prisma/client/
COPY --from=BUILD_IMAGE /src/app/packages/@foodbudget/backend/api/prisma/ /src/app/node_modules/@foodbudget/api/prisma/
COPY --from=BUILD_IMAGE /src/app/packages/@foodbudget/backend/api/node_modules/ /src/app/node_modules/@foodbudget/api/node_modules/
COPY --from=BUILD_IMAGE /src/app/packages/@foodbudget/backend/api/dist/ /src/app/node_modules/@foodbudget/api/dist/
COPY --from=BUILD_IMAGE /src/app/packages/@foodbudget/backend/api/package.json /src/app/node_modules/@foodbudget/api/package.json

COPY --from=BUILD_IMAGE /src/app/packages/@foodbudget/backend/logger/node_modules/ /src/app/node_modules/@foodbudget/logger/node_modules/
COPY --from=BUILD_IMAGE /src/app/packages/@foodbudget/backend/logger/dist/ /src/app/node_modules/@foodbudget/logger/dist/
COPY --from=BUILD_IMAGE /src/app/packages/@foodbudget/backend/logger/package.json /src/app/node_modules/@foodbudget/logger/package.json

COPY --from=BUILD_IMAGE /src/app/packages/@foodbudget/backend/errors/node_modules/ /src/app/node_modules/@foodbudget/errors/node_modules/
COPY --from=BUILD_IMAGE /src/app/packages/@foodbudget/backend/errors/dist/ /src/app/node_modules/@foodbudget/errors/dist/
COPY --from=BUILD_IMAGE /src/app/packages/@foodbudget/backend/errors/package.json /src/app/node_modules/@foodbudget/errors/package.json

FROM public.ecr.aws/lambda/nodejs:14

RUN npm install -g node-gyp

RUN yum install -y \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    musl-libc \
    google-chrome-stable\
    gcc

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_SKIP_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

COPY --from=BUILD_API_IMAGE /src/app/dist/src/ ./
COPY --from=BUILD_API_IMAGE /src/app/node_modules/ ./node_modules/
COPY --from=BUILD_API_IMAGE /src/app/.env ./.env

CMD ["index.handler"]

The only relevant part is at the bottom, where I use "FROM public.ecr.aws/lambda/nodejs:14".
I tried installing gcc and node-gyp but to no avail.

### Expected behaviour
I am trying to create a cron job on AWS Lambda that will call my API, which internally uses argon2. All these happened under Docker. When I build it and try to run it, I expect it to work, but instead I got the error as shown below.

### Actual behaviour
I got this error.

Uncaught Exception      {"errorType":"Error","errorMessage":"libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory","stack":["Error: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory","    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)","    at Module.load (internal/modules/cjs/loader.js:928:32)","    at Function.Module._load (internal/modules/cjs/loader.js:769:14)","    at Module.require (internal/modules/cjs/loader.js:952:19)","    at require (internal/modules/cjs/helpers.js:88:18)","    at Object.<anonymous> (/var/task/node_modules/argon2/argon2.js:9:56)","    at Module._compile (internal/modules/cjs/loader.js:1063:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)","    at Module.load (internal/modules/cjs/loader.js:928:32)","    at Function.Module._load (internal/modules/cjs/loader.js:769:14)"]}

### Environment
**Operating system**:
Mac

**Node version:**
v15.4.0

## EDIT:

const binary = require('@mapbox/node-pre-gyp')
const path = require('path')
const bindingPath = binary.find(path.resolve(path.join(__dirname, './package.json')))
// The error is from this line in argon2.
const { hash: _hash, limits, types, names, version } = require(bindingPath) /* eslint-disable-line */

I copied package.json to the compiled docker image, but I still have the same error...

**Comment by azrikahar** [comment]
I believe it's because you're using the Alpine version. It is mentioned over here: https://github.com/mhart/alpine-node#caveats

You can either try the solution provided in the link, or you'll need to try using non-Alpine variant to verify whether it works or not. Do note that this kind of error is also very possible for many other libraries (can't remember what are the libraries now), not just node-argon2, hence the caveat of using Alpine images are highlighted in Docker Node.

**Comment by Lilmortal** [comment]
Hey you are right! I tried to follow the solutions provided in the link, but it did not work. At the end, I just removed the alpine image and it works. Thanks alot!

**Comment by harishsd1998** [comment]
@jacktan165 can you please mention which image you used to resolve this issue?

**Comment by RusselRillema** [comment]
@jacktan165 I am also wondering what image you used to solve this issue

**Comment by ranisalt** [comment]
They probably used `node:alpine` instead. If you build on Alpine, you must run on Alpine.
