### ISSUE TITLE
Cannot Build from Source Automatically

### ISSUE THREAD

**Issue by DakotaLarson** [ranisalt/node-argon2#294]
### Steps to reproduce
1. Install argon2 on CentOS7
2. Run program
3. See this error: http://prntscr.com/125xcbl

### Expected behaviour
Not get an error

### Actual behaviour
Get an error

### Environment
**Operating system**: CentOS 7

**Node version:** 14.16.1

**Compiler version:** 

This is related to #276, however, I think this description provides a better ask users can work with.

In the FAQ, it is stated that if you want to disregard the prebuilt binaries, you have to run `npm rebuild argon2 --build-from-source` or a similar command. 

The formal issue at hand is that this behavior is not automatic. I cannot dictate to this library (through an environment variable for example) that I always want to disregard the prebuilt libraries, so if I run `npm i` I will always get unworkable code until I rebuild manually. Could this be made possible?

**Comment by cube-dan** [comment]
I got argon2 to behave on CentOS 7 using SCL, info here: https://github.com/directus/directus/issues/6071#issuecomment-1379418550

**Comment by ranisalt** [comment]
@cube-dan thanks for the tip! While not ideal to stay in outdated systems, it might help creating a migration path.
