### ISSUE TITLE
Update the NPM repository

### ISSUE THREAD

**Issue by naorpeled** [ranisalt/node-argon2#300]
Hey,
@ranisalt could you upload the latest version to NPM?

thanks in advance :)

**Comment by ranisalt** [comment]
Huh, we have automatic deploy to NPM set up, I don't know what happened last time

**Comment by naorpeled** [comment]
> Huh, we have automatic deploy to NPM set up, I don't know what happened last time

I see.. do you think you could look into it today?

**Comment by ranisalt** [comment]
As soon as #297 is merged

**Comment by naorpeled** [comment]
> As soon as #297 is merged

Awesome, thank you!

**Comment by ranisalt** [comment]
Done!
