### ISSUE TITLE
404 when trying to pull binary from https://github.com/ranisalt/node-argon2/releases/download/v0.28.0/argon2-v0.28.0-napi-v3-linux-x64-musl.tar.gz

### ISSUE THREAD

**Issue by net5033** [ranisalt/node-argon2#301]
We just updated to node-argon2 v0.28.0 and it looks like we are having an issue pulling the pre built binaries. We are using Alpine Linux and on Node 14 and get the following errors when trying to build argon2. It looks like this is something built and hosted on your GitHub.

`node-pre-gyp http GET https://github.com/ranisalt/node-argon2/releases/download/v0.28.0/argon2-v0.28.0-napi-v3-linux-x64-musl.tar.gz`

`node-pre-gyp ERR! install response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.28.0/argon2-v0.28.0-napi-v3-linux-x64-musl.tar.gz`

**Comment by ranisalt** [comment]
Wait until 0.28.1 is published, requirements for node-gyp have changed and I was not notified of build failutes

**Comment by ranisalt** [comment]
There you go, the binary file: https://github.com/ranisalt/node-argon2/releases/tag/v0.28.1
