### ISSUE TITLE
Build fails on Node 16.4 ARM M1

### ISSUE THREAD

**Issue by stevenmunro** [ranisalt/node-argon2#305]
I note there are new ARM builds but trying `yarn add argon2` fails on my system.

Big Sur 11.3
Node v16.4.0

```
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.5
node-pre-gyp info using node@16.4.0 | darwin | arm64
node-pre-gyp info check checked for "/Volumes/Samsung 850PRO/NEXTJS_Sites/restaurant/node_modules/argon2/lib/binding/napi-v3/argon2.node" (not found)
node-pre-gyp http GET https://github.com/ranisalt/node-argon2/releases/download/v0.28.2/argon2-v0.28.2-napi-v3-darwin-arm64-unknown.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.28.2/argon2-v0.28.2-napi-v3-darwin-arm64-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for argon2@0.28.2 and node@16.4.0 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.28.2/argon2-v0.28.2-napi-v3-darwin-arm64-unknown.tar.gz
[...] 
```

**Comment by ranisalt** [comment]
Odd, indeed there is no Darwin ARM64 build even though we have it in the pipeline

![image](https://user-images.githubusercontent.com/1993083/123926797-c852b380-d97b-11eb-877a-95f78ff4a761.png)

**Comment by ranisalt** [comment]
Indeed, we build for ARM64 and for OS X but not for OS X on ARM64 together. I don't even think it is feasible, as GitHub Actions run on x86 and the run-on-arm64 action [does not support OS X](https://github.com/uraimo/run-on-arch-action#supported-platforms). For the time being, you will have to rebuild from sources.

**Comment by nVitius** [comment]
There's an open issue for M1 support on github actions: https://github.com/actions/virtual-environments/issues/2187

It looks like there hasn't been any updates on it since December of last year.

**Comment by partyconfetti** [comment]
anything?

**Comment by power-f-GOD** [comment]
Anything?

**Comment by maxgfr** [comment]
To solve this problem, I downgrade my node version to v14 by using nvm :

```
nvm install 14 
nvm use 14
```

**Comment by zikster3262** [comment]
any news ?

**Comment by Tooluloope** [comment]
Still fails on node v16.7.0

**Comment by ranisalt** [comment]
No development from Github on supporting M1 for Actions, so no progress on this issue yet :(

**Comment by partyconfetti** [comment]
The package [sharp](https://github.com/lovell/sharp) has an ARM build, it says Mac Stadium but maybe you can try it out? You can checkout the commit here: https://github.com/lovell/sharp/commit/21d1a7ca620fe667fb7dd463cc2fcc80ffebc2e4

**Comment by Slapbox** [comment]
Thanks for all the hard work @ranisalt! Any update on this?

Any possibility this could accelerate the timeline? https://github.com/actions/runner/issues/805#issuecomment-963962733

Some other related threads: https://github.com/gitx/gitx/issues/289

**Comment by ranisalt** [comment]
@Slapbox definitely, will keep track of these in order to support ARM64 OS X as soon as possible.

**Comment by partyconfetti** [comment]
Note on node-gyp fails, apparently I've been using my old `.npmrc` file from my old non-M1 computer, and it had an `node_gyp=[definitely not existing path]` line in it. This was preventing yarn to build the package.
Hope this helps someone!

**Comment by Tenpi** [comment]
This still doesn't install on M1 Macs a year later.

I hope that this is given a higher priority. In the meantime I guess I'll use bcrypt.

**Comment by Slapbox** [comment]
@Tenpi in theory you should be able to build the package from source on M1 machines. It's really just those of us without M1 machines that are out of luck for now.

**Comment by ranisalt** [comment]
> This still doesn't install on M1 Macs a year later.

You should be able to install it from source as @Slapbox mentioned. It is a priority to get it working decently on every major platform but this project doesn't really have the resources to do so swiftly :(

**Comment by Slapbox** [comment]
M1 chips have made trouble for many projects. It's hardly something `node-argon2` is alone in. 

Is there anything the users of this project can do to help accelerate the process?

**Comment by ranisalt** [comment]
Donate a M1 to me so I can work around that :laughing: but seriously, I applied to MacStadium as per @partyconfetti suggestion, and hopefully the workflow used by sharp can be just copy-pasted.

**Comment by AvKat** [comment]
@ranisalt I'm kinda lost here. You said that arm-64 Darwin is in the pipeline but I could not find that at all.
Maybe you could take a look?

**Comment by gpetrov** [comment]
Compiling arm64 images for Darwin (Mac) is also possible on intel with cross compilation.

Check some of the other projects that does that already, like:  https://github.com/lovell/sharp-libvips/blob/main/.github/workflows/build-release.yml

How it is done: https://github.com/lovell/sharp-libvips/pull/74

**Comment by Slapbox** [comment]
@ranisalt - Does this get us any closer? https://github.com/actions/runner/pull/1618#issuecomment-1133366112

**Comment by Slapbox** [comment]
@ranisalt did you ever hear back about your MacStadium application? Any news on this generally?

I hate to keep bumping this thread, but I also dislike that our installer size is 500mb for macOS users (certainly not saying that's your fault - I am very grateful for your work.) I'm eagerly anticipating the day `node-argon2` can have a prebuilt binary for ARM-based macOS devices.

**Comment by ranisalt** [comment]
@Slapbox I got an approval from MacStadium a couple of days ago, but I'm on vacation for this week, after that I'll be able to work on it - and it shouldn't be very long since you guys helped a lot already :)

If you prefer, you can open a pull request configuring it and I will set up the token when needed.

**Comment by Slapbox** [comment]
Any updates @ranisalt? Not to rush you of course; I super appreciate that you even shared this project to begin with! A few macOS users are dismayed at the giant size of the dual-architecture installer we're distributing in the meanwhile which got this back on my radar.

If I had any experience with MacStadium I'd be happy to help with a PR, but sadly I haven't got a clue.

**Comment by ranisalt** [comment]
@Slapbox I'm working on that now on the macos-m1 branch. MacStadium has answered me ~~quite a while ago, but I was super busy changing jobs~~ and now I'm setting up the runner to test, build & deploy the M1 (and possibly M2) versions.

**Comment by ranisalt** [comment]
Here we go! Please help me test [v0.29.0](https://github.com/ranisalt/node-argon2/releases/tag/v0.29.0)

**Comment by Slapbox** [comment]
Thank you so much for your outstanding work @ranisalt! I finally got a chance to give this a try and it's looking great!

**Comment by necm1** [comment]
Macbook Pro M2 2022 user here - still getting following error:
`'node_modules/argon2/lib/binding/napi-v3/argon2.node' (mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))`

I tried it with using [v0.29.0](https://github.com/ranisalt/node-argon2/releases/tag/v0.29.0) but sadly it didn't work, even with v0.29.1

@ranisalt do you've any updates for M2 users? I know you currently trying to make it work with M1 :/

**Comment by ranisalt** [comment]
@necm1 this is an upstream issue, it is [@mapbox/node-pre-gyp](https://github.com/mapbox/node-pre-gyp) that decides what prebuilt to install. Can you open an issue there and link back so we can track it?

**Comment by Slapbox** [comment]
Standing by to smash the thumbs up button on that issue when you've created it @necm1.

**Comment by jodem** [comment]
Updating to 0.29 (you can force sub lib to use 29 with override directive in package.json) worked like a charm, thanks.

**Comment by buildreactive** [comment]
Still seems to be failing? I notice homebrew has an argon2 install available for M1 silicon. Wondering if I can install that and somehow it works in my Elixir apps... in the meantime latest attempt to build:

```
17:32:23.289 [error] Process #PID<0.7222.0> raised an exception
** (RuntimeError) An error occurred when loading Argon2.
Make sure you have a C compiler and Erlang 20 installed.
If you are not using Erlang 20, either upgrade to Erlang 20 or
use bcrypt_elixir (version 0.12) or pbkdf2_elixir.
See the Comeonin wiki for more information.

    (argon2_elixir 3.1.0) lib/argon2/base.ex:19: Argon2.Base.init/0
    (kernel 8.5.4) code_server.erl:1317: anonymous fn/1 in :code_server.handle_on_load/5
17:32:23.290 [warning] The on_load function for module Elixir.Argon2.Base returned:
{%RuntimeError{
   message: "An error occurred when loading Argon2.\nMake sure you have a C compiler and Erlang 20 installed.\nIf you are not using Erlang 20, either upgrade to Erlang 20 or\nuse bcrypt_elixir (version 0.12) or pbkdf2_elixir.\nSee the Comeonin wiki for more information.\n"
 },
 [
   {Argon2.Base, :init, 0,
    [file: 'lib/argon2/base.ex', line: 19, error_info: %{...}]},
   {:code_server, :"-handle_on_load/5-fun-0-", 1,
    [file: 'code_server.erl', line: 1317]}
 ]}
```

Which is a really strange error at this stage...

```
@Firefly % elixir --version
Erlang/OTP 25 [erts-13.2.2] [source] [64-bit] [smp:20:20] [ds:20:20:10] [async-threads:1] [jit] [dtrace]

Elixir 1.14.4 (compiled with Erlang/OTP 25)
```

**Comment by buildreactive** [comment]
It's not an Elixir issue, it's a build issue related to argon2... started happening when I added argon2 as a project dependency. Pulling in argon2 generates an error, and the error seems to be saying "you need a C compiler to compile argon2." (Which is silly, and a misdiagnosis, since I have a C compiler).

So... After a good bit of digging and experimenting... I found the problem is caused by having *a space in the project path.* Moving the project to a new path (with no space) fixes it – and all builds just fine now.

So... workaround: Don't use spaces. Ultimate fix(?): Find out why the build fusses over a space?

**Comment by Slapbox** [comment]
Never using spaces in a project's path is generally good practice because it's just not worth the headaches that spaces can cause.

**Comment by kadiryaren** [comment]
FOUND!

I found a solution.  in my m2 pro  cpu device after running `pip3 install setuptools`  worked for argon.  

Error occurs because of that if you use python 3.12+ `distutils` package doesnt maintained anymore. In 3.12 you should use 
`pip3 install setuptools`   to install package.
