### ISSUE TITLE
Can't use this in angular 8 app with node 14

### ISSUE THREAD

**Issue by iPankajKumar** [ranisalt/node-argon2#308]
Installed the module just fine, 
but while doing "npm start" it throws all these errors.

1
![image](https://user-images.githubusercontent.com/24999656/125502753-c7de3e11-5978-4b0c-a111-0c44d4248c7e.png)

2
![image](https://user-images.githubusercontent.com/24999656/125502689-e0d4eab3-6d12-420d-9ed1-5f0af541b4db.png)

**Comment by ipankajsingh** [comment]
Is this npm module suppose to be used in angular app ? If not, what's the alternative ?

**Comment by ranisalt** [comment]
@ipankajsingh if you are asking if this module can be run on a browser, then no, it is not possible because this library requires the Node runtime to run.

What is the use case? Virtually every time someone tries to do it, they are just doing the wrong thing, so I hope I can help you solve this.

**Comment by ipankajsingh** [comment]
I have a requirement where I need to hash the password using Argon2id in frontend and then verify the hash in the backend.
I believe if I keep all the parameters liek hashLength, salt length etc etc same on both frntend and backend, then I can achieve this.
Let me try the argon2-browser code, the only problem is I have to import the script tag and all that javascript thing, I was looking for pure Typescript implementation.

**Comment by ranisalt** [comment]
@ipankajsingh yes, you will have to use argon2-browser instead. A pure JS/TS implementation of Argon2 is not available yet, as far as I'm concerned.
