### ISSUE TITLE
Elasticbeanstalk deployment help

### ISSUE THREAD

**Issue by rgovindji** [ranisalt/node-argon2#312]
I'm able to deploy to elasticbeanstalk by running the command "npm install argon2--save--target = 12.2.0 --target_arch = x64--target_platform = linux--target_libc = glibc” before deploying. 

The issue I have is locally I'm on OSX so I always have to reinstall argon2 after a deployment so I can work. I was wondering if there is a better way to do this so that elasticbeanstalk always chooses to use the linux binary and locally I don't need to run the npm install script before the deployment?

**Comment by on21life** [comment]
To solve that, the prerequisites must be met, but your code fails in my elasticbeanstalk linux environment.

`npm install argon2--save--target = 12.2.0 --target_arch = x64--target_platform = linux--target_li
bc = glibc
//npm ERR! code EINVALIDTAGNAME
//npm ERR! Invalid tag name "=": Tags may not have any characters that encodeURIComponent encodes.

//npm ERR! A complete log of this run can be found in:
//npm ERR!     /root/.npm/_logs/2022-04-21T07_11_26_767Z-debug.log`

**Comment by ranisalt** [comment]
@rgovindji I know it's been a while, I just released an alpha version under the `next` tag that will not have this issue, as it packages binaries for all architectures supported at once, no install step required.

You can try it by installing `argon2@next` with your preferred package manager, the rest of the library remains the same.

**Comment by ranisalt** [comment]
Should be fixed with v0.40.1
