### ISSUE TITLE
Different Result, if I run argon2i with the same config in python's nacl library

### ISSUE THREAD

**Issue by ihrigb** [ranisalt/node-argon2#314]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [X] Checkout to the latest version, **including submodules**
- [X] Try to find an *isolated* way to reproduce the behavior
- [X] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. Check source code listings below and execute them

### Expected behaviour
I did not reach the expected hash result with argon2i from the node library, while I do with the result in Python's nacl lib. I cannot see any differences in configuration and options. Node source code contains the expected byte array.

### Actual behaviour
See above.

### Environment
**Operating system**: Win 10 and Ubuntu 20.04

**Node version:** 10

**Compiler version:**

Source Codes:
NodeJS Code: https://gist.github.com/ihrigb/a6160003ff63057c69034ea07e17f2e7
Python Code: https://gist.github.com/ihrigb/f3a1415245840326d9fdec18be9ab6e7

**Comment by ranisalt** [comment]
Interesting. I'm trying some local tests to identify the issue.

Just for the record, this is the formatted password generated by node-argon2:

`$argon2i$v=19$m=8192,t=4,p=1$dzU23MMOLoR+DnUp4jRgzw$ax16RBZjPP7n3bFmApiAwXdseI6bA58ldp09zRAIe0I`

**Comment by ihrigb** [comment]
HI @ranisalt, I am not too familiar with argon2 itself. What does the `v` parameter stand for?

**Comment by ranisalt** [comment]
> What does the `v` parameter stand for?

It stands for the version of the algorithm. There were slight changes from the original published version that change the resulting hash, therefore you need to specify what version needs to be used.

0x10 (or 16) means v1.0 and 0x13 (or 19, as the example above) for v1.3

**Comment by ihrigb** [comment]
Can that make any difference in that case?

**Comment by ranisalt** [comment]
> Can that make any difference in that case?

It could make it, but I expect pynacl to use the latest version (1.3) by default, and I checked with both 1.0 and 1.3 and it returns different hashes anyway.

**Comment by ihrigb** [comment]
Any update or idea to this?

**Comment by ihrigb** [comment]
I just tried this in Java using the Bouncycastle lib. Same result as with node-argon2. Could that hint to an issue in the Py lib? See the Gist for what I did.
https://gist.github.com/ihrigb/20cf7e321b1faaa9c39de524756bc28d

**Comment by ranisalt** [comment]
> Could that hint to an issue in the Py lib? See

Yes, if the Python lib is different from the other ones, it might hint that it is using the incorrect parameters. I get the test vectors straight from the `argon2` CLI tool, from the reference implementation, so I'm fairly sure this lib is correct on the output.
