### ISSUE TITLE
node-argon2 version 0.28.2 uses a vulnurable strip-ansi package

### ISSUE THREAD

**Issue by halvors** [ranisalt/node-argon2#317]
### Expected behaviour
node-argon2 should update the strip-ansi package (or the one that depends on it) to a non-vulnerable version.

### Actual behaviour
Dependabot returns the following:

The latest possible version that can be installed is 2.1.1 because of the following conflicting dependencies:

argon2@0.28.2 requires ansi-regex@^2.0.0 via a transitive dependency on strip-ansi@3.0.1
argon2@0.28.2 requires ansi-regex@^3.0.0 via a transitive dependency on strip-ansi@4.0.0

**Comment by ranisalt** [comment]
What versions are vulnerable? I have upgraded all dependencies to the latest versions but it still requires strip-ansi 6.0.0, 3.0.1, 4.0.0 and 5.2.0

**Comment by ranisalt** [comment]
Dependabot is completely wild about this package. It complains about the vulnerability, and when I click to generate a merge request it claims the repo has been fixed already. Rinse and repeat.

**Comment by vimutti77** [comment]
Look like the vulnerable is come from
`@mapbox/node-pre-gyp@1.0.1 > npmlog@5.0.1 > gauge@3.0.0 > strip-ansi@"4.0.0"`

Dependency tree:
```
node_modules/argon2@0.28.2
  > @mapbox/node-pre-gyp@^1.0.1
    > npmlog@^5.0.1
      > gauge@^3.0.0
        > strip-ansi@"^3.0.1 || ^4.0.0"
        > string-width@"^1.0.1 || ^2.0.0",
```

We need to wait for https://github.com/npm/gauge/pull/136 to be merged. Then we need to create a PR for `npmlog` and `@mapbox/node-pre-gyp` to use the new version.

**Comment by darkgl0w** [comment]
Related: https://github.com/chalk/ansi-regex/pull/46

**Comment by mccraveiro** [comment]
@ranisalt It seems to be fixed downstream: https://github.com/mapbox/node-pre-gyp/issues/620
Can we get a new release?

**Comment by ranisalt** [comment]
@mccraveiro we still get the vulnerable versions of ansi-regex due to mocha and standard. I will upgrade the dependencies anyway because there are some unpublished small changes
