### ISSUE TITLE
Move CLI in dedicated package

### ISSUE THREAD

**Issue by julien-f** [ranisalt/node-argon2#32]
To avoid useless dependencies :)
I am planning to do the same with [hashy](https://github.com/julien-f/nodejs-hashy).

See also https://github.com/sindresorhus/ama/issues/17

**Comment by ranisalt** [comment]
Check https://github.com/ranisalt/node-argon2-cli :smile:

**Comment by julien-f** [comment]
Nice!

Thank you :)
