### ISSUE TITLE
Please consider adding FreeBSD support (pre-built packages)

### ISSUE THREAD

**Issue by mike-pt** [ranisalt/node-argon2#320]
Currently there are no prebuild package for FreeBSD, some projects like code-server depend on node-Argon2 so it would be great.

**Comment by mike-pt** [comment]
I tried to follow the README, not super familiar with building with node/npm but I' might be able to help wtith FreeBSD compatibility however I can't get past this:

```
$ CXX=clang npm install argon2
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "argon2" under a package
npm ERR! also called "argon2". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-10-19T12_20_08_217Z-debug.log
```

**Comment by Brooooooklyn** [comment]
@mike-pt maybe you want to try https://github.com/napi-rs/node-rs/tree/main/packages/argon2

**Comment by mike-pt** [comment]
Oh this is great, this is actually a dep in code.server, I will see if I can build it now using the new package.

Many thanks

**Comment by ranisalt** [comment]
There you go! Update to v0.29.1
