### ISSUE TITLE
Issue installing Argon on Windows as a dependency for Directus

### ISSUE THREAD

**Issue by ACHildebrand** [ranisalt/node-argon2#330]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [X] Checkout to the latest version, **including submodules**
- [ ] Try to find an *isolated* way to reproduce the behavior
- [X] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. Attempt to install Directus on a windows machine using NPM
2.
3.

### Expected behaviour
Directus should install with all dependencies

### Actual behaviour
Directus attempts to access a URL that does not exist because you appear to be missing a compiled version of Argon

### Environment
**Operating system**:
Windows
**Node version:**
12.18.0
**Compiler version:**
N/A
**Error Log**
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.28.3/argon2-v0.28.3-napi-v3-win32-ia32-unknown.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for argon2@0.28.3 and node@12.21.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/ranisalt/node-argon2/releases/download/v0.28.3/argon2-v0.28.3-napi-v3-win32-ia32-unknown.tar.gz 
gyp ERR! build error

**Comment by parabirb** [comment]
this doesn't seem like something that'd go in this repo, but you're getting the issue because you're on IA-32. the windows build is x64 only.
