### ISSUE TITLE
npm install argon2 failed! 

### ISSUE THREAD

**Issue by liuyang3688** [ranisalt/node-argon2#345]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [√] Checkout to the latest version, **including submodules**
- [√] Try to find an *isolated* way to reproduce the behavior
- [√] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. npm install argon2

### Expected behaviour
successfully installed

### Actual behaviour

> E:\ruilang\qserver>npm install argon2 -g
> npm ERR! code 1
> npm ERR! path D:\nodejs\node_global\node_modules\argon2
> npm ERR! command failed
> npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp info using node-gyp@9.0.0
> npm ERR! gyp info using node@16.14.2 | win32 | x64
> npm ERR! gyp info find Python using Python version 3.8.0 found at "E:\Devenv\Python\Python38\python.exe"
> npm ERR! gyp info find VS using VS2022 (17.1.32421.90) found at:
> npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
> npm ERR! gyp info find VS run with --verbose for detailed information
> npm ERR! gyp info spawn E:\Devenv\Python\Python38\python.exe
> npm ERR! gyp info spawn args [
> npm ERR! gyp info spawn args   'D:\\nodejs\\node_global\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
> npm ERR! gyp info spawn args   'binding.gyp',
> npm ERR! gyp info spawn args   '-f',
> npm ERR! gyp info spawn args   'msvs',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   'D:\\nodejs\\node_global\\node_modules\\argon2\\build\\config.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   'D:\\nodejs\\node_global\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\16.14.2\\include\\node\\common.gypi',
> npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
> npm ERR! gyp info spawn args   '-Dvisibility=default',
> npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\16.14.2',
> npm ERR! gyp info spawn args   '-Dnode_gyp_dir=D:\\nodejs\\node_global\\node_modules\\npm\\node_modules\\node-gyp',
> npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Administrator\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.14.2\\\\<(target_arch)\\\\node.lib',
> npm ERR! gyp info spawn args   '-Dmodule_root_dir=D:\\nodejs\\node_global\\node_modules\\argon2',
> npm ERR! gyp info spawn args   '-Dnode_engine=v8',
> npm ERR! gyp info spawn args   '--depth=.',
> npm ERR! gyp info spawn args   '--no-parallel',
> npm ERR! gyp info spawn args   '--generator-output',
> npm ERR! gyp info spawn args   'D:\\nodejs\\node_global\\node_modules\\argon2\\build',
> npm ERR! gyp info spawn args   '-Goutput_dir=.'
> npm ERR! gyp info spawn args ]
> npm ERR! gyp: Undefined variable module_name in binding.gyp while trying to load binding.gyp
> npm ERR! gyp ERR! configure error
> npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
> npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (D:\nodejs\node_global\node_modules\npm\node_modules\node-gyp\lib\configure.js:261:16)
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
> npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
> npm ERR! gyp ERR! System Windows_NT 10.0.19043
> npm ERR! gyp ERR! command "E:\\Devenv\\nodejs\\node.exe" "D:\\nodejs\\node_global\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> npm ERR! gyp ERR! cwd D:\nodejs\node_global\node_modules\argon2
> npm ERR! gyp ERR! node -v v16.14.2
> npm ERR! gyp ERR! node-gyp -v v9.0.0
> npm ERR! gyp ERR! not ok

### Environment
**Operating system**:
Win10

**Node version:**
16.14.2

**Compiler version:**
node-gyp: v9.0.0

**Comment by liuyang3688** [comment]
> Undefined variable module_name in binding.gyp while trying to load binding.gyp

**Comment by asferreira** [comment]
Same problem on FreeBSD 13.1 and node 16

**Comment by gunwd** [comment]
I'm getting an error when installing argon2 as well, on Ubuntu 22.04. Although I'm not sure if it's the same error.

Here's the debug log:
```
483 verbose stack Error: command failed
483 verbose stack     at ChildProcess.<anonymous> (/snap/node/6378/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
483 verbose stack     at ChildProcess.emit (node:events:527:28)
483 verbose stack     at maybeClose (node:internal/child_process:1092:16)
483 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
484 verbose pkgid argon2@0.28.5
485 verbose cwd /home/test/test
486 verbose Linux 5.15.0-37-generic
487 verbose node v16.15.1
488 verbose npm  v8.11.0
489 error code 1
490 error path /home/test/node_modules/argon2
491 error command failed
492 error command sh -c node-pre-gyp install --fallback-to-build
493 verbose exit 1
```

**Comment by ranisalt** [comment]
@gunwd the useful information on the debug log is what comes before the "command failed" line, can you please share that as well?

**Comment by HaKePlan** [comment]
@gunwd do you use nodejs from snap? I had the same problem once with a nodejs from snap. After I installed nodejs as a binary, it worked perfectly fine. Snap has some permission problems with some packages...

**Comment by gunwd** [comment]
> @gunwd do you use nodejs from snap? I had the same problem once with a nodejs from snap. After I installed nodejs as a binary, it worked perfectly fine. Snap has some permission problems with some packages...

Exactly what you said! Apologies for not writing an update — I wanted to figure out why Snap causes the problem since it doesn’t sandbox Node itself.

Will probably open an issue there if this is a bug and not a feature. 😂

**Comment by ranisalt** [comment]
> Will probably open an issue there if this is a bug and not a feature. joy

It is not :laughing: do you mind adding that to the README?

**Comment by VityaSchel** [comment]
For some reason it keeps happening with pnpm on macos

**Comment by ranisalt** [comment]
> For some reason it keeps happening with pnpm on macos

Can you create a new issue? Make sure to include as much info about your machine as possible

**Comment by nealoke** [comment]
I had the same error as the OP, my issue was that even though I switched to the correct node version with `nvm use 24.7.0` VS Code was somehow [caching the default](https://stackoverflow.com/a/70087862). 

**How to fix**
1. Run `nvm alias default 24.7.0`
2. Reload VS Code window
3. Double check that if you open a new terminal you are in fact on the default we set earlier (`nvm list`)

From this point onwards you can simply run `npm install` without issues.
