### ISSUE TITLE
Something that was just hashed fails verification

### ISSUE THREAD

**Issue by yeetsquad747** [ranisalt/node-argon2#347]
### What happens
I am working with node-argon to hash passwords for an app. The hashing functionality works fine but the verification doesn't work. When I tried to verify the password(that was password) with the hash `$argon2i$v=19$m=4096,t=3,p=1$1fgte9sjad6bWS+V8LMMlg$IFyWws6nEPZMlIt0c1p/6VfghpHWnKnFulS43Y13INw`, it said that they aren't the same.

### Environment
**Operating system**: Ubuntu 22.04 Desktop

**Node version:** v18.3.0

### Code
**Verification code**
```
  const body = req.body;
  let user = await UserModel.findOne({
    username: body["username"],
  });
  if (!user) {
    return res.status(401).send({
        status: 401,
        message: `Username ${body.username} not recognized`
    })
  } else if (await argon.verify(user.password, body.password)) {
    return res.status(200).send({
      status: 200,
      message: `Successfully logged in to ${body.username}.`,
    });
  }
  res.status(401).send({
    status: 401,
    message: `Incorrect login details. You are not signed in to ${body.username}.`,
  });
```

**Comment by ranisalt** [comment]
Could you also share the code where you hash the password initially?

**Comment by yeetsquad747** [comment]
No it was just me screwing up(I hashed the passwords surrounded by the JSON.stringify() function). Sorry for wasting your time.

**Comment by ranisalt** [comment]
It happens! No worries;
