### ISSUE TITLE
Provide timing/enumeration attack safe .verify()

### ISSUE THREAD

**Issue by xbjfk** [ranisalt/node-argon2#352]
Hi,
I was wondering if there was any possible way to use .verify() in a timing safe way that prevents enumeration attacks?
As in, if the 1st argument is null, the second argument is still hashed and then the function returns false. This way, no user's salt can be provided if the user is invalid, and the same time will be taken to say "invalid username/password combo" as if the user did exist

**Comment by ranisalt** [comment]
The hash comparison, in case a valid hash and a password were provided, is done in a timing safe way using [`crypto.timingSafeEqual`](https://nodejs.org/api/crypto.html#cryptotimingsafeequala-b)

However, if the hash is invalid (i.e. it does not start with `$argon2`), it will return as soon as possible. That case would only happen if you are taking invalid hashes from your database, or something like that. The user input does not matter at all, the verification is time-safe for any user input.

Is this what you have in mind?

**Comment by xbjfk** [comment]
In mind I was thinking what if the user provides an invalid username. It is common practice to not allow the frontend to show whether the username was invalid or the password hash didn't match, and a key part of this is taking the same amount of time whether the user exists or not.

**Comment by ranisalt** [comment]
@xbjfk in that case, you can coalesce the hash to a known hash of an empty string. If you don't allow empty passwords, the verification will always fail in constant time.

To do that, just hash `""` with your default parameters. You can either use a static constant hash, or generate a new value every time you start the server, so it will always be updated if you change params. Then, coalesce the hashed password to this known constant when it is null, e.g. `argon2.verify(user.password || INVALID_HASH, plaintext)`

**Comment by xbjfk** [comment]
Thanks, this seems really obvious in hindsight
