### ISSUE TITLE
Adding pepper

### ISSUE THREAD

**Issue by ahkhanjani** [ranisalt/node-argon2#354]
How can we add pepper?
The binaries apparently don't support it. Can we implement a pre-argon pepper hashing or will it be simply useless without the core support?

**Comment by ranisalt** [comment]
You can use `secret`, pass a `Buffer` and it will be included in the password hash. That feature is missing from the docs, but you can see the implementation in #241

**Comment by ahkhanjani** [comment]
I was wondering about secret missing in the docs. Shall we add it?

**Comment by ahkhanjani** [comment]
Hey,hope you're doing well.
It's been a while since I opened this. Should it stay open?

**Comment by ranisalt** [comment]
I don't think so, it has been [added to the wiki](https://github.com/ranisalt/node-argon2/wiki/Options#secret)
