### ISSUE TITLE
`.node` files not working.

### ISSUE THREAD

**Issue by Jacrispys** [ranisalt/node-argon2#355]
### Before creating an issue, please be sure to:
- [x] Checkout to the latest version, **including submodules**
- [x] Try to find an *isolated* way to reproduce the behavior
- [x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. Make a sveltekit project
2. npm install argon2 into the project
3. add argon2 import and run vite dev

### Expected behaviour
The project should just open in a dev environement but instead I get an error in console and the page  does not render

### Environment
**Operating system**:
Windows 10
**Node version:**
18.7
**Compiler version:**
UNKNOWN (Not sure where to check, but its a fresh version of vite for the build).

###Full Error Here:

```txt
Error: Build failed with 1 error:
node_modules/argon2/argon2.js:6:32: ERROR: No loader is configured for ".node" files: node_modules/argon2/lib/binding/napi-v3/argon2.node
    at failureErrorWithLog (C:\Users\jvanz\OneDrive\Desktop\NGTB-Web\NGTB-Web\node_modules\esbuild\lib\main.js:1621:15)
    at C:\Users\jvanz\OneDrive\Desktop\NGTB-Web\NGTB-Web\node_modules\esbuild\lib\main.js:1263:28
    at runOnEndCallbacks (C:\Users\jvanz\OneDrive\Desktop\NGTB-Web\NGTB-Web\node_modules\esbuild\lib\main.js:1043:63)
    at buildResponseToResult (C:\Users\jvanz\OneDrive\Desktop\NGTB-Web\NGTB-Web\node_modules\esbuild\lib\main.js:1261:7)
    at C:\Users\jvanz\OneDrive\Desktop\NGTB-Web\NGTB-Web\node_modules\esbuild\lib\main.js:1374:14
    at C:\Users\jvanz\OneDrive\Desktop\NGTB-Web\NGTB-Web\node_modules\esbuild\lib\main.js:675:9
    at handleIncomingPacket (C:\Users\jvanz\OneDrive\Desktop\NGTB-Web\NGTB-Web\node_modules\esbuild\lib\main.js:772:9)
    at Socket.readFromStdout (C:\Users\jvanz\OneDrive\Desktop\NGTB-Web\NGTB-Web\node_modules\esbuild\lib\main.js:641:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 32,
        file: 'node_modules/argon2/argon2.js',
        length: 35,
        line: 6,
        lineText: 'const { hash: _hash } = require("./lib/binding/napi-v3/argon2.node");',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No loader is configured for ".node" files: node_modules/argon2/lib/binding/napi-v3/argon2.node'
    }
  ],
  warnings: []
}

Node.js v18.7.0
```

**Comment by ranisalt** [comment]
This package will not run on the browser, therefore, it will not support any bundlers. You can only use node-argon2 with Node.

Mind if I ask what are you planning to do with Argon2? Usage in the browser is most of the time incorrect :P

**Comment by Jacrispys** [comment]
I used the Java bindings for another web project and had it run in the backend for password encryption, I planned on doing the same thing here with node making use of sveltekit, I am pretty new to web-dev/svelte though since I mainly work on compiled languages, but the point is I'm just trying to use it as a node-module with svelte kit.

**Comment by ranisalt** [comment]
You won't be able to do that, you can't have node-argon2 in your frontend imports, because it can't run in the browser.

If you have a backend server i.e. an API, then you can import and use node-argon2 there.

Let me know if I can help you with anything!

**Comment by Jacrispys** [comment]
Oh ok, thinking a bit deeper that makes sense why it has to work like that haha, I'll work on setting up a back end and will reopen this issue if I need any help!

**Comment by dacarley** [comment]
I just hit this with a project using the Serverless Framework, and the `serverless-esbuild` plugin.  The solution was to mark `argon2` as external in serverless.yml:

```yaml
custom:
  esbuild:
    external:
      - argon2
```
