### ISSUE TITLE
macos in GH Actions CI: no suitable image found

### ISSUE THREAD

**Issue by jsjoeio** [ranisalt/node-argon2#356]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [ ] Checkout to the latest version, **including submodules**
- [ ] Try to find an *isolated* way to reproduce the behavior
- [x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. `git clone https://github.com/jsjoeio/code-server.git`
2. `git checkout `jsjoeio/refactor-workflows`
3. Push to GitHub > Enable Actions
4. Open PR > watch `x86-64 macOS build` job fail

### Expected behaviour

"Run integration tests on standalone release" aka `yarn test:integration` should pass.

### Actual behaviour

They fail due to a node-argon error:

https://github.com/coder/code-server/actions/runs/3093663725/jobs/5006319517#step:10:15

```js
dlopen(/Users/runner/work/code-server/code-server/node_modules/argon2/lib/binding/napi-v3/argon2.node, 1): no suitable image found.  Did find:
    	/Users/runner/work/code-server/code-server/node_modules/argon2/lib/binding/napi-v3/argon2.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
    	/Users/runner/work/code-server/code-server/node_modules/argon2/lib/binding/napi-v3/argon2.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

### Environment
**Operating system**: `macos-latest` (GitHub CI)

**Node version:** 16

**Compiler version:** unsure

### Notes

I know this is probably specific to my project but wasn't sure where else to seek help!

**Comment by ranisalt** [comment]
This is odd, we definitely build for MacOS, could it be the case that you were downloading the package in a different system than you were executing? i.e. somehow ran `yarn install` in Ubuntu and then ran your tests on Mac without a new install

**Comment by jsjoeio** [comment]
Yes! That was it. We were running in Ubuntu, caching and then using those `node_modules` on macOS. Sorry for the noise!

**Comment by ranisalt** [comment]
@jsjoeio np, it happens more often than we'd like :laughing:
