### ISSUE TITLE
Wrong remote binary path break down mirror.

### ISSUE THREAD

**Issue by abcfy2** [ranisalt/node-argon2#370]
Since v0.30.1 commit: https://github.com/ranisalt/node-argon2/commit/335127423065ed02a05f13dc5a7fdabda4e4857e 

The binary mirror not working anymore.

```sh
npm_config_argon2_binary_host_mirror=https://cdn.npmmirror.com/binaries/argon2 npm i -dd argon2
```

Please revert remote host & path to the old version to fix mirror working. Thanks.

The prebuilt download URL should replace to `https://cdn.npmmirror.com/binaries/argon2/v0.30.3/argon2-v0.30.3-napi-v3-linux-x64-glibc.tar.gz`

A working example can referrer to sqlite3: https://github.com/TryGhost/node-sqlite3/blob/c1440bdaa47ffdda852ff576ac543114c4f0fb4b/package.json#L10-L20

**Comment by ranisalt** [comment]
How did you find that exact commit is the culprit?

[bcrypt](https://github.com/kelektiv/node.bcrypt.js/blob/11d2ddd185c163314bd91754c5803002d929b4ff/package.json#L62) and [libxmljs](https://github.com/libxmljs/libxmljs/blob/23da4cf9eca569a37cc36a26977fa7ab0b53d875/package.json#L11) use the same pattern as this repo with no issues. [odbc](https://github.com/markdirish/node-odbc/blob/7a97292b0dcd37553f8d99b8315561d5ce3dc69c/package.json#L56) uses yet another one.

**Comment by abcfy2** [comment]
I used the old version before, and the mirror is working. But when I upgrade to the new version, the mirror no longer work.

And I find the wrong `binary.host` config in package.json, So I just find this file commit history, then I find it.

**Comment by abcfy2** [comment]
From node-pre-gyp source code: https://github.com/mapbox/node-pre-gyp/blob/master/lib/util/versioning.js#L316

```js
const host = process.env['npm_config_' + validModuleName + '_binary_host_mirror'] || package_json.binary.host;
```
download host can be override by environment variable `npm_config_<module_name>_binary_host_mirror`.

And from this file, we know download url is merged by host + remote_path + package_name.

Only host can be override by environment `npm_config_<module_name>_binary_host_mirror`. So to make the mirror could work, we can't set `{version}` in `host` field. So your old code is correct:

```json
  "binary": {
    "module_name": "argon2",
    "module_path": "./lib/binding/napi-v{napi_build_version}",
    "host": "https://github.com/ranisalt/node-argon2/releases/download/",
    "remote_path": "v{version}",
    "package_name": "{module_name}-v{version}-napi-v{napi_build_version}-{platform}-{arch}-{libc}.tar.gz",
    "napi_versions": [
      3
    ]
  },
```

And here is the npmmirror.com files list: https://registry.npmmirror.com/binary.html?path=argon2/

**Comment by ranisalt** [comment]
Interesting. Not really an issue in this repo though, but rather a naming issue with this value which is not the `host` but something else.

I'm out of my PC right now, if you can open a PR I'll accept it right away, otherwise I can do it a little later.

**Comment by abcfy2** [comment]
Got it, and here is the PR: https://github.com/ranisalt/node-argon2/pull/371
