### ISSUE TITLE
Module parse failed: Unexpected token (1:0)

### ISSUE THREAD

**Issue by PixelPage-YT** [ranisalt/node-argon2#372]
Heyy, i need some help with the library:

### Steps to reproduce
1. Create a NextJS 13 app and use the app directory
2. Add Argon2 using `yarn add argon2`
3. Import it and use it in an API route
4. Make a request to the api route

### Expected behaviour
The hash will be created.

### Actual behaviour
I get this error: 
```
error - ./node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!doctype html>
| <html>
| <head>

Import trace for requested module:
./node_modules/@mapbox/node-pre-gyp/lib/util/nw-pre-gyp/index.html
./node_modules/@mapbox/node-pre-gyp/lib/ sync ^\.\/.*$
./node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js
./node_modules/argon2/argon2.js
./src/app/api/auth/signup/route.ts
```

### Environment
**Operating system**: MacOs 13.1

**Node version:** v16.15.0

**Argon2 version:** ^0.30.3

Thanks in advance :)

**Comment by ranisalt** [comment]
You will have to add `argon2` to externals, see https://github.com/ranisalt/node-argon2/issues/261#issuecomment-639392195

It will require a custom webpack configuration, check [Next.js documentation on that](https://nextjs.org/docs/api-reference/next.config.js/custom-webpack-config)

**Comment by PixelPage-YT** [comment]
Thank you, but it still doesn't work.
```
/** @type {import('next').NextConfig} */
const nextConfig = {
    experimental: {
        appDir: true,
    },
    webpack: (
        config,
        { buildId, dev, isServer, defaultLoaders, nextRuntime, webpack }
    ) => {
        config.externals.argon2 = "argon2";
        // Important: return the modified config
        return config;
    },
};

module.exports = nextConfig;
```
