### ISSUE TITLE
Outdated wiki: Missing documentation for secret property for options parameter

### ISSUE THREAD

**Issue by DewZ89** [ranisalt/node-argon2#377]
### Steps to reproduce
1. Go to [Options docs](https://github.com/ranisalt/node-argon2/wiki/Options)
2. Look for secret property doc

### Expected behaviour
Find documentation about secret parameter

### Actual behaviour
No documentation related to it

### Environment
**Operating system**:
N/A

**Node version:**
N/A

**Compiler version:**
N/A

**Comment by DewZ89** [comment]
Hi @ranisalt, maybe we could add it?

**Comment by ranisalt** [comment]
@DewZ89 yes, definitely!

**Comment by ranisalt** [comment]
Added a section for `secret` in the wiki:

https://github.com/ranisalt/node-argon2/wiki/Options#secret

**Comment by DewZ89** [comment]
Hi @ranisalt,
i did not saw your answer in time.
