### ISSUE TITLE
Module not found: Can't resolve 'child_process'

### ISSUE THREAD

**Issue by GefeiSHEN** [ranisalt/node-argon2#378]
### Steps to reproduce
1. Start a fresh Next.js project, npm install argon2
2. import * as argon2 from "argon2";
3. call argon2.hash("Hello") function.
4. run `npx next dev`

### Expected behaviour
The process should run without errors. 

### Actual behaviour

```
./node_modules/@mapbox/node-pre-gyp/lib/testbinary.js:9:0
Module not found: Can't resolve 'child_process'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@mapbox/node-pre-gyp/lib/ sync ^\.\/.*$
./node_modules/@mapbox/node-pre-gyp/lib/node-pre-gyp.js
./node_modules/argon2/argon2.js
./pages/auth.tsx
```

### Environment
**Operating system**: MacOS 13.3.1 (a) 

**Node version:** 19.7.0

**Compiler version:**  10.8.168.25-node.11

### Comment
I tried to disable child_process with the following code in `package.json` but it was unsuccessful, more errors pop up.
```
  "browser":{
    "child_process": false
  }
```

**Comment by ranisalt** [comment]
node-argon2 does not run in the browser. You need to make sure the call to `hash(...)` is performed on the server side, i.e. either in an API handler or in `getServerSideProps`.
