### ISSUE TITLE
documentation on ES7 Verify example is wrong/misleading

### ISSUE THREAD

**Issue by DiknT** [ranisalt/node-argon2#38]
the documentation on ES7 verify function states that promise is rejected if passwords do not match. but instead the catch block is only called if an error occurs during the verify call itself, e.g. wrong parameters:
```
async function verify () {
  try {
    await argon2.verify('<big long hash>', 'password');
    // password match
    return true // should only be called if passwords match
  } catch (err) {
    // password did not match
    return false // should be returned for password mismatch or error during verify call
  }
}
```
Instead with above setup 'true' is always returned, regardless if password match or not. The correct way would be to return the result of argon2.verify().

### Environment
**Operating system**:
OS X 10.11.4
**Node version:**
5.10.1
**Compiler version:**
g++5

**Comment by ranisalt** [comment]
Yeah, really didn't see it. `argon2.verify` with `await` returns true if the password matches, false if it does not match, and throws when a failure happens (memory corruption, allocation error, etc). Could you write a PR or may I do it?

**Comment by DiknT** [comment]
Please do it, thank you for this work.
