### ISSUE TITLE
Vulnerable downstream dependency

### ISSUE THREAD

**Issue by jdforsythe** [ranisalt/node-argon2#381]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [ ] Checkout to the latest version, **including submodules**
- [ ] Try to find an *isolated* way to reproduce the behavior
- [ ] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

```sh
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ semver vulnerable to Regular Expression Denial of Service    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ semver                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=7.5.2                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ argon2                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ argon2 > @mapbox/node-pre-gyp > make-dir > semver            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://www.npmjs.com/advisories/1092310                     │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

### Environment
**Operating system**:

**Node version:**

**Compiler version:**

**Comment by AkiraMiyakoda** [comment]
We're waiting for `@mapbox/node-pre-gyp` to update its dependency. (https://github.com/mapbox/node-pre-gyp/issues/685)
`make-dir` has already been updated, so you can add this to your `package.json` as an interim measure.
```json
"overrides": {
  "make-dir": "^4.0.0"
}
```

**Comment by jdforsythe** [comment]
@AkiraMiyakoda `@mapbox/node-pre-gyp` v1.0.11 was just published with the fix

**Comment by ranisalt** [comment]
Feel free to open a PR updating the dependency before dependabot does it :)

**Comment by jdforsythe** [comment]
> Feel free to open a PR updating the dependency before dependabot does it :)

Done. #383

**Comment by jdforsythe** [comment]
@ranisalt is there an upcoming release that will contain this change?

**Comment by ranisalt** [comment]
@jdforsythe releasing v0.31.0 with updated dependencies now.
