### ISSUE TITLE
how to install with local argon2.node

### ISSUE THREAD

**Issue by honger502** [ranisalt/node-argon2#391]
I am donwlaod argon2-v0.31.1-napi-v3-darwin-x64-unknown.tar.gz and tar it first.

then, edit package.json in my project
```js
"argon2": {
  "path": "./argon2.node"
}
```

it doesn't work

**Comment by ranisalt** [comment]
I am not familiar with what you're trying to do, that's not how Node works. I suggest reading up about [how package.json works](https://docs.npmjs.com/cli/v10/configuring-npm/package-json) before anything else.
