### ISSUE TITLE
How to hash without salt?

### ISSUE THREAD

**Issue by VityaSchel** [ranisalt/node-argon2#394]
I really need to hash without salt (https://docs.oxen.io/oxen-docs/products-built-on-oxen/session/loki-name-system-for-session) and by that I mean salt that is equal to 0 bytes
but when I try saltLength: 0 or salt: Buffer.alloc(0), argon2 throws `[Error: Salt is too short]`

**Comment by ranisalt** [comment]
You can't, [Argon2 does not support hashing without salt](https://datatracker.ietf.org/doc/html/rfc9106#name-argon2-inputs-and-outputs). The implementation of Argon2 expected in this document is not compliant [with the reference one](https://github.com/P-H-C/phc-winner-argon2/blob/master/src/core.c#L421-L434)
