### ISSUE TITLE
Mismatching version numbers on github releases and npm (0.40.0 vs 0.40.1)

### ISSUE THREAD

**Issue by pnappa** [ranisalt/node-argon2#399]
Hi, not sure if this is intentional or not, but I notice that the latest version on npm is 0.40.1, whilst the github releases page has 0.40.0.

See 
https://www.npmjs.com/package/argon2?activeTab=versions
and
https://github.com/ranisalt/node-argon2/releases/tag/v0.40.0

They both were released on the same day, so it looks like it may have been a mistake/consequence of the alpha versioning?

**Comment by ranisalt** [comment]
It is intentional, exactly what you said. It happened because NPM won't let me publish `0.40.0` because semver considers `0.40.0` to be lower than `0.40.0-alphaN`, so I had to bump patch version. Next release should be 0.40.2 or 0.41.0 and will resync between Github and NPM

**Comment by pnappa** [comment]
Alright cool! Cheers
