### ISSUE TITLE
Documentation: npm readme out of date

### ISSUE THREAD

**Issue by abh1nav** [ranisalt/node-argon2#40]
It looks like the docs on npm aren't synced with the readme in master. Specifically, the `verify` method's `match` parameter explanation (which could lead to some serious security holes if followed as per the docs on npm). This seems to have been fixed in master around the same time as the last NPM release, so maybe something went wrong while pushing to npm?

**Comment by ranisalt** [comment]
I accidentally pushed an update to the repo and didn't publish to npm. v0.11.1 fixes this issue and is already on npm.

**Comment by abh1nav** [comment]
Awesome. Thanks! ✌️
