### ISSUE TITLE
node-gyp-build error

### ISSUE THREAD

**Issue by DataBase137** [ranisalt/node-argon2#400]
### Steps to reproduce
1. Make a new nextjs app with create-next-app (with typescript)
2. Install argon2, and create a middleware.ts file
3. Use argon2 in the middleware or have it directly linked

### Error
It spits an error about having "node:" before crypto and a couple other things in the module file:

node:crypto
Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:crypto
./node_modules/argon2/argon2.cjs

If you go to the module file and remove "node:" then it is fine (you must delete the .next folder and have it regenerated), but it again spits an error about node-gyp-build:

⨯ node_modules\node-gyp-build\node-gyp-build.js (10:0) @ <unknown>
⨯ Cannot read properties of undefined (reading 'modules')

If I go into the node-gyp-build.js file, on line 10 (which was specified in the error), here is the line of code:

var abi = process.versions.modules // TODO: support old node where this is undef

Notice the TODO comment. I don't have an old version of node though.

### Environment
I'm using node version 21.7.1 (latest), but i have tried with versions down to 18.7 (before that nextjs doesnt work). I'm also using argon2 version 0.40.1 (latest). I have tried to use argon2 in a vanilla js file and it works perfectly fine without either errors shown above. I'm wondering if maybe it has a problem with the edge function because the middleware.ts file runs on the edge.

**Comment by ranisalt** [comment]
Did you get it fixed somehow? I don't think argon2 will work properly on edge functions due to their nature.

**Comment by DataBase137** [comment]
No, I wasn't able to solve the problem, I think it just doesn't work with the edge runtime.

**Comment by MrOxMasTer** [comment]
> No, I wasn't able to solve the problem, I think it just doesn't work with the edge runtime.

It doesn't work fine in the docker container either.
![image](https://github.com/ranisalt/node-argon2/assets/59291123/624912c2-f7c9-456d-b041-62ed76287c64)

**Comment by pulgueta** [comment]
I get this error when loading a page with Next.js 14.2.3 (no edge routes/pages and no middleware). Package is set under serverComponentExternalPackages experimental flag in next.config.mjs. Have you guys found a solution for this?
