### ISSUE TITLE
Doesn't work in the node:20-alpine image docker

### ISSUE THREAD

**Issue by MrOxMasTer** [ranisalt/node-argon2#402]
Welcome to the issues section if it's your first time!

### Before creating an issue, please be sure to:
- [x] Checkout to the latest version, **including submodules**
- [x] Try to find an *isolated* way to reproduce the behavior
- [x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. Install the argon2 package on the node:20-alpine image
2. try to use it
3. Receive an error

![image](https://github.com/ranisalt/node-argon2/assets/59291123/8a20b0ad-7f5d-4e82-8917-f6819902c2ee)

It says from 3.18 the binary files are there and on later versions should work. No, it doesn't work on 3.19

![image](https://github.com/ranisalt/node-argon2/assets/59291123/900cd61e-3e9e-4987-a236-31fc4a330545)
tried to compile and it still doesn't work

### Expected behaviour
work

### Actual behaviour
Causes an error

### Environment
**Operating system**:
Windows 11

**Node version:**
node:20.12.2

**Comment by MrOxMasTer** [comment]
https://github.com/prebuild/node-gyp-build/issues/53

**Comment by MrOxMasTer** [comment]
alpine3.18-3.19 don't work

**Comment by ranisalt** [comment]
Can you share a minimal Dockerfile + package.json that triggers this issue?

**Comment by MrOxMasTer** [comment]
> Can you share a minimal Dockerfile + package.json that triggers this issue?

```json
{
  "name": "shopco",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "migration:generate": "drizzle-kit generate:pg",
    "migration:push": "drizzle-kit push:pg",
    "studio": "drizzle-kit studio --host 127.0.0.1",
    "build:icons": "npx tsx ./build-icons.mts",
    "sly": "pnpm dlx @sly-cli/sly add"
  },
  "dependencies": {
    "@auth/drizzle-adapter": "^0.8.0",
    "@hookform/resolvers": "^3.3.4",
    "@radix-ui/react-dialog": "^1.0.5",
    "@radix-ui/react-slot": "^1.0.2",
    "@t3-oss/env-nextjs": "^0.9.2",
    "argon2": "^0.40.1",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.0",
    "drizzle-orm": "^0.30.2",
    "drizzle-zod": "^0.5.1",
    "embla-carousel-autoplay": "8.0.0-rc17",
    "embla-carousel-react": "8.0.0-rc17",
    "ky": "^1.2.2",
    "nanoid": "^5.0.6",
    "next": "14.2.1",
    "next-auth": "5.0.0-beta.16",
    "next-themes": "^0.3.0",
    "pg": "^8.11.3",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-focus-lock": "^2.11.2",
    "react-hook-form": "^7.51.2",
    "redis": "^4.6.13",
    "server-only": "^0.0.1",
    "sharp": "^0.33.2",
    "sonner": "^1.4.3",
    "tailwind-merge": "^2.2.1",
    "tailwindcss-animate": "^1.0.7",
    "zod": "^3.22.4",
    "zustand": "^4.5.2"
  },
  "devDependencies": {
    "@conarti/eslint-plugin-feature-sliced": "^1.0.5",
    "@sly-cli/sly": "^1.10.0",
    "@types/fs-extra": "^11.0.4",
    "@types/node": "^20.11.28",
    "@types/pg": "^8.11.2",
    "@types/react": "^18.2.66",
    "@types/react-dom": "^18.2.22",
    "@typescript-eslint/eslint-plugin": "^6.21.0",
    "@typescript-eslint/parser": "^6.21.0",
    "autoprefixer": "^10.4.18",
    "cssnano": "^6.1.0",
    "drizzle-kit": "^0.20.14",
    "eslint": "^8.57.0",
    "eslint-config-next": "14.1.3",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-drizzle": "^0.2.3",
    "eslint-plugin-import": "^2.29.1",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-tailwindcss": "^3.14.3",
    "fs-extra": "^11.2.0",
    "glob": "^10.3.10",
    "jiti": "^1.21.0",
    "lucide-react": "^0.303.0",
    "node-html-parser": "^6.1.12",
    "postcss": "^8.4.35",
    "postcss-flexbugs-fixes": "^5.0.2",
    "postcss-preset-env": "^9.4.0",
    "prettier": "^3.2.5",
    "prettier-plugin-tailwindcss": "^0.5.12",
    "react-devtools": "^5.0.2",
    "stylelint": "^16.3.0",
    "stylelint-config-standard": "^36.0.0",
    "stylelint-order": "^6.0.4",
    "stylelint-selector-bem-pattern": "^4.0.0",
    "svgo": "^3.2.0",
    "tailwindcss": "^3.4.1",
    "tailwindcss-debug-screens": "^2.2.1",
    "typescript": "^5.4.2"
  }
}
```
```Dockerfile
FROM node:20-alpine3.18 AS base

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json pnpm-lock.yaml* yarn.lock* package-lock.json* ./
RUN \
  if [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
  elif [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  else echo "Lockfile not found." && exit 1; \
  fi

# RUN apk add build-base
# RUN gcc -v
RUN npm i -g node-gyp
RUN pnpm i argon2

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN \
  if [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
  elif [ -f yarn.lock ]; then yarn run build; \
  elif [ -f package-lock.json ]; then npm run build; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
CMD HOSTNAME="0.0.0.0" node server.js

```

**Comment by ranisalt** [comment]
You seem to be using Next.js standalone mode, which notably fails to find anything that's not explicitly required when building - since the argon2 module needs to dynamically choose the binary, it fails to get picked.

You likely need to use [outputFileTracingIncludes](https://nextjs.org/docs/pages/api-reference/next-config-js/output#caveats) in one of your endpoints to include `./node_modules/argon2/**` or just copy the entire `node_modules/argon2` folder to the `runner` image

**Comment by MrOxMasTer** [comment]
> Owner


Tried to add for all pages and this is what came out

```js
experimental: {
    outputFileTracingIncludes: {
      '/': ['./node_modules/argon2/**'],
    },
  }
```

```bash
frontend  |  ⨯ Error: Cannot find module '@phc/format'
frontend  | Require stack:
frontend  | - /app/node_modules/argon2/argon2.cjs
frontend  | - /app/.next/server/app/(main)/auth/page.js
frontend  | - /app/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require.js
frontend  | - /app/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/next-server.js
frontend  | - /app/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/next.js
frontend  | - /app/server.js
frontend  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1143:15)
frontend  |     at /app/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:55:36
frontend  |     at Module._load (node:internal/modules/cjs/loader:984:27)
frontend  |     at Module.require (node:internal/modules/cjs/loader:1231:19)
frontend  |     at mod.require (/app/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require-hook.js:65:28)
frontend  |     at require (node:internal/modules/helpers:179:18)
frontend  |     at Object.<anonymous> (/app/node_modules/argon2/argon2.cjs:4:36)
frontend  |     at Module._compile (node:internal/modules/cjs/loader:1369:14)
frontend  |     at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
frontend  |     at Module.load (node:internal/modules/cjs/loader:1206:32) {
frontend  |   code: 'MODULE_NOT_FOUND',
frontend  |   requireStack: [
frontend  |     '/app/node_modules/argon2/argon2.cjs',
frontend  |     '/app/.next/server/app/(main)/auth/page.js',
frontend  |     '/app/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/require.js',
frontend  |     '/app/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/next-server.js',
frontend  |     '/app/node_modules/.pnpm/next@14.2.1_react-dom@18.2.0_react@18.2.0__react@18.2.0/node_modules/next/dist/server/next.js',
frontend  |     '/app/server.js'
frontend  |   ]
frontend  | }
```

I'm gonna try to copy the folder

**Comment by MrOxMasTer** [comment]
Could this problem be due to the use of pnpm? It's just that it creates symbolic links and it's weird to copy a folder into the runner 
![image](https://github.com/ranisalt/node-argon2/assets/59291123/7acf75de-4a40-482d-a3c8-39611137395d)

**Comment by MrOxMasTer** [comment]
maybe make some "argon2.config.js" that describes the binaries that will be included in the final build? Or create your own argon2 instance with the configuration in it

**Comment by MrOxMasTer** [comment]
> Could this problem be due to the use of pnpm? It's just that it creates symbolic links and it's weird to copy a folder into the ```runner``` ![image](https://private-user-images.githubusercontent.com/59291123/323253723-7acf75de-4a40-482d-a3c8-39611137395d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjQ3ODQsIm5iZiI6MTcxMzM2NDQ4NCwicGF0aCI6Ii81OTI5MTEyMy8zMjMyNTM3MjMtN2FjZjc1ZGUtNGE0MC00ODJkLWEzYzgtMzk2MTExMzczOTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE0MzQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5N2JjYTY3YjQwYTM1YmE3Y2RkNTNmYzJkYTAxZDcxNWQzY2YxMzkzMGM3YzAzYTRhMmYxYTE0Mzk1YTRiOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aDzeqzWixWokm2dzGGYBbQLhh-zSQjDKSW2aBD9jCMY)

**Comment by MrOxMasTer** [comment]
Do I understand correctly that these are the binaries that should be included in the final build? If so, they kind of are

![image](https://github.com/ranisalt/node-argon2/assets/59291123/9f6ac9f5-a584-49a5-8a21-a02bafec50a7)

**Comment by MrOxMasTer** [comment]
> How are you using it in middleware?

The amazing thing is that it doesn't, but it causes an error.

![image](https://github.com/ranisalt/node-argon2/assets/59291123/fe2b43f0-058d-4423-8073-f4ce4df19245)
![image](https://github.com/ranisalt/node-argon2/assets/59291123/dd88c26c-7a61-4337-b8ad-24e20cc9dc9a)

In the instance that is used in middleware - not used, but it is used in another NextAuth instance in the authentication function

![image](https://github.com/ranisalt/node-argon2/assets/59291123/8c6d63ac-3c40-4b59-9910-d61a0d38a320)

**Comment by MrOxMasTer** [comment]
> How are you using it in middleware?
which is on par with middleware

![image](https://github.com/ranisalt/node-argon2/assets/59291123/6dcb8a43-f41c-4675-a8eb-75a5808cad10)

**Comment by ranisalt** [comment]
I don't get the same failure with this minimal reproduction: https://github.com/ranisalt/argon2-nextjs-standalone

So I would start from there. Not sure if it makes a difference, but I used `'/login'` instead of `'/'`

Tip: the `node` Docker images already set up a non-root user, called `node`, with uid 1000.

> not load unnecessary binaries that are not needed by a particular distribution

You can control this using environment variable, like this:

```js
...
    outputFileTracingIncludes: {
      "/login": [`./node_modules/argon2/prebuilds/${process.env.ARGON2_PREBUILDS_GLOB || '**'}`],
    },
...
```

And in your Dockerfile, specify

```dockerfile
ENV ARGON2_PREBUILDS_GLOB="linux-x64/*.musl.*```

Or some other variation of the same idea

**Comment by MrOxMasTer** [comment]
> I don't get the same failure with this minimal reproduction: https://github.com/ranisalt/argon2-nextjs-standalone
> 
> So I would start from there. Not sure if it makes a difference, but I used `'/login'` instead of `'/'`
> 
> Tip: the `node` Docker images already set up a non-root user, called `node`, with uid 1000.

Well, first of all, I have middleware working for many pages, so it looks strange to set 1 page at a time. 

And secondly it won't fix the problem. I showed you standalone build before and next.js doesn't remove these files, so the answer should be found not in next.js, but elsewhere

![image](https://github.com/ranisalt/node-argon2/assets/59291123/0453c933-ec8f-4c63-82e8-7b9c1c7134f2)

**Comment by ranisalt** [comment]
Please raise a bug in https://github.com/vercel/next.js so we can keep track together and I can make the changes needed if the issue is with this library

**Comment by MrOxMasTer** [comment]
> Please raise a bug in https://github.com/vercel/next.js so we can keep track together and I can make the changes needed if the issue is with this library

Okay, thanks, I'll create it, but a little later. I have such an assumption. It can't be because of pnp that it somehow optimizes library imports, so is that such a thing? I'll try to test it later on a regular npm

**Comment by MrOxMasTer** [comment]
I'm sorry that I haven't created issues yet, but I didn't have time. 
Does it relate to this topic in any way?

https://github.com/vercel/next.js/pull/65204

As I understand it, it says about packages that cannot be combined and it says about argon2

**Comment by MrOxMasTer** [comment]
I decided to try switching to npm normal temporarily and see if anything happens.

Two strange situations have arisen.

1) Next.js flat out refuses to compile pages that have dynamic data retrieval from the database.

I for a long time did not understand why I have on npm basic pages (for example: ‘/’) just did not compile and tried to understand, maybe I did something wrong, but it turned out in the matter in the server components in which I call the database.

![image](https://github.com/ranisalt/node-argon2/assets/59291123/74299ed1-ef6a-4338-970f-ea7c04154ac8)

I don't understand why next.js even cares at the compilation stage whether it is connected to postgresQL or not. 

2) Another situation is interesting. I remove these dynamically parts for a while and I have missing errors related to argon2 and their imports.
Maybe it's really about pnpm and the fact that it breaks the imports in the library

**Comment by MrOxMasTer** [comment]
I switched back to ppm and in the absence of these dynamic parts, everything works for me

![image](https://github.com/ranisalt/node-argon2/assets/59291123/82d8ff44-5edb-4094-824e-6a2e028c39ac)

**Comment by MrOxMasTer** [comment]
I tried using pnpm and it works.
Now I connected to the local database and it works and does not show any errors. 
I don't understand what happened. I know I updated next.js from 14.2.1 to 14.2.3(which I have now)

And I don't remember if I updated pnpm, but if you look at the latest screenshots inside the docker container, the build has changed!

Before:

![image](https://github.com/ranisalt/node-argon2/assets/59291123/1dc5163e-474b-45a6-959b-ef9bbcb6f8e5)

After:
![image](https://github.com/ranisalt/node-argon2/assets/59291123/f15d9200-5564-4e45-bb6b-ff2cf4c0b897)
![image](https://github.com/ranisalt/node-argon2/assets/59291123/ba4f4733-c6e4-4d69-b6cc-5a9bfbbd2376)

**Comment by MrOxMasTer** [comment]
You were right, I unchecked the setting and it's showing me again that I don't have any binary files. You were right when you said next.js doesn't put those files in.

![image](https://github.com/ranisalt/node-argon2/assets/59291123/fd0d0dbd-c001-4689-ae94-25e8e735d285
![image](https://github.com/ranisalt/node-argon2/assets/59291123/7d13b266-9e24-41b1-8ed6-f863a5e75425)

**Comment by MrOxMasTer** [comment]
I added:

```js
    outputFileTracingIncludes: {
      '/auth': [
        `./node_modules/argon2/prebuilds/${process.env.ARGON2_PREBUILDS_GLOB || '**'}`,
      ],
    },
```

And it worked

**Comment by MrOxMasTer** [comment]
I tried adding ‘/’ for the page

```js
    outputFileTracingIncludes: {
      '/': [
        `./node_modules/argon2/prebuilds/${process.env.ARGON2_PREBUILDS_GLOB || '**'}`,
      ],
    }
```

it doesn't work:
![image](https://github.com/ranisalt/node-argon2/assets/59291123/9c785a61-cb50-45c8-b921-6fa4d40a7838)

And the prebuilds folder is not there with the binary files:
![image](https://github.com/ranisalt/node-argon2/assets/59291123/a7d6bb69-158c-4aa8-bb4d-fba28af4a35c)

But in the node_modules folder itself, an argon2 folder appears with all these binary files, but they are not in next.js itself
![image](https://github.com/ranisalt/node-argon2/assets/59291123/0ae18d44-8f08-4fcd-938b-1157c281109c)

And when you add for "/auth"  (as I showed above), it works. This is really weird.

**Comment by gligorot** [comment]
Similar issue as OP but with practical reproduction steps in https://github.com/ranisalt/node-argon2/issues/413

**Comment by ranisalt** [comment]
#413 was closed, can you confirm it has also been fixed to you or is it a different issue?
