### ISSUE TITLE
Invalid argument on verify method

### ISSUE THREAD

**Issue by RodriAndreotti** [ranisalt/node-argon2#407]
Hi, could you help me to understando something?
I have used this library in another project last year, and everything worked like a charm.
Today i install it in another project (with updated release) and face the following behavior.

### Steps to reproduce
1. hash a password with following configs:
`{
        parallelism: 1,
        memoryCost: 64000, // 64 mb
        timeCost: 3, // number of itetations
    }`

2. Try to verify this same password with `await argon2.verify(hash, Buffer.from(password), this.config);`

### Expected behaviour
The password could be verified successfully

### Actual behaviour
When trying to verify password with previous generated hash the error `Invalid argument` occurs. This behavior happen only on 0.40+ versions, on version 0.31 everything works fine.

### Environment
Debian Trixie

**Node version:**
Node 22

**Comment by ranisalt** [comment]
Found the issue! It's not possible to pass `parallelism`, `memoryCost` and `timeCost` to `verify`, since those are read from the hash, but omitting `secret` (the only possible option) causes it to fail on [argon2_node.cpp#L94](https://github.com/ranisalt/node-argon2/blob/ebc6ed71b1c8aad5342f33791b966432e85cd259/argon2_node.cpp#L94)

**Comment by ranisalt** [comment]
v0.40.2 should fix this issue

**Comment by RodriAndreotti** [comment]
Great news!
Thanks to the quickly return.
I'll wait for you to have some time to look at this.
But, thank you in advance!

And congratulations on the project.

**Comment by ranisalt** [comment]
@RodriAndreotti v0.40.3 has been published with a fix. Unfortunately, GitHub Actions is messing with me and I couldn't tag a release, but it's on NPM already so you can update on your project. Obrigado :wink:

**Comment by RodriAndreotti** [comment]
You're welcome.
I tried this new version and it's working like a charm:
![image](https://github.com/ranisalt/node-argon2/assets/9449048/a817116f-b7e9-4506-b35a-e69a831919d9)
