### ISSUE TITLE
Enhancement: Promises

### ISSUE THREAD

**Issue by Dasch42** [ranisalt/node-argon2#44]
I was just wondering if it would be a possibility to add an option for using Bluebird promises? Currently, the native promises are causing me headaches when in combination with Bluebird's filtered catches.

I tried to fork the library, and simply make my own changes, but I could not for the life of me get it to compile. It just kept giving me node-gyp errors.

**Comment by ranisalt** [comment]
Gonna have a look.

**Comment by ranisalt** [comment]
Please checkout the [bluebird](https://github.com/ranisalt/node-argon2/tree/bluebird) branch, I fixed it so you can change the `Promise` property of the exported object to use a custom promise.

See an example on [bluebird.spec.js](https://github.com/ranisalt/node-argon2/blob/bluebird/bluebird.spec.js#L5), it's really a one-liner.

**Comment by Dasch42** [comment]
As far as I can tell, it works. My code once again catches the right errors, at the right places.

However, I cant for the life of me get npm to actually fetch and install it properly, by the github reference. But cloning, init'ing, and building with node-gyp manually, makes it work perfectly! :+1:

**Comment by ranisalt** [comment]
Yeah, npm makes it pretty hard to sync to branches.

Did you feel any improvements from using Bluebird? It plays nice with basic, default hash but it doesn't scale time and memory cost very well to me.

**Comment by Dasch42** [comment]
Do you have any advice for how something like this could easily be handled? Currently I have an install-argon.sh script being executed during install, after having run npm-install on the project.

The improvements I felt, was _actual_ compatibility with my own codebase. I've been relying pretty heavily on the Bluebird's filtered catches, in order to create what I feel is more readable code. I was using a BCrypt library previously, which was "promisified" using Bluebird. 

But everything involved with hashing and verification unfortunately completely broke, after plugging in your Argon2 library _(which supposedly is superior)_. So unfortunately, that is the only aspect I can even argue improvements -- which is horribly un-scientific.
