### ISSUE TITLE
C++11 issues with clang at install time

### ISSUE THREAD

**Issue by jdconley** [ranisalt/node-argon2#49]
### Steps to reproduce
1. Followed the basic instructions for node-argon2 v0.12.0 and tried to install with: `CXX=clang++ npm install argon2 --save`

### Expected behaviour
The module should install without error.

### Actual behaviour
The module failed to install with the following error:

```
../src/argon2_node.cpp:6:10: fatal error: 'tuple' file not found
#include <tuple>
         ^
```
This led me to believe the C++11 stdlib wasn't being loaded.

I confirmed by adding the following to the installation command line:

```
CXX='clang++ -std=c++11 -stdlib=libc++' npm install argon2 --save
```

This workaround was successful. But, it seems there is an issue with the targets in the gyp configuration. I found an interesting SO on how to setup the targets in the gyp config. http://stackoverflow.com/questions/25645057/node-gyp-cannot-compile-a-nodejs-extension-fatal-error-thread-file-not-found

### Environment
OSX 10.11.5

**Node version:**
6.3.0

**Compiler version:**
node-gyp=3.4.0
clang++=Apple LLVM version 7.3.0 (clang-703.0.31)

**Comment by ranisalt** [comment]
Interesting. I never had any problems, and I was pretty sure `-std=c++11` was default for node-gyp. It will not happen with GCC as it now defaults to `-std=c++14`.

You should add `"cflags": ["-std=c++11"]` to the `argon2` target. You might do it and I will merge, or wait until I can fix it.

**Comment by jdconley** [comment]
I'm working on the PR right now to override the defaults. Unfortunately, just adding the "cflags" wasn't enough. It was the "OTHER_CPLUSPLUSFLAGS" under the "xcode_settings" option that I had to set.

On this system, this is what gets output with `node-gyp rebuild --loglevel=silly`. Looks like this system is setup to do `-std=gnu++0x` by default. This was likely something with when I was messing with early C++11, or Unity, or something...

```
  c++ '-DNODE_GYP_MODULE_NAME=argon2' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' '-DNDEBUG' -I/Users/jdconley/.node-gyp/6.3.0/include/node -I/Users/jdconley/.node-gyp/6.3.0/src -I/Users/jdconley/.node-gyp/6.3.0/deps/uv/include -I/Users/jdconley/.node-gyp/6.3.0/deps/v8/include -I../node_modules/nan -I../argon2/include  -Os -gdwarf-2 -mmacosx-version-min=10.7 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-exceptions -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/argon2/src/argon2_node.o.d.raw   -c -o Release/obj.target/argon2/src/argon2_node.o ../src/argon2_node.cpp
../src/argon2_node.cpp:6:10: fatal error: 'tuple' file not found
#include <tuple>
         ^
```
