### ISSUE TITLE
feature request: expose "Secret value K" option

### ISSUE THREAD

**Issue by NodeGuy** [ranisalt/node-argon2#58]
Page 5 of [the Argon2 paper](https://github.com/P-H-C/phc-winner-argon2/raw/master/argon2-specs.pdf) specifies a secondary input:

> Secret value _K_ (serves as key if necessary, but we do not assume any key use by default) may have any
> length from 0 to 32 bytes.

I would like to use Argon2 to combine a user-supplied passphrase with a randomly-generated 32 byte key (not the salt).  Please allow me to pass in a value for K.

**Comment by ranisalt** [comment]
Can you do it? I can just look at it later (tomorrow or so)

**Comment by NodeGuy** [comment]
Thanks; I'm not in a hurry and can take a stab at it in the future.

**Comment by markfejes** [comment]
Currently it looks like that the official argon2 repo does not support the secret(K) parameter with the argon2_hash function, So i think it should be reported there, though I will take a look at it when I'll have some time.

**Comment by ranisalt** [comment]
@markfejes it does through some other function that take an argon2 context as parameter, argon2_hash is just a shortcut function.

**Comment by markfejes** [comment]
Yes, you are right, indeed. But i don't think, that using the argon2_ctx function would be a pretty approach :) I think it would be wise if one would stick to the argon2_hash function, don't you think? If you want, I could make the argon2_ctx implementation, because this is a really nice-to-have function.

**Comment by ranisalt** [comment]
Nah, I don't think this is critical. To me, Argon2 is still evolving and it's not worth to implement every single feature yet. Of course, if other bindings are implementing those stuff, then we should too not to lag behind.

**Comment by cbhacking** [comment]
Just took a look at this myself. Would be pretty easy to add support for secret (pepper) in the `argon2_hash` function (it's just a wrapper that sets an `argon2_context` and then calls `argon2_ctx` with the specified type) and it just sets `context.secret = NULL`; it would be easy to add an `argon2_secret_hash` or similar that does the same thing but takes the secret as a parameter. I actually am more comfortable doing that than making the change to the Node binding but I assume that would be an easy fix as well...? I may make the change and submit a PR to the argon2 reference impl.

**Comment by ranisalt** [comment]
Once it gets implemented there, it's a breeze to push forward here :)

**Comment by ranisalt** [comment]
Should be easy to implement now with `extractOptions`, just mimic salt extraction.

**Comment by simonepri** [comment]
@ranisalt any news on this? Can I help you somehow?
I'm not able to implement the argon2 paper's [test vectors](https://tools.ietf.org/html/draft-irtf-cfrg-argon2-03#section-6).

**Comment by ranisalt** [comment]
@simonepri you need to change parameter reading on C++.

**Comment by simonepri** [comment]
@ranisalt Also the `version` should be configurable.
https://github.com/ranisalt/node-argon2/blob/master/src/argon2_node.cpp#L75

It makes sense for you?

**Comment by ranisalt** [comment]
Sure. That line is from a previous version of the lib.

**Comment by simonepri** [comment]
> "That line is from a previous version of the lib."

What do you mean?

**Comment by ranisalt** [comment]
It means I wrote it long ago and never bothered with it :P feel free to fix it

**Comment by ranisalt** [comment]
@jilvin there are plans, see #137 

Moving discussion to the related PR.
