### ISSUE TITLE
Improve README/docs understanding

### ISSUE THREAD

**Issue by schang933** [ranisalt/node-argon2#60]
First of all, appreciate the library. I think it's a great start and recommend filling some gaps in the README to aid understanding. As a feature request I'm not providing environment/reproducibility, but let me know if you need it.
- Include a minimum-viable reasonably-secure implementation. Because most people, myself included, are not in the security space. Below is my attempt using old-ES from what I understand of the README. Feel free to let me know if there's any security issues since I'll actually be using it.

``` javascript
var argon2 = require('argon2');

var getPasswordHash = function(password) {
  // Assumes that 16 bytes is good enough for now
  return argon2.generateSalt().then(function(salt) {
    // Assumes defaults don't change (specifically using Argon2i by default)
    return argon2.hash(password, salt);
  });
};

var verifyPassword = function(passwordHash, password) {
  return argon2.verify(passwordHash, password);
};
```
- Improved options documentation. Many libraries will create a table with info like "option name", "option data type", "option default", and "option description". For example, from the README I can't tell what timeCost means. Is it number of seconds it will run before returning something, number of iterations (2^n)? If I need to read Argon2 papers to understand this, preferably link to the excerpt that describes it.

**Comment by ranisalt** [comment]
Can do, though most of that is actually Argon2 related and not exactly from this lib, I feel it's a good thing to do.

I use defaults recommended by Argon2 and used by most implementations, and since the options get stored with the hash, if you want to change the options your old hashes are still valid and working. You can assume that defaults are enough.

**Comment by ranisalt** [comment]
Added a comprehensive options guide to the wiki: https://github.com/ranisalt/node-argon2/wiki/Options

Will work on other parts when I have time.

**Comment by EyalPerry** [comment]
which algorithm version does this library implement?
I think it should be a part of docs.

**Comment by ranisalt** [comment]
@EyalPerry nice addition. We currently track the latest upstream release of [phc-winner-argon2](https://github.com/P-H-C/phc-winner-argon2/releases), though.

**Comment by tiritto** [comment]
I think that documentation could use some simple examples of library usage. Personally, I am literally confused about how to do such a simple thing like saving password hash for future verifications. I know I can just `argon2.verify(hash, 'password')`, but I shouldn't be keeping plain passwords in my db, neither should I let client to send plain password to the server.

The only logical way I can see is to use argon2 on client side to generate and send digest to the server. On server-side I can just compare this digest against hashed password. This is easy. But when user is creating new account and sends digest to the server, I have no clue how am I supposed to get the plain hash out of it for further verifications. I tried to verify digest against another digest but it obivously failed.

**Comment by ranisalt** [comment]
> neither should I let client to send plain password to the server

Yes, you should. When a client signs up or logs in, you will send the password in plain, through a secure channel (HTTPS).



> The only logical way I can see is to use argon2 on client side to generate and send digest to the server

Wrong because of the above. When you hash the password prior to sending to the server, you are effectively making the hash become the password.

> I have no clue how am I supposed to get the plain hash out of it

It is impossible. Argon2 is an one-way function, you can never revert to the preimage.
