### ISSUE TITLE
[feature request] Return unencoded hash

### ISSUE THREAD

**Issue by felipeochoa** [ranisalt/node-argon2#64]
It would be great to allow grabbing the hash as a raw buffer instead of the crypt-encoded string. Right now I'm using a regex to parse the crypt format and then decode the base64 key, but it would be better (and faster) if `node-argon2` just had `argon2` generate the raw key instead of the encoded one.

```js
const cryptRegex = /\$([^$]+)$/;
argon2.hash(password, salt)
  .then(encodedKey => {
    const key = Buffer.from(cryptRegex.exec(encodedKey)[1], 'base64');
})
```

**Comment by markfejes** [comment]
I'll look into this. You will have to pass this:  {raw: true} if you want the promise to resolve with the raw hash only. Is this what you would like to see @felipeochoa?

**Comment by felipeochoa** [comment]
@markfejes amazing, yes!
