### ISSUE TITLE
raw: true isn't working

### ISSUE THREAD

**Issue by lironzua** [ranisalt/node-argon2#71]
I'm using it like this:
        const options = { raw: true, timeCost: 2, memoryCost: 16, parallelism: 1, hashLength: 32 };
        const uidBuffer = new Buffer(uid);
        return argon2.hash(password, uidBuffer, options);
but it produces the encoded hash.. any way to get the raw hash as a buffer?

**Comment by ranisalt** [comment]
What version are you using? Raw password support is only included on v0.15+

**Comment by lironzua** [comment]
argon2@0.14.1
I also tried passing in the password as a buffer... it still yields the hash

**Comment by lironzua** [comment]
Thanks!
