### ISSUE TITLE
Cannot Use argon2.defaults When Using .hash()

### ISSUE THREAD

**Issue by rdegges** [ranisalt/node-argon2#8]
The following code errors out, when it should be working according to the docs:

```javascript
'use strict';

var argon = require('argon2');

var password = 'xxx!';

argon.generateSalt((err, salt) => {
  if (err) {
    throw err;
  }

  // the argon.defaults param is what breaks the code
  argon.hash(password, salt, argon.defaults, (err, hash) => {
    if (err) {
      throw err;
    }

    console.log('Successfully created Argon2 hash:', hash);
  });
});
```

It errors with:

```/Users/rdegges/Dropbox/Code/testing/argon/node_modules/argon2/index.js:29
  Object.assign(options, Object.assign({}, defaults, options));
         ^

TypeError: Cannot assign to read only property 'timeCost' of #<Object>
    at Function.assign (native)
    at validate (/Users/rdegges/Dropbox/Code/testing/argon/node_modules/argon2/index.js:29:10)
    at Object.exports.hash (/Users/rdegges/Dropbox/Code/testing/argon/node_modules/argon2/index.js:64:7)
    at /Users/rdegges/Dropbox/Code/testing/argon/test.js:12:9
    at InternalFieldObject.ondone (/Users/rdegges/Dropbox/Code/testing/argon/node_modules/argon2/index.js:85:5)
```

It works if I remove the `argon.defaults` call, but I'm assuming that should work =)

**Comment by cgmb** [comment]
I haven't tried this, but I notice that the title says `argon2.defaults`, while the code says `argon.defaults`.

**Comment by rdegges** [comment]
That was just from my own require statement, just named it `argon` for convenience, heh.

**Comment by ranisalt** [comment]
That's because `defaults` is a **frozen** default map for reading only (e.g. you want to double the default time cost, you'd use `{timeCost: argon.defaults.timeCost * 2}`, but there's no need to pass it since defaults will be used anyway. Just omit the third argument if you want to use the defaults.
