### ISSUE TITLE
argon2.hash() method terminates the program

### ISSUE THREAD

**Issue by agauniyal** [ranisalt/node-argon2#83]
### Before creating an issue, please be sure to:
- [x] Checkout to the latest version, **including submodules**
- [x] Try to find an *isolated* way to reproduce the behavior
- [x] Fill in all the blanks in the most specific way you can

### Steps to reproduce
1. Install argon2
2. use `argon2.hash(password);` method with async await

Eg.
```javascript
try {
    const hash1 = await argon2.hash(undefined);
} catch (e) {
    console.log(e);
}
```

### Expected behavior
The error should be caught and application should not terminate

### Actual behaviour
The error is not caught by` catch(e) {  }` block and instead terminates the whole application with following output -

```
buffer.js:161
  throw new TypeError(kFromErrorMsg);
  ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:161:9)
    at RandomBytes.crypto.randomBytes [as ondone] (/home/agauniyal/projects/gsoc/crossroads/node_modules/argon2/index.js:45:30)
```

### Environment
**Operating system**:
Arch Linux
**Node version:**
8.1.0
**Compiler version:**
gcc (GCC) 7.1.1 20170516

**Comment by ranisalt** [comment]
I'm not sure it even makes sense to prevent invoking the method on an insane way. It clearly is *not* an issue with the method or it's parameters but with the caller.

What is the use case?

**Comment by agauniyal** [comment]
Was just testing the scenario when this code throws and my catch block executes, seemed a quick way to do this.

**Comment by ranisalt** [comment]
I think so. This is an user input issue, the undefined input is not on the domain of the hash function. It could (re)throw a TypeError once it happens.

Also, since most of the errors `hash` can throw are either misconfigured options (which you don't use) or lack of memory/invalid accesses (which isn't really catchable), you can even drop the try/catch if you check the password first.

**Comment by agauniyal** [comment]
ok sure! thanks for clarifying the issue here 👍
