### ISSUE TITLE
can't install argon2

### ISSUE THREAD

**Issue by dwikip** [ranisalt/node-argon2#9]
Hello,
this error appear when installing node-argon2

../src/argon2_node.cpp:51:13: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
             plain.c_str(), plain.size(), salt.c_str(), salt.size(), nullptr,
             ^
../src/argon2_node.cpp:11:7: error: expected nested-name-specifier before ‘uint’
 using uint = unsigned int;
       ^
../src/argon2_node.cpp:11:12: error: expected ‘;’ before ‘=’ token
 using uint = unsigned int;
            ^
../src/argon2_node.cpp:11:12: error: expected unqualified-id before ‘=’ token
../src/argon2_node.cpp:13:7: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
 const auto ENCODED_LEN = 108u;
       ^
../src/argon2_node.cpp:13:12: error: ‘ENCODED_LEN’ does not name a type
 const auto ENCODED_LEN = 108u;
            ^
../src/argon2_node.cpp:14:7: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
 const auto HASH_LEN = 32u;
       ^
../src/argon2_node.cpp:14:12: error: ‘HASH_LEN’ does not name a type
 const auto HASH_LEN = 32u;
            ^
../src/argon2_node.cpp:15:7: warning: ‘auto’ changes meaning in C++11; please remove it [-Wc++0x-compat]
 const auto SALT_LEN = 16u;
       ^
../src/argon2_node.cpp:15:12: error: ‘SALT_LEN’ does not name a type
 const auto SALT_LEN = 16u;
            ^

attached full log :
[log.txt](https://github.com/ranisalt/node-argon2/files/104562/log.txt)
using ubuntu 14.0.4 and gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4

Please help....
thank you

**Comment by cgmb** [comment]
These bindings use C++11 features which need to be enabled by a compiler flag. It appears that setting is inherited from `common.gypi` in node, and C++11 features were first enabled in nodejs/node@e43c109891dcdce3da30de1baee1d2c97cabfcd9. The first release containing that commit was node `v1.0.0`.

I see from the log file that you're using node `v0.10.25`. You may be able to resolve the problem by updating to a newer version of node. node-argon2 is tested against everything newer than node 4.0, so I think either node LTS or node Stable should be fine.

**Comment by dwikip** [comment]
thank you @cgmb 
its working fine now
thanks

**Comment by ranisalt** [comment]
I made it clear on the README now that Node 4.0 is required. Thanks!
