### ISSUE TITLE
macOS installation problem

### ISSUE THREAD

**Issue by rockchalkwushock** [ranisalt/node-argon2#92]
I am receiving the following error message upon trying to install the library:

```sh
rockchalkwushock in argon2-test $ CXX=g++-6 npm install --save argon2

> argon2@0.16.1 install /Users/rockchalkwushock/Desktop/argon2-test/node_modules/argon2
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  LIBTOOL-STATIC Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
make: g++-6: No such file or directory
make: *** [Release/obj.target/argon2/src/argon2_node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rockchalkwushock/.nvm/versions/node/v8.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/rockchalkwushock/.nvm/versions/node/v8.2.1/bin/node" "/Users/rockchalkwushock/.nvm/versions/node/v8.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rockchalkwushock/Desktop/argon2-test/node_modules/argon2
gyp ERR! node -v v8.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN argon2-test@1.0.0 No description
npm WARN argon2-test@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.16.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the argon2@0.16.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rockchalkwushock/.npm/_logs/2017-08-26T13_57_35_993Z-debug.log
```

I followed the instructions in the README & went and checked on the [`node-gyp`]() installation as well. I'm seeing three things that don't add up, but am unsure how to handle them:

1. `xcodebuild`: 

```sh
which xcodebuild # /usr/bin/xcodebuild
```

2.`'/Library/Developer/CommandLineTools'` doesn't exist in file structure

3. `gcc`:

I don't believe the `brew install gcc` is taking precedence over the native `gcc` on the Mac. I say this because anything installed with `brew` should be located at `/usr/local/bin/<formula>` and I receive back `/usr/bin/gcc` which holds all the native binaries the Mac comes with.

```sh
rockchalkwushock in argon2-test $ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### Environment
| Tech                    | Version |
|-----------------|---------|
| macOS                | 10.12.6  |
| `node`               | 8.2.1       |
| `yarn`                | 0.27.5     |
| `npm`                | 5.3.0       |
| `node-gyp`       | 3.6.2.      |
| `python`            | 2.7.10     |
| `xcode-select` | 2347      |

**Comment by ranisalt** [comment]
What version of gcc is installed when you brew install it? Is it possible to see?

**Comment by rockchalkwushock** [comment]
@ranisalt 

I was able to get the versions by traveling to the directory `homebrew` saves to:

## `/usr/local/bin`

![screen shot 2017-08-28 at 05 18 36](https://user-images.githubusercontent.com/19720404/29769552-82b48776-8bb0-11e7-964a-cce37d4f5970.png)

**Comment by rockchalkwushock** [comment]
The current `PATH` on my Mac shows as:

```sh
PATH = /Users/rockchalkwushock/.nvm/versions/node/v8.2.1/bin:/Users/rockchalkwushock/.config/yarn/global/node_modules/.bin:/Users/rockchalkwushock/.config/yarn/global/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:
```

I see that `usr/local/bin:` is referenced prior to `usr/` so the `brew install gcc` should be read and linked prior to that of the local `gcc`. All other `homebrew` installed packages are working fine. Following along with this [post](https://stackoverflow.com/questions/28970935/osx-replace-gcc-version-4-2-1-with-4-9-installed-via-homebrew) I was able to set a symbolic link and updated my `PATH`:

```sh
cd /usr/local/Cellar/gcc/7.2.0/bin
ln -s gcc-7 gcc
vi .bash_profile
export PATH="/usr/local/Cellar/gcc/7.2.0/bin:$PATH";
source .bash_profile
which gcc # /usr/local/bin/gcc
gcc --version # gcc (Homebrew GCC 7.2.0) 7.2.0
```

`gcc` is pointing to the correct version now for sure. I created a new directory and ran the following command and received back the error messages in the below screenshot now:

```sh
rockchalkwushock in argon2-test $ CXX=g++-7 npm install --save argon2
```

![screen shot 2017-08-28 at 06 24 48](https://user-images.githubusercontent.com/19720404/29771557-0ac0fda8-8bba-11e7-819a-04aa7aac7722.png)

It seems there is still an issue with `xcodebuild` as well as the _unrecognized command_ :

**'-stdlib=libc++'**

Any further ideas on this? It has been years since I wrote anything in C & I believe the unrecognized command is dealing with C/C++.

**Comment by ranisalt** [comment]
According to [this](https://stackoverflow.com/a/19774902/1940360), the default stdlib for g++ in macOS is libc++ since Mavericks (10.9), but I don't know how it affects brew.

You can try adding below [this](https://github.com/ranisalt/node-argon2/blob/master/binding.gyp#L8) line:
```js
"cflags!": ["-stdlib=libc++"],
```

If it doesn't work, try clang.

**Comment by rockchalkwushock** [comment]
@ranisalt 

So clone the source to my machine and add that snippet, then run

```sh
CXX=g++-6 npm install ./temp/node-argon2
```

**Comment by rockchalkwushock** [comment]
@ranisalt 

```sh
CXX=clang++ npm install --save argon2 # that did the trick
```

Compiles and the code runs as it should, thanks for your help with figuring this out. Closing

**Comment by kaansoral** [comment]
`CXX=clang++ npm install argon2`

Should be added to the Readme, I had the same issue, this solved it, thanks @rockchalkwushock
