### ISSUE TITLE
Grow beyond password hashing, Specifically: Raw Hash

### ISSUE THREAD

**Issue by knanan** [ranisalt/node-argon2#94]
I see there is a strong commitment to keep this plugin, the major and only node.js port only for password hashing, however Argon2 is bigger than that

My request is:
1) Raw/String Hash Option
2) Custom Salt Option

I'm personally switching to CLI usage, from syntax to functionality, this plugin disappointed me at every turn, I've lost a good 1.5 hours of my life :(

**Comment by ranisalt** [comment]
You can currently select raw hashing with `raw: true` option, and I'm doing internal stuff to allow custom salt, secret and other Argon2 parameters.

**Comment by Slapbox** [comment]
Awesome work @ranisalt 

Is custom salt allowed yet?

**Comment by ranisalt** [comment]
Long ago, just pass a `salt` option with a buffer:

```await argon2.hash(password, {salt: Buffer.from('the salt you want')})```

**Comment by Slapbox** [comment]
Ah thanks! I poked around but didn't see that.
