### ISSUE TITLE
argon2.verify directly a hash byte Buffer instead of a MCF string hash

### ISSUE THREAD

**Issue by ibudisteanu** [ranisalt/node-argon2#96]
Hi. I really love Argon2, but I have an issue that I can't solve it. I started using Argon2 today, and I was able to return both types of hashes (Buffer bytes and String).

Buffer bytes hash

`<Buffer e2 ab 80 d2 89 67 3e 66 82 00 06 74 cd 39 54 44 6e fa fd f3 5a 37 d3 5e d6 d4 ad 4d 33 5d f0 5c> 
`
String hash

`$argon2i$v=19$m=4096,t=3,p=1$qlRSRgw72QD+Cw54MA18fQ$NW+po4QNXi1msPTkiYtElpJoIX6PhQk5PsF6PY7B4Vg`

I can see that the String hash contains more parameters used in the hashing algorithm, but I believe that all my nodes will use the **same hashing options**, so it is very pointless for me to send the entire string in the network and not just the Buffer bytes (which are more optimal). Moreover, I believe I don't need salt for Proof of Work blocks. Right?

When I call the function **verify** directly with the Buffer bytes, Argon2 returns me the regex error, because I can not provide the options directly to the verify function. **Error: Invalid hash, must be in MCF, generated by Argon2."**

How can I solve this problem by proving the options directly alongside with the Buffer to verify my Buffer byte hash, and not a string

**Comment by ranisalt** [comment]
I am working on that issue, and will publish a new release soon.

**Comment by ibudisteanu** [comment]
@ranisalt  Actually the function to verify/validate a hash is to rehash again the initial data in order to check their equality

**Comment by ranisalt** [comment]
The raw hash doesn't contain parameter data, thus you need to supply it to the verify function. On the other hand, the encoded hash does contain parameters and they are parsed prior to verify.

**Comment by ranisalt** [comment]
@ibudisteanu should you need to verify raw hashes, just hash the plain text with the same parameters *and* `raw: true` and compare the buffers.
